// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content-feed/bump-touch-point.proto

package ContentFeedService_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Bump touch point card
// an advertisement for Bumps, containing bumpable listings belonging to the user
//
// @param
// balance: user's current balance
// items: user's bumpable listings
type BumpTouchPointCard struct {
	Balance              string                `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Items                []*BumpTouchPointItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BumpTouchPointCard) Reset()         { *m = BumpTouchPointCard{} }
func (m *BumpTouchPointCard) String() string { return proto.CompactTextString(m) }
func (*BumpTouchPointCard) ProtoMessage()    {}
func (*BumpTouchPointCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_64c07aadaad8cb55, []int{0}
}

func (m *BumpTouchPointCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BumpTouchPointCard.Unmarshal(m, b)
}
func (m *BumpTouchPointCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BumpTouchPointCard.Marshal(b, m, deterministic)
}
func (m *BumpTouchPointCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BumpTouchPointCard.Merge(m, src)
}
func (m *BumpTouchPointCard) XXX_Size() int {
	return xxx_messageInfo_BumpTouchPointCard.Size(m)
}
func (m *BumpTouchPointCard) XXX_DiscardUnknown() {
	xxx_messageInfo_BumpTouchPointCard.DiscardUnknown(m)
}

var xxx_messageInfo_BumpTouchPointCard proto.InternalMessageInfo

func (m *BumpTouchPointCard) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *BumpTouchPointCard) GetItems() []*BumpTouchPointItem {
	if m != nil {
		return m.Items
	}
	return nil
}

//*
// Bumpable listing
//
// @param
// price: price set on the listing
type BumpTouchPointItem struct {
	ProductId            string                     `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Title                string                     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price                string                     `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl             string                     `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BumpPrices           []*BumpTouchPointPriceItem `protobuf:"bytes,5,rep,name=bump_prices,json=bumpPrices,proto3" json:"bump_prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BumpTouchPointItem) Reset()         { *m = BumpTouchPointItem{} }
func (m *BumpTouchPointItem) String() string { return proto.CompactTextString(m) }
func (*BumpTouchPointItem) ProtoMessage()    {}
func (*BumpTouchPointItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_64c07aadaad8cb55, []int{1}
}

func (m *BumpTouchPointItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BumpTouchPointItem.Unmarshal(m, b)
}
func (m *BumpTouchPointItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BumpTouchPointItem.Marshal(b, m, deterministic)
}
func (m *BumpTouchPointItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BumpTouchPointItem.Merge(m, src)
}
func (m *BumpTouchPointItem) XXX_Size() int {
	return xxx_messageInfo_BumpTouchPointItem.Size(m)
}
func (m *BumpTouchPointItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BumpTouchPointItem.DiscardUnknown(m)
}

var xxx_messageInfo_BumpTouchPointItem proto.InternalMessageInfo

func (m *BumpTouchPointItem) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *BumpTouchPointItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BumpTouchPointItem) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *BumpTouchPointItem) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *BumpTouchPointItem) GetBumpPrices() []*BumpTouchPointPriceItem {
	if m != nil {
		return m.BumpPrices
	}
	return nil
}

//*
// Bump price for a listing
//
// @param
// option: bump type, e.g. PAID-3D-BUMP
// context: encrypted string containing pricing information. The client should send this with
//their purchase request to guarantee their quoted price.
type BumpTouchPointPriceItem struct {
	Option               string   `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Price                string   `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Context              string   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BumpTouchPointPriceItem) Reset()         { *m = BumpTouchPointPriceItem{} }
func (m *BumpTouchPointPriceItem) String() string { return proto.CompactTextString(m) }
func (*BumpTouchPointPriceItem) ProtoMessage()    {}
func (*BumpTouchPointPriceItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_64c07aadaad8cb55, []int{2}
}

func (m *BumpTouchPointPriceItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BumpTouchPointPriceItem.Unmarshal(m, b)
}
func (m *BumpTouchPointPriceItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BumpTouchPointPriceItem.Marshal(b, m, deterministic)
}
func (m *BumpTouchPointPriceItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BumpTouchPointPriceItem.Merge(m, src)
}
func (m *BumpTouchPointPriceItem) XXX_Size() int {
	return xxx_messageInfo_BumpTouchPointPriceItem.Size(m)
}
func (m *BumpTouchPointPriceItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BumpTouchPointPriceItem.DiscardUnknown(m)
}

var xxx_messageInfo_BumpTouchPointPriceItem proto.InternalMessageInfo

func (m *BumpTouchPointPriceItem) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *BumpTouchPointPriceItem) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *BumpTouchPointPriceItem) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func init() {
	proto.RegisterType((*BumpTouchPointCard)(nil), "ContentFeedService_proto.BumpTouchPointCard")
	proto.RegisterType((*BumpTouchPointItem)(nil), "ContentFeedService_proto.BumpTouchPointItem")
	proto.RegisterType((*BumpTouchPointPriceItem)(nil), "ContentFeedService_proto.BumpTouchPointPriceItem")
}

func init() {
	proto.RegisterFile("content-feed/bump-touch-point.proto", fileDescriptor_64c07aadaad8cb55)
}

var fileDescriptor_64c07aadaad8cb55 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6a, 0xe3, 0x30,
	0x14, 0x24, 0xce, 0x26, 0x59, 0x2b, 0x37, 0xb1, 0xec, 0x0a, 0x96, 0x42, 0x48, 0x2f, 0x39, 0xd4,
	0x36, 0x6d, 0x8f, 0xbd, 0x25, 0x10, 0xc8, 0xa5, 0x84, 0xb4, 0xbd, 0x94, 0x82, 0x91, 0xa5, 0x57,
	0x47, 0x60, 0x5b, 0x42, 0x7e, 0x2a, 0xfd, 0xb6, 0x7e, 0x45, 0x3f, 0xa9, 0x48, 0x76, 0x68, 0x5a,
	0x08, 0xf4, 0x38, 0x33, 0x6f, 0xde, 0x9b, 0xb1, 0x45, 0xce, 0x85, 0x6e, 0x10, 0x1a, 0x4c, 0x9e,
	0x01, 0x64, 0x56, 0xb8, 0xda, 0x24, 0xa8, 0x9d, 0xd8, 0x27, 0x46, 0xab, 0x06, 0x53, 0x63, 0x35,
	0x6a, 0xca, 0x56, 0xdd, 0xd0, 0x1a, 0x40, 0xde, 0x81, 0x7d, 0x51, 0x02, 0xf2, 0xa0, 0xcc, 0x2d,
	0xa1, 0x4b, 0x57, 0x9b, 0x7b, 0x6f, 0xd9, 0x7a, 0xc7, 0x8a, 0x5b, 0x49, 0x19, 0x99, 0x14, 0xbc,
	0xe2, 0x8d, 0x00, 0x36, 0x98, 0x0d, 0x16, 0xf1, 0xee, 0x00, 0xe9, 0x92, 0x8c, 0x14, 0x42, 0xdd,
	0xb2, 0x68, 0x36, 0x5c, 0x4c, 0xaf, 0x2e, 0xd2, 0x53, 0x9b, 0xd3, 0xaf, 0x6b, 0x37, 0x08, 0xf5,
	0xae, 0xb3, 0xce, 0xdf, 0x07, 0xdf, 0x8f, 0x7a, 0x95, 0x9e, 0x11, 0x62, 0xac, 0x96, 0x4e, 0x60,
	0xae, 0x64, 0x7f, 0x37, 0xee, 0x99, 0x8d, 0xa4, 0x7f, 0xc8, 0x08, 0x15, 0x56, 0xc0, 0xa2, 0xa0,
	0x74, 0xc0, 0xb3, 0xc6, 0x2a, 0x01, 0x6c, 0xd8, 0xb1, 0x01, 0xd0, 0xff, 0x24, 0x56, 0x35, 0x2f,
	0x21, 0x77, 0xb6, 0x62, 0xbf, 0x82, 0xf2, 0x3b, 0x10, 0x0f, 0xb6, 0xa2, 0x3b, 0x32, 0xf5, 0x9f,
	0x29, 0x0f, 0xa3, 0x2d, 0x1b, 0x85, 0x22, 0x97, 0x3f, 0x2d, 0xb2, 0xf5, 0xae, 0xd0, 0x86, 0xf8,
	0x2d, 0x01, 0xb6, 0x73, 0x4e, 0xfe, 0x9d, 0x18, 0xa3, 0x7f, 0xc9, 0x58, 0x1b, 0x54, 0xba, 0xe9,
	0x2b, 0xf5, 0xe8, 0x33, 0x79, 0x74, 0x9c, 0x9c, 0x91, 0x49, 0xf8, 0xa1, 0xaf, 0xd8, 0x37, 0x3a,
	0xc0, 0xe5, 0xd3, 0xe3, 0x6d, 0xa9, 0x70, 0xef, 0x8a, 0x54, 0xe8, 0x3a, 0x13, 0xdc, 0x6a, 0xd7,
	0x42, 0x55, 0x65, 0xed, 0x9e, 0x5b, 0x90, 0x49, 0xc8, 0x9a, 0x95, 0xd0, 0x64, 0xa5, 0xce, 0x8e,
	0xdf, 0xc4, 0xcd, 0xa9, 0x62, 0x6f, 0x51, 0xbc, 0x5a, 0xf7, 0x4c, 0x31, 0x0e, 0xd4, 0xf5, 0x47,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x08, 0xac, 0xf1, 0x4f, 0x02, 0x00, 0x00,
}
