// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content-feed/cats.proto

package ContentFeedService_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdVersion int32

const (
	AdVersion_DEFAULT_AD_VERSION    AdVersion = 0
	AdVersion_SPOTLIGHT_REBRAND     AdVersion = 1
	AdVersion_WITH_EXTERNAL_ADS     AdVersion = 2
	AdVersion_WITH_SINGLE_SLOT      AdVersion = 3
	AdVersion_WITH_EXTERNAL_VID_ADS AdVersion = 4
	AdVersion_WITH_PROFILE_ADS      AdVersion = 5
	AdVersion_WITH_DSS_ADS          AdVersion = 6
	AdVersion_WITH_SHOUTOUT_ADS     AdVersion = 7
)

var AdVersion_name = map[int32]string{
	0: "DEFAULT_AD_VERSION",
	1: "SPOTLIGHT_REBRAND",
	2: "WITH_EXTERNAL_ADS",
	3: "WITH_SINGLE_SLOT",
	4: "WITH_EXTERNAL_VID_ADS",
	5: "WITH_PROFILE_ADS",
	6: "WITH_DSS_ADS",
	7: "WITH_SHOUTOUT_ADS",
}

var AdVersion_value = map[string]int32{
	"DEFAULT_AD_VERSION":    0,
	"SPOTLIGHT_REBRAND":     1,
	"WITH_EXTERNAL_ADS":     2,
	"WITH_SINGLE_SLOT":      3,
	"WITH_EXTERNAL_VID_ADS": 4,
	"WITH_PROFILE_ADS":      5,
	"WITH_DSS_ADS":          6,
	"WITH_SHOUTOUT_ADS":     7,
}

func (x AdVersion) String() string {
	return proto.EnumName(AdVersion_name, int32(x))
}

func (AdVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{0}
}

type PromotedListingCard_PromotedAdType int32

const (
	PromotedListingCard_PROMOTED_10      PromotedListingCard_PromotedAdType = 0
	PromotedListingCard_TOP_SPOTLIGHT_10 PromotedListingCard_PromotedAdType = 1
)

var PromotedListingCard_PromotedAdType_name = map[int32]string{
	0: "PROMOTED_10",
	1: "TOP_SPOTLIGHT_10",
}

var PromotedListingCard_PromotedAdType_value = map[string]int32{
	"PROMOTED_10":      0,
	"TOP_SPOTLIGHT_10": 1,
}

func (x PromotedListingCard_PromotedAdType) String() string {
	return proto.EnumName(PromotedListingCard_PromotedAdType_name, int32(x))
}

func (PromotedListingCard_PromotedAdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{2, 0}
}

type SellerReview_ReviewType int32

const (
	SellerReview_UNKNOWN  SellerReview_ReviewType = 0
	SellerReview_POSITIVE SellerReview_ReviewType = 1
	SellerReview_NEUTRAL  SellerReview_ReviewType = 2
	SellerReview_NEGATIVE SellerReview_ReviewType = 3
)

var SellerReview_ReviewType_name = map[int32]string{
	0: "UNKNOWN",
	1: "POSITIVE",
	2: "NEUTRAL",
	3: "NEGATIVE",
}

var SellerReview_ReviewType_value = map[string]int32{
	"UNKNOWN":  0,
	"POSITIVE": 1,
	"NEUTRAL":  2,
	"NEGATIVE": 3,
}

func (x SellerReview_ReviewType) String() string {
	return proto.EnumName(SellerReview_ReviewType_name, int32(x))
}

func (SellerReview_ReviewType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{6, 0}
}

type ExternalAd_ExternalAdType int32

const (
	ExternalAd_EXTERNAL_10 ExternalAd_ExternalAdType = 0
	ExternalAd_EXTERNAL_20 ExternalAd_ExternalAdType = 1
)

var ExternalAd_ExternalAdType_name = map[int32]string{
	0: "EXTERNAL_10",
	1: "EXTERNAL_20",
}

var ExternalAd_ExternalAdType_value = map[string]int32{
	"EXTERNAL_10": 0,
	"EXTERNAL_20": 1,
}

func (x ExternalAd_ExternalAdType) String() string {
	return proto.EnumName(ExternalAd_ExternalAdType_name, int32(x))
}

func (ExternalAd_ExternalAdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{9, 0}
}

type ExternalVidAd_ExternalVidAdType int32

const (
	ExternalVidAd_UNKNOWN         ExternalVidAd_ExternalVidAdType = 0
	ExternalVidAd_EXTERNAL_VID_20 ExternalVidAd_ExternalVidAdType = 1
)

var ExternalVidAd_ExternalVidAdType_name = map[int32]string{
	0: "UNKNOWN",
	1: "EXTERNAL_VID_20",
}

var ExternalVidAd_ExternalVidAdType_value = map[string]int32{
	"UNKNOWN":         0,
	"EXTERNAL_VID_20": 1,
}

func (x ExternalVidAd_ExternalVidAdType) String() string {
	return proto.EnumName(ExternalVidAd_ExternalVidAdType_name, int32(x))
}

func (ExternalVidAd_ExternalVidAdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{11, 0}
}

type AdsRequestOption struct {
	//In order to identify unique users, Google created ‘GAID’ (Google Advertising ID), and Apple created ‘IDFA’ (Identifier For Advertising).
	AdvertisingId string `protobuf:"bytes,1,opt,name=advertising_id,json=advertisingId,proto3" json:"advertising_id,omitempty"`
	//if in the OS settings the user has enabled the limit ad tracking, then the OS will return true to us when we call to retrieve that info from `AdvertisingIdentifier`
	AdDoNotTrack         bool      `protobuf:"varint,2,opt,name=ad_do_not_track,json=adDoNotTrack,proto3" json:"ad_do_not_track,omitempty"`
	AdVersion            AdVersion `protobuf:"varint,3,opt,name=ad_version,json=adVersion,proto3,enum=ContentFeedService_proto.AdVersion" json:"ad_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AdsRequestOption) Reset()         { *m = AdsRequestOption{} }
func (m *AdsRequestOption) String() string { return proto.CompactTextString(m) }
func (*AdsRequestOption) ProtoMessage()    {}
func (*AdsRequestOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{0}
}

func (m *AdsRequestOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdsRequestOption.Unmarshal(m, b)
}
func (m *AdsRequestOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdsRequestOption.Marshal(b, m, deterministic)
}
func (m *AdsRequestOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdsRequestOption.Merge(m, src)
}
func (m *AdsRequestOption) XXX_Size() int {
	return xxx_messageInfo_AdsRequestOption.Size(m)
}
func (m *AdsRequestOption) XXX_DiscardUnknown() {
	xxx_messageInfo_AdsRequestOption.DiscardUnknown(m)
}

var xxx_messageInfo_AdsRequestOption proto.InternalMessageInfo

func (m *AdsRequestOption) GetAdvertisingId() string {
	if m != nil {
		return m.AdvertisingId
	}
	return ""
}

func (m *AdsRequestOption) GetAdDoNotTrack() bool {
	if m != nil {
		return m.AdDoNotTrack
	}
	return false
}

func (m *AdsRequestOption) GetAdVersion() AdVersion {
	if m != nil {
		return m.AdVersion
	}
	return AdVersion_DEFAULT_AD_VERSION
}

type DedicatedSpotlightSection struct {
	PromotedListingCards []*PromotedListingCard `protobuf:"bytes,1,rep,name=promoted_listing_cards,json=promotedListingCards,proto3" json:"promoted_listing_cards,omitempty"`
	SectionTitle         string                 `protobuf:"bytes,2,opt,name=section_title,json=sectionTitle,proto3" json:"section_title,omitempty"`
	SectionPosition      int32                  `protobuf:"varint,3,opt,name=section_position,json=sectionPosition,proto3" json:"section_position,omitempty"`
	SectionSubTitle      string                 `protobuf:"bytes,4,opt,name=section_sub_title,json=sectionSubTitle,proto3" json:"section_sub_title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DedicatedSpotlightSection) Reset()         { *m = DedicatedSpotlightSection{} }
func (m *DedicatedSpotlightSection) String() string { return proto.CompactTextString(m) }
func (*DedicatedSpotlightSection) ProtoMessage()    {}
func (*DedicatedSpotlightSection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{1}
}

func (m *DedicatedSpotlightSection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DedicatedSpotlightSection.Unmarshal(m, b)
}
func (m *DedicatedSpotlightSection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DedicatedSpotlightSection.Marshal(b, m, deterministic)
}
func (m *DedicatedSpotlightSection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DedicatedSpotlightSection.Merge(m, src)
}
func (m *DedicatedSpotlightSection) XXX_Size() int {
	return xxx_messageInfo_DedicatedSpotlightSection.Size(m)
}
func (m *DedicatedSpotlightSection) XXX_DiscardUnknown() {
	xxx_messageInfo_DedicatedSpotlightSection.DiscardUnknown(m)
}

var xxx_messageInfo_DedicatedSpotlightSection proto.InternalMessageInfo

func (m *DedicatedSpotlightSection) GetPromotedListingCards() []*PromotedListingCard {
	if m != nil {
		return m.PromotedListingCards
	}
	return nil
}

func (m *DedicatedSpotlightSection) GetSectionTitle() string {
	if m != nil {
		return m.SectionTitle
	}
	return ""
}

func (m *DedicatedSpotlightSection) GetSectionPosition() int32 {
	if m != nil {
		return m.SectionPosition
	}
	return 0
}

func (m *DedicatedSpotlightSection) GetSectionSubTitle() string {
	if m != nil {
		return m.SectionSubTitle
	}
	return ""
}

type PromotedListingCard struct {
	TrackingData         *TrackingData                      `protobuf:"bytes,1,opt,name=tracking_data,json=trackingData,proto3" json:"tracking_data,omitempty"`
	ListingCard          *ListingCard                       `protobuf:"bytes,2,opt,name=listing_card,json=listingCard,proto3" json:"listing_card,omitempty"`
	AdType               PromotedListingCard_PromotedAdType `protobuf:"varint,3,opt,name=ad_type,json=adType,proto3,enum=ContentFeedService_proto.PromotedListingCard_PromotedAdType" json:"ad_type,omitempty"`
	PromotionTag         string                             `protobuf:"bytes,4,opt,name=promotion_tag,json=promotionTag,proto3" json:"promotion_tag,omitempty"`
	Context              string                             `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	PromotionId          string                             `protobuf:"bytes,6,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *PromotedListingCard) Reset()         { *m = PromotedListingCard{} }
func (m *PromotedListingCard) String() string { return proto.CompactTextString(m) }
func (*PromotedListingCard) ProtoMessage()    {}
func (*PromotedListingCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{2}
}

func (m *PromotedListingCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromotedListingCard.Unmarshal(m, b)
}
func (m *PromotedListingCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromotedListingCard.Marshal(b, m, deterministic)
}
func (m *PromotedListingCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromotedListingCard.Merge(m, src)
}
func (m *PromotedListingCard) XXX_Size() int {
	return xxx_messageInfo_PromotedListingCard.Size(m)
}
func (m *PromotedListingCard) XXX_DiscardUnknown() {
	xxx_messageInfo_PromotedListingCard.DiscardUnknown(m)
}

var xxx_messageInfo_PromotedListingCard proto.InternalMessageInfo

func (m *PromotedListingCard) GetTrackingData() *TrackingData {
	if m != nil {
		return m.TrackingData
	}
	return nil
}

func (m *PromotedListingCard) GetListingCard() *ListingCard {
	if m != nil {
		return m.ListingCard
	}
	return nil
}

func (m *PromotedListingCard) GetAdType() PromotedListingCard_PromotedAdType {
	if m != nil {
		return m.AdType
	}
	return PromotedListingCard_PROMOTED_10
}

func (m *PromotedListingCard) GetPromotionTag() string {
	if m != nil {
		return m.PromotionTag
	}
	return ""
}

func (m *PromotedListingCard) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *PromotedListingCard) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

type ProfilePromotionCard struct {
	TrackingData         *TrackingData  `protobuf:"bytes,1,opt,name=tracking_data,json=trackingData,proto3" json:"tracking_data,omitempty"`
	SellerData           *SellerProfile `protobuf:"bytes,2,opt,name=seller_data,json=sellerData,proto3" json:"seller_data,omitempty"`
	ListingThumbnailUrls []*Photo       `protobuf:"bytes,3,rep,name=listing_thumbnail_urls,json=listingThumbnailUrls,proto3" json:"listing_thumbnail_urls,omitempty"`
	PromotionTag         string         `protobuf:"bytes,4,opt,name=promotion_tag,json=promotionTag,proto3" json:"promotion_tag,omitempty"`
	Context              string         `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	PromotionId          string         `protobuf:"bytes,6,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProfilePromotionCard) Reset()         { *m = ProfilePromotionCard{} }
func (m *ProfilePromotionCard) String() string { return proto.CompactTextString(m) }
func (*ProfilePromotionCard) ProtoMessage()    {}
func (*ProfilePromotionCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{3}
}

func (m *ProfilePromotionCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePromotionCard.Unmarshal(m, b)
}
func (m *ProfilePromotionCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePromotionCard.Marshal(b, m, deterministic)
}
func (m *ProfilePromotionCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePromotionCard.Merge(m, src)
}
func (m *ProfilePromotionCard) XXX_Size() int {
	return xxx_messageInfo_ProfilePromotionCard.Size(m)
}
func (m *ProfilePromotionCard) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePromotionCard.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePromotionCard proto.InternalMessageInfo

func (m *ProfilePromotionCard) GetTrackingData() *TrackingData {
	if m != nil {
		return m.TrackingData
	}
	return nil
}

func (m *ProfilePromotionCard) GetSellerData() *SellerProfile {
	if m != nil {
		return m.SellerData
	}
	return nil
}

func (m *ProfilePromotionCard) GetListingThumbnailUrls() []*Photo {
	if m != nil {
		return m.ListingThumbnailUrls
	}
	return nil
}

func (m *ProfilePromotionCard) GetPromotionTag() string {
	if m != nil {
		return m.PromotionTag
	}
	return ""
}

func (m *ProfilePromotionCard) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *ProfilePromotionCard) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

type SellerProfile struct {
	Id                      string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username                string          `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Description             string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProfilePicture          *Photo          `protobuf:"bytes,4,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	AdditionalListingsCount int32           `protobuf:"varint,5,opt,name=additional_listings_count,json=additionalListingsCount,proto3" json:"additional_listings_count,omitempty"`
	Review                  *SellerReview   `protobuf:"bytes,6,opt,name=review,proto3" json:"review,omitempty"`
	Feedback                *SellerFeedback `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}        `json:"-"`
	XXX_unrecognized        []byte          `json:"-"`
	XXX_sizecache           int32           `json:"-"`
}

func (m *SellerProfile) Reset()         { *m = SellerProfile{} }
func (m *SellerProfile) String() string { return proto.CompactTextString(m) }
func (*SellerProfile) ProtoMessage()    {}
func (*SellerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{4}
}

func (m *SellerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellerProfile.Unmarshal(m, b)
}
func (m *SellerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellerProfile.Marshal(b, m, deterministic)
}
func (m *SellerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellerProfile.Merge(m, src)
}
func (m *SellerProfile) XXX_Size() int {
	return xxx_messageInfo_SellerProfile.Size(m)
}
func (m *SellerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_SellerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_SellerProfile proto.InternalMessageInfo

func (m *SellerProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SellerProfile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SellerProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SellerProfile) GetProfilePicture() *Photo {
	if m != nil {
		return m.ProfilePicture
	}
	return nil
}

func (m *SellerProfile) GetAdditionalListingsCount() int32 {
	if m != nil {
		return m.AdditionalListingsCount
	}
	return 0
}

func (m *SellerProfile) GetReview() *SellerReview {
	if m != nil {
		return m.Review
	}
	return nil
}

func (m *SellerProfile) GetFeedback() *SellerFeedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type Photo struct {
	ThumbnailUrl                    string   `protobuf:"bytes,1,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ThumbnailProgressiveUrl         string   `protobuf:"bytes,2,opt,name=thumbnail_progressive_url,json=thumbnailProgressiveUrl,proto3" json:"thumbnail_progressive_url,omitempty"`
	ThumbnailProgressiveLowRange    int32    `protobuf:"varint,3,opt,name=thumbnail_progressive_low_range,json=thumbnailProgressiveLowRange,proto3" json:"thumbnail_progressive_low_range,omitempty"`
	ThumbnailProgressiveMediumRange int32    `protobuf:"varint,4,opt,name=thumbnail_progressive_medium_range,json=thumbnailProgressiveMediumRange,proto3" json:"thumbnail_progressive_medium_range,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{5}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Photo) GetThumbnailProgressiveUrl() string {
	if m != nil {
		return m.ThumbnailProgressiveUrl
	}
	return ""
}

func (m *Photo) GetThumbnailProgressiveLowRange() int32 {
	if m != nil {
		return m.ThumbnailProgressiveLowRange
	}
	return 0
}

func (m *Photo) GetThumbnailProgressiveMediumRange() int32 {
	if m != nil {
		return m.ThumbnailProgressiveMediumRange
	}
	return 0
}

type SellerReview struct {
	Reviews              []*SellerReview_Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SellerReview) Reset()         { *m = SellerReview{} }
func (m *SellerReview) String() string { return proto.CompactTextString(m) }
func (*SellerReview) ProtoMessage()    {}
func (*SellerReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{6}
}

func (m *SellerReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellerReview.Unmarshal(m, b)
}
func (m *SellerReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellerReview.Marshal(b, m, deterministic)
}
func (m *SellerReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellerReview.Merge(m, src)
}
func (m *SellerReview) XXX_Size() int {
	return xxx_messageInfo_SellerReview.Size(m)
}
func (m *SellerReview) XXX_DiscardUnknown() {
	xxx_messageInfo_SellerReview.DiscardUnknown(m)
}

var xxx_messageInfo_SellerReview proto.InternalMessageInfo

func (m *SellerReview) GetReviews() []*SellerReview_Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

type SellerReview_Review struct {
	Type                 SellerReview_ReviewType `protobuf:"varint,1,opt,name=type,proto3,enum=ContentFeedService_proto.SellerReview_ReviewType" json:"type,omitempty"`
	Count                int32                   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SellerReview_Review) Reset()         { *m = SellerReview_Review{} }
func (m *SellerReview_Review) String() string { return proto.CompactTextString(m) }
func (*SellerReview_Review) ProtoMessage()    {}
func (*SellerReview_Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{6, 0}
}

func (m *SellerReview_Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellerReview_Review.Unmarshal(m, b)
}
func (m *SellerReview_Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellerReview_Review.Marshal(b, m, deterministic)
}
func (m *SellerReview_Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellerReview_Review.Merge(m, src)
}
func (m *SellerReview_Review) XXX_Size() int {
	return xxx_messageInfo_SellerReview_Review.Size(m)
}
func (m *SellerReview_Review) XXX_DiscardUnknown() {
	xxx_messageInfo_SellerReview_Review.DiscardUnknown(m)
}

var xxx_messageInfo_SellerReview_Review proto.InternalMessageInfo

func (m *SellerReview_Review) GetType() SellerReview_ReviewType {
	if m != nil {
		return m.Type
	}
	return SellerReview_UNKNOWN
}

func (m *SellerReview_Review) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SellerFeedback struct {
	Score                float32  `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellerFeedback) Reset()         { *m = SellerFeedback{} }
func (m *SellerFeedback) String() string { return proto.CompactTextString(m) }
func (*SellerFeedback) ProtoMessage()    {}
func (*SellerFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{7}
}

func (m *SellerFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellerFeedback.Unmarshal(m, b)
}
func (m *SellerFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellerFeedback.Marshal(b, m, deterministic)
}
func (m *SellerFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellerFeedback.Merge(m, src)
}
func (m *SellerFeedback) XXX_Size() int {
	return xxx_messageInfo_SellerFeedback.Size(m)
}
func (m *SellerFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_SellerFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_SellerFeedback proto.InternalMessageInfo

func (m *SellerFeedback) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type ShoutoutPromotionCard struct {
	TrackingData *TrackingData  `protobuf:"bytes,1,opt,name=tracking_data,json=trackingData,proto3" json:"tracking_data,omitempty"`
	SellerData   *SellerProfile `protobuf:"bytes,2,opt,name=seller_data,json=sellerData,proto3" json:"seller_data,omitempty"`
	PromotionId  string         `protobuf:"bytes,4,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	// if the user seeing the shoutout is following the seller, this will be true, else false
	IsUserFollowing bool   `protobuf:"varint,5,opt,name=is_user_following,json=isUserFollowing,proto3" json:"is_user_following,omitempty"`
	Caption         string `protobuf:"bytes,6,opt,name=caption,proto3" json:"caption,omitempty"`
	// Types that are valid to be assigned to ShoutoutType:
	//	*ShoutoutPromotionCard_ShoutoutTypeProfile_
	//	*ShoutoutPromotionCard_ShoutoutTypeCollection_
	ShoutoutType         isShoutoutPromotionCard_ShoutoutType `protobuf_oneof:"shoutoutType"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ShoutoutPromotionCard) Reset()         { *m = ShoutoutPromotionCard{} }
func (m *ShoutoutPromotionCard) String() string { return proto.CompactTextString(m) }
func (*ShoutoutPromotionCard) ProtoMessage()    {}
func (*ShoutoutPromotionCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{8}
}

func (m *ShoutoutPromotionCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShoutoutPromotionCard.Unmarshal(m, b)
}
func (m *ShoutoutPromotionCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShoutoutPromotionCard.Marshal(b, m, deterministic)
}
func (m *ShoutoutPromotionCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShoutoutPromotionCard.Merge(m, src)
}
func (m *ShoutoutPromotionCard) XXX_Size() int {
	return xxx_messageInfo_ShoutoutPromotionCard.Size(m)
}
func (m *ShoutoutPromotionCard) XXX_DiscardUnknown() {
	xxx_messageInfo_ShoutoutPromotionCard.DiscardUnknown(m)
}

var xxx_messageInfo_ShoutoutPromotionCard proto.InternalMessageInfo

func (m *ShoutoutPromotionCard) GetTrackingData() *TrackingData {
	if m != nil {
		return m.TrackingData
	}
	return nil
}

func (m *ShoutoutPromotionCard) GetSellerData() *SellerProfile {
	if m != nil {
		return m.SellerData
	}
	return nil
}

func (m *ShoutoutPromotionCard) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

func (m *ShoutoutPromotionCard) GetIsUserFollowing() bool {
	if m != nil {
		return m.IsUserFollowing
	}
	return false
}

func (m *ShoutoutPromotionCard) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type isShoutoutPromotionCard_ShoutoutType interface {
	isShoutoutPromotionCard_ShoutoutType()
}

type ShoutoutPromotionCard_ShoutoutTypeProfile_ struct {
	ShoutoutTypeProfile *ShoutoutPromotionCard_ShoutoutTypeProfile `protobuf:"bytes,7,opt,name=shoutout_type_profile,json=shoutoutTypeProfile,proto3,oneof"`
}

type ShoutoutPromotionCard_ShoutoutTypeCollection_ struct {
	ShoutoutTypeCollection *ShoutoutPromotionCard_ShoutoutTypeCollection `protobuf:"bytes,8,opt,name=shoutout_type_collection,json=shoutoutTypeCollection,proto3,oneof"`
}

func (*ShoutoutPromotionCard_ShoutoutTypeProfile_) isShoutoutPromotionCard_ShoutoutType() {}

func (*ShoutoutPromotionCard_ShoutoutTypeCollection_) isShoutoutPromotionCard_ShoutoutType() {}

func (m *ShoutoutPromotionCard) GetShoutoutType() isShoutoutPromotionCard_ShoutoutType {
	if m != nil {
		return m.ShoutoutType
	}
	return nil
}

func (m *ShoutoutPromotionCard) GetShoutoutTypeProfile() *ShoutoutPromotionCard_ShoutoutTypeProfile {
	if x, ok := m.GetShoutoutType().(*ShoutoutPromotionCard_ShoutoutTypeProfile_); ok {
		return x.ShoutoutTypeProfile
	}
	return nil
}

func (m *ShoutoutPromotionCard) GetShoutoutTypeCollection() *ShoutoutPromotionCard_ShoutoutTypeCollection {
	if x, ok := m.GetShoutoutType().(*ShoutoutPromotionCard_ShoutoutTypeCollection_); ok {
		return x.ShoutoutTypeCollection
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ShoutoutPromotionCard) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ShoutoutPromotionCard_ShoutoutTypeProfile_)(nil),
		(*ShoutoutPromotionCard_ShoutoutTypeCollection_)(nil),
	}
}

type ShoutoutPromotionCard_ShoutoutTypeProfile struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListingThumbnailUrls []*Photo `protobuf:"bytes,2,rep,name=listing_thumbnail_urls,json=listingThumbnailUrls,proto3" json:"listing_thumbnail_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) Reset() {
	*m = ShoutoutPromotionCard_ShoutoutTypeProfile{}
}
func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) String() string { return proto.CompactTextString(m) }
func (*ShoutoutPromotionCard_ShoutoutTypeProfile) ProtoMessage()    {}
func (*ShoutoutPromotionCard_ShoutoutTypeProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{8, 0}
}

func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeProfile.Unmarshal(m, b)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeProfile.Marshal(b, m, deterministic)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeProfile.Merge(m, src)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) XXX_Size() int {
	return xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeProfile.Size(m)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeProfile proto.InternalMessageInfo

func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ShoutoutPromotionCard_ShoutoutTypeProfile) GetListingThumbnailUrls() []*Photo {
	if m != nil {
		return m.ListingThumbnailUrls
	}
	return nil
}

type ShoutoutPromotionCard_ShoutoutTypeCollection struct {
	CollectionId         string   `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	ListingThumbnailUrls []*Photo `protobuf:"bytes,2,rep,name=listing_thumbnail_urls,json=listingThumbnailUrls,proto3" json:"listing_thumbnail_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) Reset() {
	*m = ShoutoutPromotionCard_ShoutoutTypeCollection{}
}
func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) String() string {
	return proto.CompactTextString(m)
}
func (*ShoutoutPromotionCard_ShoutoutTypeCollection) ProtoMessage() {}
func (*ShoutoutPromotionCard_ShoutoutTypeCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{8, 1}
}

func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeCollection.Unmarshal(m, b)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeCollection.Marshal(b, m, deterministic)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeCollection.Merge(m, src)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) XXX_Size() int {
	return xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeCollection.Size(m)
}
func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeCollection.DiscardUnknown(m)
}

var xxx_messageInfo_ShoutoutPromotionCard_ShoutoutTypeCollection proto.InternalMessageInfo

func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

func (m *ShoutoutPromotionCard_ShoutoutTypeCollection) GetListingThumbnailUrls() []*Photo {
	if m != nil {
		return m.ListingThumbnailUrls
	}
	return nil
}

type ExternalAd struct {
	TrackingData         *TrackingData             `protobuf:"bytes,1,opt,name=tracking_data,json=trackingData,proto3" json:"tracking_data,omitempty"`
	ExternalAdData       *ExternalAdData           `protobuf:"bytes,2,opt,name=external_ad_data,json=externalAdData,proto3" json:"external_ad_data,omitempty"`
	AdType               ExternalAd_ExternalAdType `protobuf:"varint,3,opt,name=ad_type,json=adType,proto3,enum=ContentFeedService_proto.ExternalAd_ExternalAdType" json:"ad_type,omitempty"`
	PromotionId          string                    `protobuf:"bytes,4,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExternalAd) Reset()         { *m = ExternalAd{} }
func (m *ExternalAd) String() string { return proto.CompactTextString(m) }
func (*ExternalAd) ProtoMessage()    {}
func (*ExternalAd) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{9}
}

func (m *ExternalAd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalAd.Unmarshal(m, b)
}
func (m *ExternalAd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalAd.Marshal(b, m, deterministic)
}
func (m *ExternalAd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalAd.Merge(m, src)
}
func (m *ExternalAd) XXX_Size() int {
	return xxx_messageInfo_ExternalAd.Size(m)
}
func (m *ExternalAd) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalAd.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalAd proto.InternalMessageInfo

func (m *ExternalAd) GetTrackingData() *TrackingData {
	if m != nil {
		return m.TrackingData
	}
	return nil
}

func (m *ExternalAd) GetExternalAdData() *ExternalAdData {
	if m != nil {
		return m.ExternalAdData
	}
	return nil
}

func (m *ExternalAd) GetAdType() ExternalAd_ExternalAdType {
	if m != nil {
		return m.AdType
	}
	return ExternalAd_EXTERNAL_10
}

func (m *ExternalAd) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

type ExternalAdData struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PrimaryPhotoUrl      string   `protobuf:"bytes,3,opt,name=primary_photo_url,json=primaryPhotoUrl,proto3" json:"primary_photo_url,omitempty"`
	LandingUrl           string   `protobuf:"bytes,4,opt,name=landing_url,json=landingUrl,proto3" json:"landing_url,omitempty"`
	BackgroundColor      string   `protobuf:"bytes,5,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	PromotedBy           string   `protobuf:"bytes,6,opt,name=promoted_by,json=promotedBy,proto3" json:"promoted_by,omitempty"`
	PromotedByTag        string   `protobuf:"bytes,7,opt,name=promoted_by_tag,json=promotedByTag,proto3" json:"promoted_by_tag,omitempty"`
	PromotedByUrl        string   `protobuf:"bytes,8,opt,name=promoted_by_url,json=promotedByUrl,proto3" json:"promoted_by_url,omitempty"`
	CtaTitle             string   `protobuf:"bytes,9,opt,name=cta_title,json=ctaTitle,proto3" json:"cta_title,omitempty"`
	BrandImageUrl        string   `protobuf:"bytes,10,opt,name=brand_image_url,json=brandImageUrl,proto3" json:"brand_image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalAdData) Reset()         { *m = ExternalAdData{} }
func (m *ExternalAdData) String() string { return proto.CompactTextString(m) }
func (*ExternalAdData) ProtoMessage()    {}
func (*ExternalAdData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{10}
}

func (m *ExternalAdData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalAdData.Unmarshal(m, b)
}
func (m *ExternalAdData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalAdData.Marshal(b, m, deterministic)
}
func (m *ExternalAdData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalAdData.Merge(m, src)
}
func (m *ExternalAdData) XXX_Size() int {
	return xxx_messageInfo_ExternalAdData.Size(m)
}
func (m *ExternalAdData) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalAdData.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalAdData proto.InternalMessageInfo

func (m *ExternalAdData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ExternalAdData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ExternalAdData) GetPrimaryPhotoUrl() string {
	if m != nil {
		return m.PrimaryPhotoUrl
	}
	return ""
}

func (m *ExternalAdData) GetLandingUrl() string {
	if m != nil {
		return m.LandingUrl
	}
	return ""
}

func (m *ExternalAdData) GetBackgroundColor() string {
	if m != nil {
		return m.BackgroundColor
	}
	return ""
}

func (m *ExternalAdData) GetPromotedBy() string {
	if m != nil {
		return m.PromotedBy
	}
	return ""
}

func (m *ExternalAdData) GetPromotedByTag() string {
	if m != nil {
		return m.PromotedByTag
	}
	return ""
}

func (m *ExternalAdData) GetPromotedByUrl() string {
	if m != nil {
		return m.PromotedByUrl
	}
	return ""
}

func (m *ExternalAdData) GetCtaTitle() string {
	if m != nil {
		return m.CtaTitle
	}
	return ""
}

func (m *ExternalAdData) GetBrandImageUrl() string {
	if m != nil {
		return m.BrandImageUrl
	}
	return ""
}

type ExternalVidAd struct {
	TrackingData         *TrackingData                   `protobuf:"bytes,1,opt,name=tracking_data,json=trackingData,proto3" json:"tracking_data,omitempty"`
	ExternalVidAdData    *ExternalVidAdData              `protobuf:"bytes,2,opt,name=external_vid_ad_data,json=externalVidAdData,proto3" json:"external_vid_ad_data,omitempty"`
	AdType               ExternalVidAd_ExternalVidAdType `protobuf:"varint,3,opt,name=ad_type,json=adType,proto3,enum=ContentFeedService_proto.ExternalVidAd_ExternalVidAdType" json:"ad_type,omitempty"`
	PromotionId          string                          `protobuf:"bytes,4,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ExternalVidAd) Reset()         { *m = ExternalVidAd{} }
func (m *ExternalVidAd) String() string { return proto.CompactTextString(m) }
func (*ExternalVidAd) ProtoMessage()    {}
func (*ExternalVidAd) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{11}
}

func (m *ExternalVidAd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalVidAd.Unmarshal(m, b)
}
func (m *ExternalVidAd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalVidAd.Marshal(b, m, deterministic)
}
func (m *ExternalVidAd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalVidAd.Merge(m, src)
}
func (m *ExternalVidAd) XXX_Size() int {
	return xxx_messageInfo_ExternalVidAd.Size(m)
}
func (m *ExternalVidAd) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalVidAd.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalVidAd proto.InternalMessageInfo

func (m *ExternalVidAd) GetTrackingData() *TrackingData {
	if m != nil {
		return m.TrackingData
	}
	return nil
}

func (m *ExternalVidAd) GetExternalVidAdData() *ExternalVidAdData {
	if m != nil {
		return m.ExternalVidAdData
	}
	return nil
}

func (m *ExternalVidAd) GetAdType() ExternalVidAd_ExternalVidAdType {
	if m != nil {
		return m.AdType
	}
	return ExternalVidAd_UNKNOWN
}

func (m *ExternalVidAd) GetPromotionId() string {
	if m != nil {
		return m.PromotionId
	}
	return ""
}

type ExternalVidAdData struct {
	Title                string       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PromotedBy           string       `protobuf:"bytes,3,opt,name=promoted_by,json=promotedBy,proto3" json:"promoted_by,omitempty"`
	PromotedByTag        string       `protobuf:"bytes,4,opt,name=promoted_by_tag,json=promotedByTag,proto3" json:"promoted_by_tag,omitempty"`
	CtaTitle             string       `protobuf:"bytes,5,opt,name=cta_title,json=ctaTitle,proto3" json:"cta_title,omitempty"`
	BrandImageUrl        string       `protobuf:"bytes,6,opt,name=brand_image_url,json=brandImageUrl,proto3" json:"brand_image_url,omitempty"`
	LandingUrl           string       `protobuf:"bytes,7,opt,name=landing_url,json=landingUrl,proto3" json:"landing_url,omitempty"`
	VideoData            *Media_Video `protobuf:"bytes,8,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExternalVidAdData) Reset()         { *m = ExternalVidAdData{} }
func (m *ExternalVidAdData) String() string { return proto.CompactTextString(m) }
func (*ExternalVidAdData) ProtoMessage()    {}
func (*ExternalVidAdData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{12}
}

func (m *ExternalVidAdData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalVidAdData.Unmarshal(m, b)
}
func (m *ExternalVidAdData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalVidAdData.Marshal(b, m, deterministic)
}
func (m *ExternalVidAdData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalVidAdData.Merge(m, src)
}
func (m *ExternalVidAdData) XXX_Size() int {
	return xxx_messageInfo_ExternalVidAdData.Size(m)
}
func (m *ExternalVidAdData) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalVidAdData.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalVidAdData proto.InternalMessageInfo

func (m *ExternalVidAdData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ExternalVidAdData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ExternalVidAdData) GetPromotedBy() string {
	if m != nil {
		return m.PromotedBy
	}
	return ""
}

func (m *ExternalVidAdData) GetPromotedByTag() string {
	if m != nil {
		return m.PromotedByTag
	}
	return ""
}

func (m *ExternalVidAdData) GetCtaTitle() string {
	if m != nil {
		return m.CtaTitle
	}
	return ""
}

func (m *ExternalVidAdData) GetBrandImageUrl() string {
	if m != nil {
		return m.BrandImageUrl
	}
	return ""
}

func (m *ExternalVidAdData) GetLandingUrl() string {
	if m != nil {
		return m.LandingUrl
	}
	return ""
}

func (m *ExternalVidAdData) GetVideoData() *Media_Video {
	if m != nil {
		return m.VideoData
	}
	return nil
}

type TrackingData struct {
	TrackingUrls         *TrackingData_TrackingUrls `protobuf:"bytes,1,opt,name=tracking_urls,json=trackingUrls,proto3" json:"tracking_urls,omitempty"`
	TrackingTag          string                     `protobuf:"bytes,2,opt,name=tracking_tag,json=trackingTag,proto3" json:"tracking_tag,omitempty"`
	ViewableTag          string                     `protobuf:"bytes,3,opt,name=viewable_tag,json=viewableTag,proto3" json:"viewable_tag,omitempty"`
	Zid                  string                     `protobuf:"bytes,4,opt,name=zid,proto3" json:"zid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TrackingData) Reset()         { *m = TrackingData{} }
func (m *TrackingData) String() string { return proto.CompactTextString(m) }
func (*TrackingData) ProtoMessage()    {}
func (*TrackingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{13}
}

func (m *TrackingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackingData.Unmarshal(m, b)
}
func (m *TrackingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackingData.Marshal(b, m, deterministic)
}
func (m *TrackingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackingData.Merge(m, src)
}
func (m *TrackingData) XXX_Size() int {
	return xxx_messageInfo_TrackingData.Size(m)
}
func (m *TrackingData) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackingData.DiscardUnknown(m)
}

var xxx_messageInfo_TrackingData proto.InternalMessageInfo

func (m *TrackingData) GetTrackingUrls() *TrackingData_TrackingUrls {
	if m != nil {
		return m.TrackingUrls
	}
	return nil
}

func (m *TrackingData) GetTrackingTag() string {
	if m != nil {
		return m.TrackingTag
	}
	return ""
}

func (m *TrackingData) GetViewableTag() string {
	if m != nil {
		return m.ViewableTag
	}
	return ""
}

func (m *TrackingData) GetZid() string {
	if m != nil {
		return m.Zid
	}
	return ""
}

type TrackingData_TrackingUrls struct {
	Impressions          []string                 `protobuf:"bytes,1,rep,name=impressions,proto3" json:"impressions,omitempty"`
	Viewables            []string                 `protobuf:"bytes,2,rep,name=viewables,proto3" json:"viewables,omitempty"`
	Clicks               []string                 `protobuf:"bytes,3,rep,name=clicks,proto3" json:"clicks,omitempty"`
	Action               *TrackingData_ActionType `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Follows              []string                 `protobuf:"bytes,5,rep,name=follows,proto3" json:"follows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TrackingData_TrackingUrls) Reset()         { *m = TrackingData_TrackingUrls{} }
func (m *TrackingData_TrackingUrls) String() string { return proto.CompactTextString(m) }
func (*TrackingData_TrackingUrls) ProtoMessage()    {}
func (*TrackingData_TrackingUrls) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{13, 0}
}

func (m *TrackingData_TrackingUrls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackingData_TrackingUrls.Unmarshal(m, b)
}
func (m *TrackingData_TrackingUrls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackingData_TrackingUrls.Marshal(b, m, deterministic)
}
func (m *TrackingData_TrackingUrls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackingData_TrackingUrls.Merge(m, src)
}
func (m *TrackingData_TrackingUrls) XXX_Size() int {
	return xxx_messageInfo_TrackingData_TrackingUrls.Size(m)
}
func (m *TrackingData_TrackingUrls) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackingData_TrackingUrls.DiscardUnknown(m)
}

var xxx_messageInfo_TrackingData_TrackingUrls proto.InternalMessageInfo

func (m *TrackingData_TrackingUrls) GetImpressions() []string {
	if m != nil {
		return m.Impressions
	}
	return nil
}

func (m *TrackingData_TrackingUrls) GetViewables() []string {
	if m != nil {
		return m.Viewables
	}
	return nil
}

func (m *TrackingData_TrackingUrls) GetClicks() []string {
	if m != nil {
		return m.Clicks
	}
	return nil
}

func (m *TrackingData_TrackingUrls) GetAction() *TrackingData_ActionType {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *TrackingData_TrackingUrls) GetFollows() []string {
	if m != nil {
		return m.Follows
	}
	return nil
}

type TrackingData_ActionType struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Like                 string   `protobuf:"bytes,2,opt,name=like,proto3" json:"like,omitempty"`
	Chat                 string   `protobuf:"bytes,3,opt,name=chat,proto3" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackingData_ActionType) Reset()         { *m = TrackingData_ActionType{} }
func (m *TrackingData_ActionType) String() string { return proto.CompactTextString(m) }
func (*TrackingData_ActionType) ProtoMessage()    {}
func (*TrackingData_ActionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_dee4e141de1d75c6, []int{13, 1}
}

func (m *TrackingData_ActionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackingData_ActionType.Unmarshal(m, b)
}
func (m *TrackingData_ActionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackingData_ActionType.Marshal(b, m, deterministic)
}
func (m *TrackingData_ActionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackingData_ActionType.Merge(m, src)
}
func (m *TrackingData_ActionType) XXX_Size() int {
	return xxx_messageInfo_TrackingData_ActionType.Size(m)
}
func (m *TrackingData_ActionType) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackingData_ActionType.DiscardUnknown(m)
}

var xxx_messageInfo_TrackingData_ActionType proto.InternalMessageInfo

func (m *TrackingData_ActionType) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *TrackingData_ActionType) GetLike() string {
	if m != nil {
		return m.Like
	}
	return ""
}

func (m *TrackingData_ActionType) GetChat() string {
	if m != nil {
		return m.Chat
	}
	return ""
}

func init() {
	proto.RegisterEnum("ContentFeedService_proto.AdVersion", AdVersion_name, AdVersion_value)
	proto.RegisterEnum("ContentFeedService_proto.PromotedListingCard_PromotedAdType", PromotedListingCard_PromotedAdType_name, PromotedListingCard_PromotedAdType_value)
	proto.RegisterEnum("ContentFeedService_proto.SellerReview_ReviewType", SellerReview_ReviewType_name, SellerReview_ReviewType_value)
	proto.RegisterEnum("ContentFeedService_proto.ExternalAd_ExternalAdType", ExternalAd_ExternalAdType_name, ExternalAd_ExternalAdType_value)
	proto.RegisterEnum("ContentFeedService_proto.ExternalVidAd_ExternalVidAdType", ExternalVidAd_ExternalVidAdType_name, ExternalVidAd_ExternalVidAdType_value)
	proto.RegisterType((*AdsRequestOption)(nil), "ContentFeedService_proto.AdsRequestOption")
	proto.RegisterType((*DedicatedSpotlightSection)(nil), "ContentFeedService_proto.DedicatedSpotlightSection")
	proto.RegisterType((*PromotedListingCard)(nil), "ContentFeedService_proto.PromotedListingCard")
	proto.RegisterType((*ProfilePromotionCard)(nil), "ContentFeedService_proto.ProfilePromotionCard")
	proto.RegisterType((*SellerProfile)(nil), "ContentFeedService_proto.SellerProfile")
	proto.RegisterType((*Photo)(nil), "ContentFeedService_proto.Photo")
	proto.RegisterType((*SellerReview)(nil), "ContentFeedService_proto.SellerReview")
	proto.RegisterType((*SellerReview_Review)(nil), "ContentFeedService_proto.SellerReview.Review")
	proto.RegisterType((*SellerFeedback)(nil), "ContentFeedService_proto.SellerFeedback")
	proto.RegisterType((*ShoutoutPromotionCard)(nil), "ContentFeedService_proto.ShoutoutPromotionCard")
	proto.RegisterType((*ShoutoutPromotionCard_ShoutoutTypeProfile)(nil), "ContentFeedService_proto.ShoutoutPromotionCard.ShoutoutTypeProfile")
	proto.RegisterType((*ShoutoutPromotionCard_ShoutoutTypeCollection)(nil), "ContentFeedService_proto.ShoutoutPromotionCard.ShoutoutTypeCollection")
	proto.RegisterType((*ExternalAd)(nil), "ContentFeedService_proto.ExternalAd")
	proto.RegisterType((*ExternalAdData)(nil), "ContentFeedService_proto.ExternalAdData")
	proto.RegisterType((*ExternalVidAd)(nil), "ContentFeedService_proto.ExternalVidAd")
	proto.RegisterType((*ExternalVidAdData)(nil), "ContentFeedService_proto.ExternalVidAdData")
	proto.RegisterType((*TrackingData)(nil), "ContentFeedService_proto.TrackingData")
	proto.RegisterType((*TrackingData_TrackingUrls)(nil), "ContentFeedService_proto.TrackingData.TrackingUrls")
	proto.RegisterType((*TrackingData_ActionType)(nil), "ContentFeedService_proto.TrackingData.ActionType")
}

func init() { proto.RegisterFile("content-feed/cats.proto", fileDescriptor_dee4e141de1d75c6) }

var fileDescriptor_dee4e141de1d75c6 = []byte{
	// 1763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x4b, 0x6f, 0x1b, 0xc9,
	0x11, 0x36, 0x87, 0x22, 0x29, 0x16, 0x29, 0x92, 0x6a, 0xcb, 0x32, 0xad, 0x2c, 0x60, 0x99, 0x0b,
	0x3b, 0x5a, 0x07, 0x96, 0x62, 0x19, 0x41, 0x90, 0x07, 0x02, 0x50, 0x22, 0x65, 0x11, 0xe6, 0x92,
	0x44, 0x73, 0xa8, 0x5d, 0x04, 0x0b, 0x0c, 0x9a, 0x33, 0x6d, 0x6a, 0xe0, 0xe1, 0x34, 0x33, 0xd3,
	0x94, 0x57, 0x39, 0x2e, 0x90, 0x7f, 0x90, 0x73, 0x4e, 0xf9, 0x15, 0x39, 0x25, 0x97, 0x5c, 0x72,
	0xcb, 0x39, 0xe7, 0x20, 0xf9, 0x03, 0x39, 0xe5, 0x10, 0xf4, 0x63, 0x1e, 0xa4, 0xa8, 0x87, 0xe1,
	0xdd, 0x00, 0x7b, 0xe2, 0xf4, 0xd7, 0x55, 0xd5, 0xf5, 0xee, 0x6a, 0xc2, 0x43, 0x9b, 0xf9, 0x9c,
	0xfa, 0xfc, 0xc5, 0x5b, 0x4a, 0x9d, 0x03, 0x9b, 0xf0, 0x70, 0x7f, 0x16, 0x30, 0xce, 0x50, 0xfd,
	0x58, 0x6d, 0x9c, 0x50, 0xea, 0x0c, 0x69, 0x70, 0xe1, 0xda, 0xd4, 0x92, 0x3b, 0x3b, 0x3b, 0x0b,
	0x2c, 0x9e, 0x1b, 0x72, 0xd7, 0x9f, 0x28, 0xae, 0xc6, 0x1f, 0x33, 0x50, 0x6b, 0x3a, 0x21, 0xa6,
	0xbf, 0x99, 0xd3, 0x90, 0xf7, 0x67, 0xdc, 0x65, 0x3e, 0x7a, 0x0a, 0x15, 0xe2, 0x5c, 0xd0, 0x80,
	0xbb, 0xa1, 0xeb, 0x4f, 0x2c, 0xd7, 0xa9, 0x67, 0x76, 0x33, 0x7b, 0x45, 0xbc, 0x91, 0x42, 0x3b,
	0x0e, 0x7a, 0x0a, 0x55, 0xe2, 0x58, 0x0e, 0xb3, 0x7c, 0xc6, 0x2d, 0x1e, 0x10, 0xfb, 0x5d, 0xdd,
	0xd8, 0xcd, 0xec, 0xad, 0xe3, 0x32, 0x71, 0x5a, 0xac, 0xc7, 0xb8, 0x29, 0x30, 0x74, 0x04, 0x40,
	0x1c, 0xeb, 0x82, 0x06, 0xa1, 0xcb, 0xfc, 0x7a, 0x76, 0x37, 0xb3, 0x57, 0x39, 0xfc, 0x74, 0xff,
	0x3a, 0x6d, 0xf7, 0x9b, 0xce, 0x99, 0x22, 0xc5, 0x45, 0x12, 0x7d, 0x36, 0xfe, 0x9b, 0x81, 0x47,
	0x2d, 0xea, 0xb8, 0x36, 0xe1, 0xd4, 0x19, 0xce, 0x18, 0xf7, 0xdc, 0xc9, 0x39, 0x1f, 0x52, 0x5b,
	0xea, 0x6b, 0xc3, 0xf6, 0x2c, 0x60, 0x53, 0xc6, 0xa9, 0x63, 0x69, 0xf3, 0x2c, 0x9b, 0x04, 0x4e,
	0x58, 0xcf, 0xec, 0x66, 0xf7, 0x4a, 0x87, 0x2f, 0xae, 0x3f, 0x6d, 0xa0, 0xf9, 0xba, 0x8a, 0xed,
	0x98, 0x04, 0x0e, 0xde, 0x9a, 0x5d, 0x05, 0x43, 0xf4, 0x29, 0x6c, 0x84, 0xea, 0x3c, 0x8b, 0xbb,
	0xdc, 0xa3, 0xd2, 0xd6, 0x22, 0x2e, 0x6b, 0xd0, 0x14, 0x18, 0xfa, 0x0c, 0x6a, 0x11, 0xd1, 0x8c,
	0x85, 0x2e, 0x8f, 0x2c, 0xce, 0xe1, 0xaa, 0xc6, 0x07, 0x1a, 0x46, 0xcf, 0x61, 0x33, 0x22, 0x0d,
	0xe7, 0x63, 0x2d, 0x73, 0x4d, 0xca, 0x8c, 0x68, 0x87, 0xf3, 0xb1, 0x14, 0xdb, 0xf8, 0x43, 0x16,
	0xee, 0xaf, 0xd0, 0x14, 0xbd, 0x81, 0x0d, 0xe9, 0x77, 0x61, 0xb0, 0x43, 0x38, 0x91, 0x71, 0x2a,
	0x1d, 0x3e, 0xbb, 0xde, 0x5e, 0x53, 0x93, 0xb7, 0x08, 0x27, 0xb8, 0xcc, 0x53, 0x2b, 0x74, 0x0a,
	0xe5, 0xb4, 0xf3, 0xa4, 0x7d, 0xa5, 0xc3, 0xa7, 0xd7, 0xcb, 0x4a, 0xfb, 0xac, 0xe4, 0xa5, 0xd4,
	0x1a, 0x41, 0x81, 0x38, 0x16, 0xbf, 0x9c, 0x51, 0x1d, 0xee, 0x5f, 0x7e, 0x50, 0x00, 0x62, 0xac,
	0xe9, 0x98, 0x97, 0x33, 0x8a, 0xf3, 0x44, 0xfe, 0x8a, 0x08, 0xa8, 0xc8, 0xc8, 0x18, 0x90, 0x89,
	0xf6, 0x56, 0x39, 0x06, 0x4d, 0x32, 0x41, 0x75, 0x28, 0xc8, 0x74, 0xff, 0x9a, 0xd7, 0x73, 0x72,
	0x3b, 0x5a, 0xa2, 0x27, 0x90, 0x50, 0x8a, 0x9c, 0xce, 0xcb, 0xed, 0x52, 0x8c, 0x75, 0x9c, 0xc6,
	0x4f, 0xa1, 0xb2, 0x78, 0x36, 0xaa, 0x42, 0x69, 0x80, 0xfb, 0x9f, 0xf7, 0xcd, 0x76, 0xcb, 0x7a,
	0xf9, 0xe3, 0xda, 0x3d, 0xb4, 0x05, 0x35, 0xb3, 0x3f, 0xb0, 0x86, 0x83, 0xbe, 0xd9, 0xed, 0xbc,
	0x3e, 0x35, 0x05, 0x9a, 0x69, 0xfc, 0xd3, 0x80, 0xad, 0x41, 0xc0, 0xde, 0xba, 0x1e, 0x1d, 0x44,
	0xf2, 0xbe, 0x8b, 0x08, 0x95, 0x42, 0xea, 0x79, 0x34, 0x50, 0xa2, 0x54, 0x80, 0x7e, 0x78, 0xbd,
	0xa8, 0xa1, 0x24, 0xd6, 0x7a, 0x61, 0x50, 0xbc, 0x52, 0xd2, 0x08, 0xb6, 0xa3, 0x58, 0xf3, 0xf3,
	0xf9, 0x74, 0xec, 0x13, 0xd7, 0xb3, 0xe6, 0x81, 0x17, 0xd6, 0xb3, 0xb2, 0x62, 0x1e, 0xdf, 0x10,
	0xb0, 0x73, 0xc6, 0x19, 0xde, 0xd2, 0xec, 0x66, 0xc4, 0x3d, 0x0a, 0xbc, 0xf0, 0xff, 0x10, 0xa1,
	0x7f, 0x1b, 0xb0, 0xb1, 0x60, 0x16, 0xaa, 0x80, 0x11, 0x37, 0x28, 0xc3, 0x75, 0xd0, 0x0e, 0xac,
	0xcf, 0x43, 0x1a, 0xf8, 0x64, 0x1a, 0x95, 0x68, 0xbc, 0x46, 0xbb, 0x50, 0x72, 0x68, 0x68, 0x07,
	0xee, 0x2c, 0xae, 0xcc, 0x22, 0x4e, 0x43, 0xe8, 0x14, 0xaa, 0x33, 0x25, 0xd8, 0x9a, 0xb9, 0x36,
	0x9f, 0x07, 0xaa, 0x26, 0xef, 0xe0, 0x91, 0x8a, 0xe6, 0x1b, 0x28, 0x36, 0xf4, 0x73, 0x78, 0x44,
	0x1c, 0x47, 0xd6, 0x3a, 0xf1, 0xa2, 0xb6, 0x14, 0x5a, 0x36, 0x9b, 0xfb, 0xca, 0xf0, 0x1c, 0x7e,
	0x98, 0x10, 0xe8, 0xf4, 0x0f, 0x8f, 0xc5, 0x36, 0xfa, 0x15, 0xe4, 0x03, 0x7a, 0xe1, 0xd2, 0xf7,
	0xd2, 0x05, 0x37, 0xa6, 0x8b, 0x72, 0x06, 0x96, 0xd4, 0x58, 0x73, 0xa1, 0x16, 0xac, 0x8b, 0x5e,
	0x3f, 0x16, 0x2d, 0xb9, 0x20, 0x25, 0xec, 0xdd, 0x26, 0xe1, 0x44, 0xd3, 0xe3, 0x98, 0x53, 0x34,
	0xdd, 0x9c, 0xb4, 0x4d, 0xc4, 0x75, 0x21, 0x4d, 0xb4, 0xbb, 0xcb, 0x3c, 0x15, 0x7d, 0x61, 0x70,
	0x42, 0x34, 0x0b, 0xd8, 0x24, 0xa0, 0x61, 0xe8, 0x5e, 0x50, 0xc9, 0xa0, 0x22, 0xf1, 0x30, 0x26,
	0x18, 0x24, 0xfb, 0x82, 0xb7, 0x0d, 0x8f, 0x57, 0xf3, 0x7a, 0xec, 0xbd, 0x15, 0x10, 0x7f, 0x42,
	0x75, 0x1b, 0xfd, 0x64, 0x95, 0x84, 0x2e, 0x7b, 0x8f, 0x05, 0x0d, 0x7a, 0x03, 0x8d, 0xd5, 0x62,
	0xa6, 0xd4, 0x71, 0xe7, 0x53, 0x2d, 0x69, 0x4d, 0x4a, 0x7a, 0xbc, 0x4a, 0xd2, 0xe7, 0x92, 0x4e,
	0x0a, 0x6b, 0x7c, 0x63, 0x40, 0x39, 0xed, 0x5d, 0xf4, 0x1a, 0x0a, 0xca, 0xbf, 0x77, 0xb8, 0x57,
	0xd2, 0x8c, 0xfb, 0x3a, 0x3a, 0x11, 0xf7, 0x0e, 0x85, 0xbc, 0x16, 0xd9, 0x86, 0x35, 0xd9, 0x26,
	0x33, 0xb2, 0x4d, 0xbe, 0xfc, 0x20, 0x79, 0xb2, 0x37, 0x4a, 0x76, 0xb4, 0x05, 0x39, 0x95, 0x57,
	0x86, 0x34, 0x4d, 0x2d, 0x1a, 0x47, 0x00, 0x09, 0x25, 0x2a, 0x41, 0x61, 0xd4, 0x7b, 0xd3, 0xeb,
	0x7f, 0xd1, 0xab, 0xdd, 0x43, 0x65, 0x58, 0x1f, 0xf4, 0x87, 0x1d, 0xb3, 0x73, 0xd6, 0xae, 0x65,
	0xc4, 0x56, 0xaf, 0x3d, 0x32, 0x71, 0xb3, 0x5b, 0x33, 0xc4, 0x56, 0xaf, 0xfd, 0xba, 0x29, 0xb7,
	0xb2, 0x8d, 0x67, 0x50, 0x59, 0xcc, 0x0f, 0x71, 0x56, 0x68, 0xb3, 0x40, 0xe9, 0x6c, 0x60, 0xb5,
	0x68, 0xfc, 0x35, 0x0f, 0x0f, 0x86, 0xe7, 0x6c, 0xce, 0xd9, 0x9c, 0x7f, 0x2f, 0x3a, 0xe0, 0x72,
	0xaf, 0x59, 0xbb, 0xd2, 0x6b, 0xc4, 0x0d, 0xed, 0x86, 0x96, 0x68, 0x1e, 0xd6, 0x5b, 0xe6, 0x79,
	0xec, 0xbd, 0xeb, 0x4f, 0x64, 0xe5, 0xae, 0xe3, 0xaa, 0x1b, 0x8e, 0x42, 0x1a, 0x9c, 0x44, 0xb0,
	0x6c, 0x6a, 0x44, 0x75, 0x95, 0xbc, 0x6e, 0x6a, 0x6a, 0x89, 0x2e, 0xe1, 0x41, 0xa8, 0x1d, 0x23,
	0xaf, 0x44, 0x4b, 0xf7, 0x09, 0x5d, 0x98, 0xc7, 0x37, 0x28, 0xbf, 0xca, 0x9f, 0x31, 0x2a, 0x82,
	0xaa, 0x0d, 0x3b, 0xbd, 0x87, 0xef, 0x87, 0x57, 0x61, 0xf4, 0x4d, 0x06, 0xea, 0x8b, 0x67, 0xdb,
	0xcc, 0xf3, 0xd4, 0x6c, 0x51, 0x5f, 0x97, 0xc7, 0x9f, 0x7c, 0xcc, 0xf1, 0xc7, 0xb1, 0xb4, 0xd3,
	0x7b, 0x78, 0x3b, 0x5c, 0xb9, 0xb3, 0xf3, 0xbb, 0x0c, 0xdc, 0x5f, 0xa1, 0x33, 0x7a, 0x08, 0x05,
	0xe9, 0xda, 0xb8, 0x79, 0xe7, 0xc5, 0xb2, 0xe3, 0xdc, 0x70, 0x37, 0x19, 0x1f, 0x71, 0x37, 0xed,
	0xfc, 0x3e, 0x03, 0xdb, 0xab, 0x95, 0x17, 0xed, 0x2d, 0x71, 0x4c, 0xa2, 0x50, 0x39, 0x01, 0xbf,
	0x33, 0xb5, 0x8e, 0x2a, 0x50, 0x4e, 0x3b, 0xae, 0xf1, 0x77, 0x03, 0xa0, 0xfd, 0x35, 0x17, 0x17,
	0x96, 0xd7, 0xfc, 0x96, 0xab, 0x07, 0x43, 0x8d, 0x6a, 0xd1, 0x96, 0x98, 0xdc, 0x93, 0x12, 0xba,
	0xe1, 0x7a, 0x48, 0x94, 0x91, 0x12, 0x2b, 0x74, 0x61, 0x8d, 0xba, 0xcb, 0xb3, 0xde, 0xab, 0xbb,
	0x88, 0x4a, 0x7d, 0x2e, 0x8c, 0x78, 0xb7, 0x57, 0x65, 0xe3, 0x10, 0x2a, 0x8b, 0xcc, 0x62, 0x46,
	0x6b, 0x7f, 0x69, 0xb6, 0x71, 0xaf, 0xd9, 0x55, 0x33, 0x5a, 0x1a, 0x38, 0x14, 0xe3, 0xd9, 0x7f,
	0x8c, 0x34, 0x93, 0xd4, 0x7b, 0x0b, 0x72, 0x6a, 0xe4, 0x56, 0xb1, 0x56, 0x8b, 0xe5, 0x01, 0xc1,
	0xb8, 0x3a, 0x20, 0x3c, 0x87, 0xcd, 0x59, 0xe0, 0x4e, 0x49, 0x70, 0x69, 0xcd, 0x44, 0x58, 0xe5,
	0xed, 0xa6, 0x06, 0x89, 0xaa, 0xde, 0x90, 0xe1, 0x16, 0xb7, 0xda, 0x63, 0x28, 0x79, 0xc4, 0x77,
	0x44, 0xec, 0x04, 0x95, 0x32, 0x06, 0x34, 0x24, 0x08, 0x3e, 0x83, 0x9a, 0xe8, 0xa9, 0x93, 0x80,
	0xcd, 0x7d, 0x47, 0x14, 0x27, 0x0b, 0xf4, 0x4c, 0x54, 0x4d, 0xf0, 0x63, 0x01, 0x0b, 0x59, 0xf1,
	0x1b, 0x67, 0x7c, 0xa9, 0x9b, 0x0c, 0x44, 0xd0, 0xd1, 0x25, 0x7a, 0x26, 0x27, 0x97, 0x88, 0x40,
	0x4e, 0x5f, 0x05, 0xf5, 0x6a, 0x4b, 0x88, 0xc4, 0xf8, 0xb5, 0x44, 0x27, 0x14, 0x5b, 0x5f, 0xa6,
	0x13, 0xba, 0xfd, 0x00, 0x8a, 0x36, 0x27, 0xfa, 0x5d, 0x52, 0x54, 0x83, 0x94, 0xcd, 0x89, 0x7a,
	0xe7, 0x3c, 0x83, 0xea, 0x38, 0x20, 0xbe, 0x63, 0xb9, 0x53, 0x32, 0x51, 0x37, 0x3c, 0x28, 0x21,
	0x12, 0xee, 0x08, 0x74, 0x14, 0x78, 0x8d, 0x7f, 0x19, 0xb0, 0x11, 0x39, 0xfe, 0xcc, 0x75, 0xbe,
	0xed, 0x84, 0xfe, 0x0a, 0xb6, 0xe2, 0x84, 0xbe, 0x70, 0x9d, 0xa5, 0xa4, 0xfe, 0xd1, 0xed, 0x99,
	0x28, 0x75, 0x92, 0x82, 0x37, 0xe9, 0x32, 0x84, 0xf0, 0x72, 0x6a, 0xff, 0xec, 0x8e, 0x02, 0x17,
	0x57, 0x1f, 0x9a, 0xe0, 0x3f, 0x81, 0xcd, 0x2b, 0xfc, 0x8b, 0xb7, 0xf7, 0x7d, 0xa8, 0xc6, 0xf9,
	0x7d, 0xd6, 0x69, 0xa9, 0x1c, 0xff, 0xb3, 0xb1, 0xc4, 0xf7, 0x51, 0x69, 0xbe, 0x94, 0x6e, 0xd9,
	0xbb, 0xa4, 0xdb, 0xda, 0xaa, 0x74, 0x5b, 0x48, 0xa3, 0xdc, 0xed, 0x69, 0x94, 0x5f, 0x91, 0x46,
	0xcb, 0x85, 0x54, 0xb8, 0x52, 0x48, 0x2d, 0x80, 0x0b, 0xd7, 0xa1, 0x4c, 0x85, 0x7f, 0xfd, 0xb6,
	0x97, 0xab, 0x18, 0xf3, 0xc8, 0xfe, 0x99, 0xe0, 0xc0, 0x45, 0xc9, 0x28, 0x9c, 0xd5, 0xf8, 0x47,
	0x16, 0xca, 0xe9, 0x6c, 0x43, 0x5f, 0xa6, 0x92, 0x55, 0xb6, 0x7a, 0x95, 0xac, 0xaf, 0xee, 0x96,
	0xac, 0xf1, 0x42, 0x34, 0xfa, 0x24, 0x73, 0xe5, 0x4b, 0xe9, 0x09, 0xc4, 0x6b, 0xe9, 0x3b, 0x1d,
	0x82, 0x08, 0x13, 0x9e, 0x7b, 0x02, 0x65, 0x31, 0xbc, 0x91, 0xb1, 0x47, 0x25, 0x89, 0x7e, 0xad,
	0x44, 0x98, 0x20, 0xa9, 0x41, 0xf6, 0xb7, 0x71, 0x12, 0x89, 0xcf, 0x9d, 0xbf, 0x65, 0x12, 0x13,
	0xe4, 0x41, 0xbb, 0x50, 0x72, 0xa7, 0x33, 0x39, 0xde, 0x32, 0x5f, 0x0d, 0xae, 0x45, 0x9c, 0x86,
	0xd0, 0x27, 0x50, 0x8c, 0x64, 0xaa, 0xbb, 0xac, 0x88, 0x13, 0x00, 0x6d, 0x43, 0xde, 0xf6, 0x5c,
	0xfb, 0x9d, 0x7a, 0x19, 0x16, 0xb1, 0x5e, 0xa1, 0x0e, 0xe4, 0x89, 0x1a, 0x24, 0xd4, 0xfb, 0xe8,
	0xe5, 0x1d, 0x7d, 0xd2, 0x54, 0xff, 0x96, 0xa8, 0x9a, 0x50, 0xd7, 0x6f, 0x1d, 0x0a, 0x6a, 0xbe,
	0x0a, 0xeb, 0x39, 0x79, 0x46, 0xb4, 0xdc, 0xe9, 0x02, 0x24, 0xf4, 0x42, 0x15, 0x7d, 0xa4, 0x1e,
	0x18, 0x34, 0x3f, 0x82, 0x35, 0xcf, 0x7d, 0x17, 0xbd, 0xf6, 0xe4, 0xb7, 0xc0, 0xec, 0x73, 0xc2,
	0xb5, 0xd3, 0xe4, 0xf7, 0xf3, 0xbf, 0x64, 0xa0, 0x18, 0xff, 0xbb, 0x84, 0xb6, 0x01, 0xb5, 0xda,
	0x27, 0xcd, 0x51, 0xd7, 0xb4, 0x9a, 0x2d, 0xeb, 0xac, 0x8d, 0x87, 0x9d, 0xbe, 0x28, 0xae, 0x07,
	0xb0, 0x99, 0x3c, 0xee, 0x71, 0xfb, 0x08, 0x37, 0x7b, 0xad, 0x5a, 0x46, 0xc0, 0x5f, 0x74, 0xcc,
	0x53, 0x2b, 0x2e, 0xbc, 0x66, 0x6b, 0x58, 0x33, 0xd0, 0x16, 0xd4, 0x24, 0x3c, 0xec, 0xf4, 0x5e,
	0x77, 0xdb, 0xd6, 0xb0, 0xdb, 0x37, 0x6b, 0x59, 0xf4, 0x08, 0x1e, 0x2c, 0x12, 0x8b, 0x2a, 0x15,
	0x0c, 0x6b, 0x31, 0xc3, 0x00, 0xf7, 0x4f, 0x3a, 0xdd, 0xb6, 0x44, 0x73, 0xa8, 0x06, 0x65, 0x89,
	0xb6, 0x86, 0x43, 0x89, 0xe4, 0xe3, 0xf3, 0x86, 0xa7, 0xfd, 0x91, 0xd9, 0x1f, 0x99, 0x12, 0x2e,
	0x1c, 0x7d, 0xf5, 0xeb, 0xde, 0xc4, 0xe5, 0xe7, 0xf3, 0xf1, 0xbe, 0xcd, 0xa6, 0x07, 0x36, 0x09,
	0xd8, 0x5c, 0x0c, 0xb5, 0x07, 0xe1, 0x39, 0x09, 0xa8, 0xf3, 0x42, 0x3a, 0xfc, 0x60, 0x42, 0xfd,
	0x83, 0x09, 0x3b, 0x48, 0xff, 0xed, 0xf7, 0x8b, 0xeb, 0xa2, 0xf3, 0x27, 0xa3, 0x78, 0x7c, 0xa2,
	0x91, 0x71, 0x5e, 0x42, 0xaf, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x36, 0x39, 0xcf, 0x65,
	0x14, 0x00, 0x00,
}
