// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: content-feed/contentfeed.proto

package ContentFeedService_proto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterContentFeedServiceOrionServer registers ContentFeedService to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterContentFeedServiceOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_ContentFeedService_serviceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterContentFeedServiceDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "ContentFeedService", encoder)
}

// DefaultDecoder
func RegisterContentFeedServiceDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "ContentFeedService", decoder)
}

