// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content-feed/contentfeed.proto

package ContentFeedService_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("content-feed/contentfeed.proto", fileDescriptor_f5c7115f5cd0735d) }

var fileDescriptor_f5c7115f5cd0735d = []byte{
	// 912 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x98, 0xdf, 0x6f, 0xdc, 0x44,
	0x10, 0xc7, 0xe3, 0x17, 0x1e, 0xf6, 0x01, 0x09, 0x53, 0xda, 0x92, 0x16, 0x24, 0xf2, 0xde, 0xfb,
	0x65, 0x17, 0xda, 0xa4, 0x20, 0x41, 0x8e, 0x73, 0x4f, 0x6a, 0xd1, 0xa9, 0x97, 0x9c, 0x54, 0x5e,
	0x22, 0x77, 0x3d, 0xf5, 0xad, 0xba, 0xf6, 0x9a, 0xdd, 0x75, 0xd0, 0x49, 0xa0, 0x0a, 0x45, 0xad,
	0x84, 0x80, 0x87, 0x08, 0x24, 0x9e, 0x90, 0xf8, 0x53, 0x91, 0x7f, 0xdc, 0x79, 0x7d, 0xfe, 0x71,
	0x3e, 0x1b, 0xa9, 0x4f, 0x6d, 0x3c, 0xf3, 0x9d, 0xf9, 0x64, 0x76, 0x76, 0x66, 0x15, 0xf4, 0x29,
	0x66, 0xbe, 0x04, 0x5f, 0xde, 0x7b, 0x09, 0xe0, 0xf4, 0xd3, 0x1f, 0xa2, 0xff, 0xf7, 0x02, 0xce,
	0x24, 0xd3, 0x6f, 0x9f, 0x26, 0x9f, 0x26, 0x00, 0xce, 0x1c, 0xf8, 0x25, 0xc1, 0x70, 0x11, 0x5b,
	0x0e, 0xef, 0xe6, 0x94, 0x02, 0x6c, 0x8e, 0x97, 0x17, 0x97, 0x46, 0xaf, 0xce, 0x6a, 0xa6, 0xd6,
	0x9b, 0x39, 0x2b, 0x07, 0x9c, 0x7e, 0xbf, 0x95, 0xfb, 0x1e, 0x0a, 0xe0, 0xa9, 0xe1, 0x4e, 0xce,
	0x40, 0x7c, 0x09, 0xdc, 0xb7, 0x69, 0x6a, 0xfc, 0x2c, 0x67, 0x0c, 0x38, 0x73, 0x42, 0x2c, 0x2f,
	0x92, 0x9c, 0xa5, 0x38, 0xd8, 0x4d, 0x9d, 0x12, 0xeb, 0xe8, 0xcd, 0x11, 0xd2, 0x8b, 0xbf, 0xa7,
	0xfe, 0x13, 0xfa, 0x60, 0x1e, 0x07, 0x79, 0x42, 0x84, 0x24, 0xbe, 0x2b, 0x16, 0xe6, 0x40, 0x1f,
	0xf6, 0xaa, 0x2a, 0xd2, 0xcb, 0x3b, 0x3f, 0x83, 0x1f, 0x42, 0x10, 0x72, 0x61, 0x1e, 0x8e, 0x9a,
	0x4b, 0x44, 0xc0, 0x7c, 0x01, 0x0b, 0xf3, 0xe8, 0x40, 0xff, 0x4b, 0x43, 0x1f, 0x5b, 0x20, 0xf3,
	0x1e, 0x67, 0x4c, 0xda, 0x34, 0xc2, 0x78, 0x58, 0x1d, 0xb3, 0x5c, 0x94, 0xe1, 0x1c, 0xef, 0x2f,
	0x55, 0xb0, 0x7e, 0x2e, 0x14, 0xc5, 0x30, 0xf7, 0x2f, 0x8a, 0x71, 0x68, 0xec, 0x5d, 0x14, 0x23,
	0x4a, 0xff, 0x7b, 0x75, 0x55, 0x8c, 0x41, 0x1b, 0x8e, 0xf6, 0xd5, 0x30, 0x8e, 0x0e, 0xf4, 0x2b,
	0x0d, 0xdd, 0x48, 0x7c, 0xe6, 0x01, 0xce, 0x2a, 0x62, 0xe8, 0xe6, 0x2e, 0x12, 0xc5, 0xbf, 0x53,
	0x51, 0x22, 0x8a, 0xdf, 0x34, 0x74, 0x3b, 0xb1, 0xcf, 0x38, 0x7b, 0x49, 0x28, 0xa8, 0x24, 0x0f,
	0x76, 0xc5, 0xdc, 0xd2, 0x74, 0xa6, 0x79, 0xab, 0xa1, 0xc3, 0xc4, 0x3e, 0x61, 0x94, 0xb2, 0x1f,
	0x89, 0xef, 0xbe, 0x9b, 0x5e, 0xf9, 0x53, 0x43, 0x77, 0x2d, 0x90, 0x4f, 0x19, 0x87, 0x09, 0x67,
	0xde, 0xd9, 0x92, 0x88, 0x39, 0x50, 0x0a, 0x3c, 0x0a, 0xb3, 0x18, 0x0e, 0xf4, 0x47, 0xb5, 0x67,
	0x5f, 0xae, 0x5b, 0x53, 0x0d, 0xdb, 0x52, 0xbd, 0xd1, 0xd0, 0x0d, 0x0b, 0xe4, 0xe3, 0x55, 0x00,
	0x9c, 0x32, 0x6c, 0xd3, 0x35, 0x8d, 0x59, 0x4b, 0x93, 0xf7, 0xcf, 0x28, 0xee, 0xef, 0xa5, 0x4a,
	0x41, 0x86, 0x95, 0x1c, 0xa3, 0x76, 0x1c, 0xa3, 0x76, 0x1c, 0xa3, 0xa3, 0x03, 0xfd, 0x57, 0x0d,
	0xdd, 0xb2, 0x40, 0x9e, 0x0b, 0xe0, 0x4f, 0xc8, 0x2b, 0x70, 0xd4, 0x5e, 0xf9, 0xa2, 0x36, 0x68,
	0x41, 0xd2, 0xb9, 0x63, 0x04, 0x7a, 0x3f, 0x31, 0x47, 0xa1, 0x45, 0x74, 0x28, 0xbd, 0x5d, 0x81,
	0x62, 0xcf, 0xec, 0x38, 0xfa, 0x0d, 0xfd, 0x95, 0x83, 0xd8, 0xac, 0x99, 0x59, 0xb2, 0x94, 0xe2,
	0xbc, 0xc3, 0x06, 0xb7, 0x36, 0x76, 0xce, 0x52, 0x8f, 0x9a, 0x4b, 0x94, 0xec, 0xd1, 0x9a, 0x99,
	0xa6, 0xfb, 0x74, 0x6b, 0xb0, 0x0f, 0x6b, 0xd7, 0x4c, 0xb9, 0x28, 0xc3, 0x39, 0xde, 0x5f, 0xaa,
	0x60, 0xfd, 0x91, 0xcc, 0xf9, 0xa9, 0x17, 0x84, 0x54, 0xc0, 0x2c, 0xe4, 0x78, 0x69, 0x0b, 0x58,
	0x5f, 0x95, 0xfa, 0xed, 0x57, 0x22, 0xea, 0x7c, 0x6b, 0xaf, 0x92, 0xdb, 0x32, 0xb6, 0x09, 0x5d,
	0xcd, 0x08, 0x7e, 0x25, 0x12, 0x94, 0xe1, 0x8e, 0xdb, 0x92, 0xf7, 0xef, 0x4c, 0x11, 0x0d, 0x7a,
	0x0b, 0xe4, 0x73, 0x16, 0x3e, 0xb5, 0x57, 0x5f, 0x53, 0xc1, 0xa2, 0xf6, 0x5f, 0x93, 0x3c, 0xa8,
	0x25, 0x29, 0x6a, 0x3a, 0xd3, 0x5c, 0x57, 0xd3, 0x0c, 0x3a, 0xd0, 0x3c, 0xdc, 0x5b, 0xa9, 0xf4,
	0xcd, 0xb5, 0x86, 0xee, 0x58, 0x20, 0x9f, 0x01, 0x66, 0x9e, 0x07, 0xbe, 0x03, 0xce, 0x84, 0xf1,
	0xe7, 0x2c, 0x5c, 0x63, 0x9d, 0xd4, 0x06, 0x2f, 0x95, 0x75, 0xaa, 0x93, 0x91, 0x9d, 0xda, 0x98,
	0xb3, 0x20, 0x00, 0x67, 0xea, 0xcf, 0x38, 0xc1, 0x0d, 0xeb, 0x54, 0xd4, 0xfc, 0x5f, 0xfb, 0x27,
	0xee, 0xcc, 0x31, 0x11, 0x98, 0x5d, 0x02, 0x5f, 0xed, 0xde, 0x3f, 0x79, 0xff, 0xa6, 0xfb, 0x67,
	0x5b, 0xa5, 0x9c, 0xd4, 0x3f, 0xc9, 0x76, 0xce, 0x7b, 0xa8, 0xb3, 0xe7, 0xd1, 0x1e, 0x91, 0x8b,
	0xe3, 0xe7, 0xcb, 0x56, 0x6a, 0x85, 0xef, 0x5f, 0x0d, 0x7d, 0x62, 0x81, 0x8c, 0xa2, 0x10, 0x3f,
	0x84, 0xf9, 0x92, 0x05, 0x01, 0xf1, 0xdd, 0x09, 0xdb, 0x3c, 0x1f, 0xea, 0x53, 0x54, 0x08, 0x33,
	0xc2, 0xaf, 0xda, 0xc9, 0x15, 0xc4, 0xd7, 0x48, 0xb7, 0x40, 0x9e, 0xb1, 0x40, 0x99, 0x48, 0x03,
	0x7d, 0x54, 0x1b, 0x57, 0xf5, 0xee, 0xdc, 0x4b, 0xaf, 0xd1, 0x87, 0x16, 0xc8, 0x6f, 0x1d, 0x2f,
	0x35, 0x9f, 0x73, 0x1a, 0x11, 0x0c, 0x6a, 0x09, 0x32, 0xf7, 0x2c, 0xbf, 0xd9, 0x50, 0x71, 0xce,
	0x69, 0xae, 0x02, 0x57, 0x1a, 0xfa, 0x28, 0xe7, 0x30, 0xf5, 0x6c, 0x17, 0xda, 0x31, 0x7c, 0xde,
	0x50, 0x11, 0xa7, 0xc8, 0x51, 0xfc, 0x92, 0x5c, 0xa9, 0xcc, 0x65, 0x0c, 0x02, 0xb7, 0x83, 0xb8,
	0xdf, 0x50, 0x11, 0x65, 0x28, 0xe9, 0x85, 0xc7, 0xcc, 0x8b, 0xa7, 0xc4, 0x84, 0x03, 0xec, 0xee,
	0x05, 0xd5, 0xbb, 0x73, 0x2f, 0xfc, 0xbd, 0x79, 0xf6, 0x9f, 0x5a, 0xe9, 0x4b, 0x43, 0xbd, 0xcd,
	0xc7, 0xbb, 0xa2, 0x16, 0x54, 0x19, 0xd1, 0x49, 0x0b, 0x6d, 0x71, 0xd2, 0x6c, 0x9c, 0x16, 0x36,
	0x27, 0xb6, 0x2f, 0x4f, 0x59, 0xe8, 0xcb, 0x06, 0x93, 0xa6, 0x5c, 0xd7, 0x74, 0xd2, 0x54, 0xa9,
	0x15, 0xbe, 0xb7, 0x1a, 0xba, 0x69, 0x81, 0x5c, 0x3f, 0xcf, 0xd6, 0xa7, 0x12, 0x91, 0xd5, 0xf7,
	0xe4, 0xb6, 0xa2, 0xe3, 0x5b, 0xf0, 0x9b, 0xd9, 0xf7, 0xdf, 0xb9, 0x44, 0x2e, 0xc3, 0x17, 0x3d,
	0xcc, 0xbc, 0x3e, 0xb6, 0x39, 0x0b, 0x05, 0x50, 0xda, 0x17, 0x4b, 0x9b, 0x83, 0x73, 0x2f, 0xd6,
	0xf7, 0x5d, 0xf0, 0xfb, 0x2e, 0xeb, 0xab, 0x7f, 0x50, 0x39, 0xa9, 0x4a, 0xf6, 0xe2, 0xbd, 0xf8,
	0x1f, 0xe3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x90, 0xd2, 0x4c, 0x67, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContentFeedServiceClient is the client API for ContentFeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContentFeedServiceClient interface {
	// search
	SearchListingsV40(ctx context.Context, in *SearchListingsRequestV4, opts ...grpc.CallOption) (*SearchListingsResponseV4, error)
	GetSearchListingsTotalV40(ctx context.Context, in *GetSearchListingsTotalRequestV4, opts ...grpc.CallOption) (*GetSearchListingsTotalResponseV4, error)
	SearchListingsV34(ctx context.Context, in *SearchListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetSearchListingsTotalV30(ctx context.Context, in *SearchListingsRequestV3, opts ...grpc.CallOption) (*GetSearchListingsTotalResponseV3, error)
	SearchSpcListingsV33(ctx context.Context, in *SearchSpcListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV33, error)
	SearchProfileListingsV33(ctx context.Context, in *SearchProfileListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV33, error)
	SearchFollowingListingsV34(ctx context.Context, in *SearchListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetMoreFromThisSellerFeedV10(ctx context.Context, in *GetMoreFromThisSellerFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetHyperlocalFeedV10(ctx context.Context, in *GetHyperlocalFeedRequestV1, opts ...grpc.CallOption) (*GetHyperlocalFeedResponseV1, error)
	GetHyperlocalFeedV20(ctx context.Context, in *GetHyperlocalFeedRequestV2, opts ...grpc.CallOption) (*GetHyperlocalFeedResponseV2, error)
	GetUserLikedListingsV34(ctx context.Context, in *GetUserLikedListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	// user search
	SearchUsersV10(ctx context.Context, in *SearchUsersRequestV1, opts ...grpc.CallOption) (*SearchUsersResponseV1, error)
	// product search
	SearchProductsV10(ctx context.Context, in *SearchProductsRequestV1, opts ...grpc.CallOption) (*SearchProductsResponseV1, error)
	// internal search
	InternalSearchListingsV10(ctx context.Context, in *InternalSearchListingsRequestV1, opts ...grpc.CallOption) (*InternalSearchListingsResponseV1, error)
	// recommendation
	GetImpulsePurchaseFeedV10(ctx context.Context, in *GetImpulsePurchaseFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetDailyPicksFeedV11(ctx context.Context, in *GetDailyPicksFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetYouMayAlsoLikeFeedV11(ctx context.Context, in *GetYouMayAlsoLikeFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetYouMayAlsoLikeFeedV10(ctx context.Context, in *GetYouMayAlsoLikeFeedRequestV1, opts ...grpc.CallOption) (*GetYouMayAlsoLikeFeedResponseV1, error)
	GetRecommendedForYouFeedV10(ctx context.Context, in *GetRecommendedForYouFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV33, error)
	GetDroppedInPriceFeedV10(ctx context.Context, in *GetDroppedInPriceFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetDailyDiscoveryV10(ctx context.Context, in *GetDailyDiscoveryRequestV1, opts ...grpc.CallOption) (*GetDailyDiscoveryResponseV1, error)
	GetDailyDiscoveryListingsV10(ctx context.Context, in *GetDailyDiscoveryListingsRequestV1, opts ...grpc.CallOption) (*GetDailyDiscoveryListingsResponseV1, error)
	GetContinueShoppingForFeedV10(ctx context.Context, in *GetContinueShoppingForFeedRequestV1, opts ...grpc.CallOption) (*GetContinueShoppingForFeedResponseV1, error)
	GetTopPicksFeedV10(ctx context.Context, in *GetTopPicksFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	GetEdmListingUrlV10(ctx context.Context, in *GetEdmListingRequestV1, opts ...grpc.CallOption) (*GetEdmListingUrlResponseV1, error)
	GetEdmListingImageV10(ctx context.Context, in *GetEdmListingRequestV1, opts ...grpc.CallOption) (*GetEdmListingImageResponseV1, error)
	GetEdmListingDescV10(ctx context.Context, in *GetEdmListingRequestV1, opts ...grpc.CallOption) (*GetEdmListingDescResponseV1, error)
	GetHomeFeedFreeV10(ctx context.Context, in *GetHomeFeedFreeRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error)
	SearchCGProductListingsV10(ctx context.Context, in *SearchCGProductListingsRequestV1, opts ...grpc.CallOption) (*SearchCGProductListingsResponseV1, error)
	GetCGProductVariantCountsV10(ctx context.Context, in *GetCGProductVariantCountsRequestV1, opts ...grpc.CallOption) (*GetCGProductVariantCountsResponseV1, error)
	// product home feed
	GetProductsHomeFeedV10(ctx context.Context, in *GetProductsHomeFeedRequestV1, opts ...grpc.CallOption) (*SearchProductsResponseV1, error)
}

type contentFeedServiceClient struct {
	cc *grpc.ClientConn
}

func NewContentFeedServiceClient(cc *grpc.ClientConn) ContentFeedServiceClient {
	return &contentFeedServiceClient{cc}
}

func (c *contentFeedServiceClient) SearchListingsV40(ctx context.Context, in *SearchListingsRequestV4, opts ...grpc.CallOption) (*SearchListingsResponseV4, error) {
	out := new(SearchListingsResponseV4)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchListingsV40", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetSearchListingsTotalV40(ctx context.Context, in *GetSearchListingsTotalRequestV4, opts ...grpc.CallOption) (*GetSearchListingsTotalResponseV4, error) {
	out := new(GetSearchListingsTotalResponseV4)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetSearchListingsTotalV40", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) SearchListingsV34(ctx context.Context, in *SearchListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchListingsV34", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetSearchListingsTotalV30(ctx context.Context, in *SearchListingsRequestV3, opts ...grpc.CallOption) (*GetSearchListingsTotalResponseV3, error) {
	out := new(GetSearchListingsTotalResponseV3)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetSearchListingsTotalV30", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) SearchSpcListingsV33(ctx context.Context, in *SearchSpcListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV33, error) {
	out := new(SearchListingsResponseV33)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchSpcListingsV33", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) SearchProfileListingsV33(ctx context.Context, in *SearchProfileListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV33, error) {
	out := new(SearchListingsResponseV33)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchProfileListingsV33", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) SearchFollowingListingsV34(ctx context.Context, in *SearchListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchFollowingListingsV34", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetMoreFromThisSellerFeedV10(ctx context.Context, in *GetMoreFromThisSellerFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetMoreFromThisSellerFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetHyperlocalFeedV10(ctx context.Context, in *GetHyperlocalFeedRequestV1, opts ...grpc.CallOption) (*GetHyperlocalFeedResponseV1, error) {
	out := new(GetHyperlocalFeedResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetHyperlocalFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetHyperlocalFeedV20(ctx context.Context, in *GetHyperlocalFeedRequestV2, opts ...grpc.CallOption) (*GetHyperlocalFeedResponseV2, error) {
	out := new(GetHyperlocalFeedResponseV2)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetHyperlocalFeedV20", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetUserLikedListingsV34(ctx context.Context, in *GetUserLikedListingsRequestV3, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetUserLikedListingsV34", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) SearchUsersV10(ctx context.Context, in *SearchUsersRequestV1, opts ...grpc.CallOption) (*SearchUsersResponseV1, error) {
	out := new(SearchUsersResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchUsersV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) SearchProductsV10(ctx context.Context, in *SearchProductsRequestV1, opts ...grpc.CallOption) (*SearchProductsResponseV1, error) {
	out := new(SearchProductsResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchProductsV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) InternalSearchListingsV10(ctx context.Context, in *InternalSearchListingsRequestV1, opts ...grpc.CallOption) (*InternalSearchListingsResponseV1, error) {
	out := new(InternalSearchListingsResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/InternalSearchListingsV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetImpulsePurchaseFeedV10(ctx context.Context, in *GetImpulsePurchaseFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetImpulsePurchaseFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetDailyPicksFeedV11(ctx context.Context, in *GetDailyPicksFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetDailyPicksFeedV11", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetYouMayAlsoLikeFeedV11(ctx context.Context, in *GetYouMayAlsoLikeFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetYouMayAlsoLikeFeedV11", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetYouMayAlsoLikeFeedV10(ctx context.Context, in *GetYouMayAlsoLikeFeedRequestV1, opts ...grpc.CallOption) (*GetYouMayAlsoLikeFeedResponseV1, error) {
	out := new(GetYouMayAlsoLikeFeedResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetYouMayAlsoLikeFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetRecommendedForYouFeedV10(ctx context.Context, in *GetRecommendedForYouFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV33, error) {
	out := new(SearchListingsResponseV33)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetRecommendedForYouFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetDroppedInPriceFeedV10(ctx context.Context, in *GetDroppedInPriceFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetDroppedInPriceFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetDailyDiscoveryV10(ctx context.Context, in *GetDailyDiscoveryRequestV1, opts ...grpc.CallOption) (*GetDailyDiscoveryResponseV1, error) {
	out := new(GetDailyDiscoveryResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetDailyDiscoveryV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetDailyDiscoveryListingsV10(ctx context.Context, in *GetDailyDiscoveryListingsRequestV1, opts ...grpc.CallOption) (*GetDailyDiscoveryListingsResponseV1, error) {
	out := new(GetDailyDiscoveryListingsResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetDailyDiscoveryListingsV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetContinueShoppingForFeedV10(ctx context.Context, in *GetContinueShoppingForFeedRequestV1, opts ...grpc.CallOption) (*GetContinueShoppingForFeedResponseV1, error) {
	out := new(GetContinueShoppingForFeedResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetContinueShoppingForFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetTopPicksFeedV10(ctx context.Context, in *GetTopPicksFeedRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetTopPicksFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetEdmListingUrlV10(ctx context.Context, in *GetEdmListingRequestV1, opts ...grpc.CallOption) (*GetEdmListingUrlResponseV1, error) {
	out := new(GetEdmListingUrlResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetEdmListingUrlV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetEdmListingImageV10(ctx context.Context, in *GetEdmListingRequestV1, opts ...grpc.CallOption) (*GetEdmListingImageResponseV1, error) {
	out := new(GetEdmListingImageResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetEdmListingImageV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetEdmListingDescV10(ctx context.Context, in *GetEdmListingRequestV1, opts ...grpc.CallOption) (*GetEdmListingDescResponseV1, error) {
	out := new(GetEdmListingDescResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetEdmListingDescV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetHomeFeedFreeV10(ctx context.Context, in *GetHomeFeedFreeRequestV1, opts ...grpc.CallOption) (*SearchListingsResponseV34, error) {
	out := new(SearchListingsResponseV34)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetHomeFeedFreeV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) SearchCGProductListingsV10(ctx context.Context, in *SearchCGProductListingsRequestV1, opts ...grpc.CallOption) (*SearchCGProductListingsResponseV1, error) {
	out := new(SearchCGProductListingsResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/SearchCGProductListingsV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetCGProductVariantCountsV10(ctx context.Context, in *GetCGProductVariantCountsRequestV1, opts ...grpc.CallOption) (*GetCGProductVariantCountsResponseV1, error) {
	out := new(GetCGProductVariantCountsResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetCGProductVariantCountsV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentFeedServiceClient) GetProductsHomeFeedV10(ctx context.Context, in *GetProductsHomeFeedRequestV1, opts ...grpc.CallOption) (*SearchProductsResponseV1, error) {
	out := new(SearchProductsResponseV1)
	err := c.cc.Invoke(ctx, "/ContentFeedService_proto.ContentFeedService/GetProductsHomeFeedV10", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentFeedServiceServer is the server API for ContentFeedService service.
type ContentFeedServiceServer interface {
	// search
	SearchListingsV40(context.Context, *SearchListingsRequestV4) (*SearchListingsResponseV4, error)
	GetSearchListingsTotalV40(context.Context, *GetSearchListingsTotalRequestV4) (*GetSearchListingsTotalResponseV4, error)
	SearchListingsV34(context.Context, *SearchListingsRequestV3) (*SearchListingsResponseV34, error)
	GetSearchListingsTotalV30(context.Context, *SearchListingsRequestV3) (*GetSearchListingsTotalResponseV3, error)
	SearchSpcListingsV33(context.Context, *SearchSpcListingsRequestV3) (*SearchListingsResponseV33, error)
	SearchProfileListingsV33(context.Context, *SearchProfileListingsRequestV3) (*SearchListingsResponseV33, error)
	SearchFollowingListingsV34(context.Context, *SearchListingsRequestV3) (*SearchListingsResponseV34, error)
	GetMoreFromThisSellerFeedV10(context.Context, *GetMoreFromThisSellerFeedRequestV1) (*SearchListingsResponseV34, error)
	GetHyperlocalFeedV10(context.Context, *GetHyperlocalFeedRequestV1) (*GetHyperlocalFeedResponseV1, error)
	GetHyperlocalFeedV20(context.Context, *GetHyperlocalFeedRequestV2) (*GetHyperlocalFeedResponseV2, error)
	GetUserLikedListingsV34(context.Context, *GetUserLikedListingsRequestV3) (*SearchListingsResponseV34, error)
	// user search
	SearchUsersV10(context.Context, *SearchUsersRequestV1) (*SearchUsersResponseV1, error)
	// product search
	SearchProductsV10(context.Context, *SearchProductsRequestV1) (*SearchProductsResponseV1, error)
	// internal search
	InternalSearchListingsV10(context.Context, *InternalSearchListingsRequestV1) (*InternalSearchListingsResponseV1, error)
	// recommendation
	GetImpulsePurchaseFeedV10(context.Context, *GetImpulsePurchaseFeedRequestV1) (*SearchListingsResponseV34, error)
	GetDailyPicksFeedV11(context.Context, *GetDailyPicksFeedRequestV1) (*SearchListingsResponseV34, error)
	GetYouMayAlsoLikeFeedV11(context.Context, *GetYouMayAlsoLikeFeedRequestV1) (*SearchListingsResponseV34, error)
	GetYouMayAlsoLikeFeedV10(context.Context, *GetYouMayAlsoLikeFeedRequestV1) (*GetYouMayAlsoLikeFeedResponseV1, error)
	GetRecommendedForYouFeedV10(context.Context, *GetRecommendedForYouFeedRequestV1) (*SearchListingsResponseV33, error)
	GetDroppedInPriceFeedV10(context.Context, *GetDroppedInPriceFeedRequestV1) (*SearchListingsResponseV34, error)
	GetDailyDiscoveryV10(context.Context, *GetDailyDiscoveryRequestV1) (*GetDailyDiscoveryResponseV1, error)
	GetDailyDiscoveryListingsV10(context.Context, *GetDailyDiscoveryListingsRequestV1) (*GetDailyDiscoveryListingsResponseV1, error)
	GetContinueShoppingForFeedV10(context.Context, *GetContinueShoppingForFeedRequestV1) (*GetContinueShoppingForFeedResponseV1, error)
	GetTopPicksFeedV10(context.Context, *GetTopPicksFeedRequestV1) (*SearchListingsResponseV34, error)
	GetEdmListingUrlV10(context.Context, *GetEdmListingRequestV1) (*GetEdmListingUrlResponseV1, error)
	GetEdmListingImageV10(context.Context, *GetEdmListingRequestV1) (*GetEdmListingImageResponseV1, error)
	GetEdmListingDescV10(context.Context, *GetEdmListingRequestV1) (*GetEdmListingDescResponseV1, error)
	GetHomeFeedFreeV10(context.Context, *GetHomeFeedFreeRequestV1) (*SearchListingsResponseV34, error)
	SearchCGProductListingsV10(context.Context, *SearchCGProductListingsRequestV1) (*SearchCGProductListingsResponseV1, error)
	GetCGProductVariantCountsV10(context.Context, *GetCGProductVariantCountsRequestV1) (*GetCGProductVariantCountsResponseV1, error)
	// product home feed
	GetProductsHomeFeedV10(context.Context, *GetProductsHomeFeedRequestV1) (*SearchProductsResponseV1, error)
}

// UnimplementedContentFeedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContentFeedServiceServer struct {
}

func (*UnimplementedContentFeedServiceServer) SearchListingsV40(ctx context.Context, req *SearchListingsRequestV4) (*SearchListingsResponseV4, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchListingsV40 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetSearchListingsTotalV40(ctx context.Context, req *GetSearchListingsTotalRequestV4) (*GetSearchListingsTotalResponseV4, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchListingsTotalV40 not implemented")
}
func (*UnimplementedContentFeedServiceServer) SearchListingsV34(ctx context.Context, req *SearchListingsRequestV3) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchListingsV34 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetSearchListingsTotalV30(ctx context.Context, req *SearchListingsRequestV3) (*GetSearchListingsTotalResponseV3, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchListingsTotalV30 not implemented")
}
func (*UnimplementedContentFeedServiceServer) SearchSpcListingsV33(ctx context.Context, req *SearchSpcListingsRequestV3) (*SearchListingsResponseV33, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSpcListingsV33 not implemented")
}
func (*UnimplementedContentFeedServiceServer) SearchProfileListingsV33(ctx context.Context, req *SearchProfileListingsRequestV3) (*SearchListingsResponseV33, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProfileListingsV33 not implemented")
}
func (*UnimplementedContentFeedServiceServer) SearchFollowingListingsV34(ctx context.Context, req *SearchListingsRequestV3) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFollowingListingsV34 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetMoreFromThisSellerFeedV10(ctx context.Context, req *GetMoreFromThisSellerFeedRequestV1) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMoreFromThisSellerFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetHyperlocalFeedV10(ctx context.Context, req *GetHyperlocalFeedRequestV1) (*GetHyperlocalFeedResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHyperlocalFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetHyperlocalFeedV20(ctx context.Context, req *GetHyperlocalFeedRequestV2) (*GetHyperlocalFeedResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHyperlocalFeedV20 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetUserLikedListingsV34(ctx context.Context, req *GetUserLikedListingsRequestV3) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLikedListingsV34 not implemented")
}
func (*UnimplementedContentFeedServiceServer) SearchUsersV10(ctx context.Context, req *SearchUsersRequestV1) (*SearchUsersResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsersV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) SearchProductsV10(ctx context.Context, req *SearchProductsRequestV1) (*SearchProductsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProductsV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) InternalSearchListingsV10(ctx context.Context, req *InternalSearchListingsRequestV1) (*InternalSearchListingsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalSearchListingsV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetImpulsePurchaseFeedV10(ctx context.Context, req *GetImpulsePurchaseFeedRequestV1) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImpulsePurchaseFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetDailyPicksFeedV11(ctx context.Context, req *GetDailyPicksFeedRequestV1) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyPicksFeedV11 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetYouMayAlsoLikeFeedV11(ctx context.Context, req *GetYouMayAlsoLikeFeedRequestV1) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYouMayAlsoLikeFeedV11 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetYouMayAlsoLikeFeedV10(ctx context.Context, req *GetYouMayAlsoLikeFeedRequestV1) (*GetYouMayAlsoLikeFeedResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYouMayAlsoLikeFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetRecommendedForYouFeedV10(ctx context.Context, req *GetRecommendedForYouFeedRequestV1) (*SearchListingsResponseV33, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendedForYouFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetDroppedInPriceFeedV10(ctx context.Context, req *GetDroppedInPriceFeedRequestV1) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDroppedInPriceFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetDailyDiscoveryV10(ctx context.Context, req *GetDailyDiscoveryRequestV1) (*GetDailyDiscoveryResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyDiscoveryV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetDailyDiscoveryListingsV10(ctx context.Context, req *GetDailyDiscoveryListingsRequestV1) (*GetDailyDiscoveryListingsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyDiscoveryListingsV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetContinueShoppingForFeedV10(ctx context.Context, req *GetContinueShoppingForFeedRequestV1) (*GetContinueShoppingForFeedResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContinueShoppingForFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetTopPicksFeedV10(ctx context.Context, req *GetTopPicksFeedRequestV1) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPicksFeedV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetEdmListingUrlV10(ctx context.Context, req *GetEdmListingRequestV1) (*GetEdmListingUrlResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdmListingUrlV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetEdmListingImageV10(ctx context.Context, req *GetEdmListingRequestV1) (*GetEdmListingImageResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdmListingImageV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetEdmListingDescV10(ctx context.Context, req *GetEdmListingRequestV1) (*GetEdmListingDescResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdmListingDescV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetHomeFeedFreeV10(ctx context.Context, req *GetHomeFeedFreeRequestV1) (*SearchListingsResponseV34, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHomeFeedFreeV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) SearchCGProductListingsV10(ctx context.Context, req *SearchCGProductListingsRequestV1) (*SearchCGProductListingsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCGProductListingsV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetCGProductVariantCountsV10(ctx context.Context, req *GetCGProductVariantCountsRequestV1) (*GetCGProductVariantCountsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCGProductVariantCountsV10 not implemented")
}
func (*UnimplementedContentFeedServiceServer) GetProductsHomeFeedV10(ctx context.Context, req *GetProductsHomeFeedRequestV1) (*SearchProductsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsHomeFeedV10 not implemented")
}

func RegisterContentFeedServiceServer(s *grpc.Server, srv ContentFeedServiceServer) {
	s.RegisterService(&_ContentFeedService_serviceDesc, srv)
}

func _ContentFeedService_SearchListingsV40_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchListingsRequestV4)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchListingsV40(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchListingsV40",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchListingsV40(ctx, req.(*SearchListingsRequestV4))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetSearchListingsTotalV40_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSearchListingsTotalRequestV4)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetSearchListingsTotalV40(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetSearchListingsTotalV40",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetSearchListingsTotalV40(ctx, req.(*GetSearchListingsTotalRequestV4))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_SearchListingsV34_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchListingsRequestV3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchListingsV34(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchListingsV34",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchListingsV34(ctx, req.(*SearchListingsRequestV3))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetSearchListingsTotalV30_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchListingsRequestV3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetSearchListingsTotalV30(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetSearchListingsTotalV30",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetSearchListingsTotalV30(ctx, req.(*SearchListingsRequestV3))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_SearchSpcListingsV33_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSpcListingsRequestV3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchSpcListingsV33(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchSpcListingsV33",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchSpcListingsV33(ctx, req.(*SearchSpcListingsRequestV3))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_SearchProfileListingsV33_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProfileListingsRequestV3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchProfileListingsV33(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchProfileListingsV33",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchProfileListingsV33(ctx, req.(*SearchProfileListingsRequestV3))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_SearchFollowingListingsV34_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchListingsRequestV3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchFollowingListingsV34(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchFollowingListingsV34",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchFollowingListingsV34(ctx, req.(*SearchListingsRequestV3))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetMoreFromThisSellerFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMoreFromThisSellerFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetMoreFromThisSellerFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetMoreFromThisSellerFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetMoreFromThisSellerFeedV10(ctx, req.(*GetMoreFromThisSellerFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetHyperlocalFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHyperlocalFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetHyperlocalFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetHyperlocalFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetHyperlocalFeedV10(ctx, req.(*GetHyperlocalFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetHyperlocalFeedV20_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHyperlocalFeedRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetHyperlocalFeedV20(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetHyperlocalFeedV20",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetHyperlocalFeedV20(ctx, req.(*GetHyperlocalFeedRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetUserLikedListingsV34_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLikedListingsRequestV3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetUserLikedListingsV34(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetUserLikedListingsV34",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetUserLikedListingsV34(ctx, req.(*GetUserLikedListingsRequestV3))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_SearchUsersV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchUsersV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchUsersV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchUsersV10(ctx, req.(*SearchUsersRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_SearchProductsV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchProductsV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchProductsV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchProductsV10(ctx, req.(*SearchProductsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_InternalSearchListingsV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalSearchListingsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).InternalSearchListingsV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/InternalSearchListingsV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).InternalSearchListingsV10(ctx, req.(*InternalSearchListingsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetImpulsePurchaseFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImpulsePurchaseFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetImpulsePurchaseFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetImpulsePurchaseFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetImpulsePurchaseFeedV10(ctx, req.(*GetImpulsePurchaseFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetDailyPicksFeedV11_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyPicksFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetDailyPicksFeedV11(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetDailyPicksFeedV11",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetDailyPicksFeedV11(ctx, req.(*GetDailyPicksFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetYouMayAlsoLikeFeedV11_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYouMayAlsoLikeFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetYouMayAlsoLikeFeedV11(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetYouMayAlsoLikeFeedV11",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetYouMayAlsoLikeFeedV11(ctx, req.(*GetYouMayAlsoLikeFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetYouMayAlsoLikeFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYouMayAlsoLikeFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetYouMayAlsoLikeFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetYouMayAlsoLikeFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetYouMayAlsoLikeFeedV10(ctx, req.(*GetYouMayAlsoLikeFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetRecommendedForYouFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendedForYouFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetRecommendedForYouFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetRecommendedForYouFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetRecommendedForYouFeedV10(ctx, req.(*GetRecommendedForYouFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetDroppedInPriceFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDroppedInPriceFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetDroppedInPriceFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetDroppedInPriceFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetDroppedInPriceFeedV10(ctx, req.(*GetDroppedInPriceFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetDailyDiscoveryV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyDiscoveryRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetDailyDiscoveryV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetDailyDiscoveryV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetDailyDiscoveryV10(ctx, req.(*GetDailyDiscoveryRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetDailyDiscoveryListingsV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyDiscoveryListingsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetDailyDiscoveryListingsV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetDailyDiscoveryListingsV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetDailyDiscoveryListingsV10(ctx, req.(*GetDailyDiscoveryListingsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetContinueShoppingForFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContinueShoppingForFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetContinueShoppingForFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetContinueShoppingForFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetContinueShoppingForFeedV10(ctx, req.(*GetContinueShoppingForFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetTopPicksFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopPicksFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetTopPicksFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetTopPicksFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetTopPicksFeedV10(ctx, req.(*GetTopPicksFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetEdmListingUrlV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdmListingRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetEdmListingUrlV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetEdmListingUrlV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetEdmListingUrlV10(ctx, req.(*GetEdmListingRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetEdmListingImageV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdmListingRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetEdmListingImageV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetEdmListingImageV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetEdmListingImageV10(ctx, req.(*GetEdmListingRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetEdmListingDescV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdmListingRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetEdmListingDescV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetEdmListingDescV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetEdmListingDescV10(ctx, req.(*GetEdmListingRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetHomeFeedFreeV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeFeedFreeRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetHomeFeedFreeV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetHomeFeedFreeV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetHomeFeedFreeV10(ctx, req.(*GetHomeFeedFreeRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_SearchCGProductListingsV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCGProductListingsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).SearchCGProductListingsV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/SearchCGProductListingsV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).SearchCGProductListingsV10(ctx, req.(*SearchCGProductListingsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetCGProductVariantCountsV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCGProductVariantCountsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetCGProductVariantCountsV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetCGProductVariantCountsV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetCGProductVariantCountsV10(ctx, req.(*GetCGProductVariantCountsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentFeedService_GetProductsHomeFeedV10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsHomeFeedRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentFeedServiceServer).GetProductsHomeFeedV10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentFeedService_proto.ContentFeedService/GetProductsHomeFeedV10",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentFeedServiceServer).GetProductsHomeFeedV10(ctx, req.(*GetProductsHomeFeedRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContentFeedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ContentFeedService_proto.ContentFeedService",
	HandlerType: (*ContentFeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchListingsV40",
			Handler:    _ContentFeedService_SearchListingsV40_Handler,
		},
		{
			MethodName: "GetSearchListingsTotalV40",
			Handler:    _ContentFeedService_GetSearchListingsTotalV40_Handler,
		},
		{
			MethodName: "SearchListingsV34",
			Handler:    _ContentFeedService_SearchListingsV34_Handler,
		},
		{
			MethodName: "GetSearchListingsTotalV30",
			Handler:    _ContentFeedService_GetSearchListingsTotalV30_Handler,
		},
		{
			MethodName: "SearchSpcListingsV33",
			Handler:    _ContentFeedService_SearchSpcListingsV33_Handler,
		},
		{
			MethodName: "SearchProfileListingsV33",
			Handler:    _ContentFeedService_SearchProfileListingsV33_Handler,
		},
		{
			MethodName: "SearchFollowingListingsV34",
			Handler:    _ContentFeedService_SearchFollowingListingsV34_Handler,
		},
		{
			MethodName: "GetMoreFromThisSellerFeedV10",
			Handler:    _ContentFeedService_GetMoreFromThisSellerFeedV10_Handler,
		},
		{
			MethodName: "GetHyperlocalFeedV10",
			Handler:    _ContentFeedService_GetHyperlocalFeedV10_Handler,
		},
		{
			MethodName: "GetHyperlocalFeedV20",
			Handler:    _ContentFeedService_GetHyperlocalFeedV20_Handler,
		},
		{
			MethodName: "GetUserLikedListingsV34",
			Handler:    _ContentFeedService_GetUserLikedListingsV34_Handler,
		},
		{
			MethodName: "SearchUsersV10",
			Handler:    _ContentFeedService_SearchUsersV10_Handler,
		},
		{
			MethodName: "SearchProductsV10",
			Handler:    _ContentFeedService_SearchProductsV10_Handler,
		},
		{
			MethodName: "InternalSearchListingsV10",
			Handler:    _ContentFeedService_InternalSearchListingsV10_Handler,
		},
		{
			MethodName: "GetImpulsePurchaseFeedV10",
			Handler:    _ContentFeedService_GetImpulsePurchaseFeedV10_Handler,
		},
		{
			MethodName: "GetDailyPicksFeedV11",
			Handler:    _ContentFeedService_GetDailyPicksFeedV11_Handler,
		},
		{
			MethodName: "GetYouMayAlsoLikeFeedV11",
			Handler:    _ContentFeedService_GetYouMayAlsoLikeFeedV11_Handler,
		},
		{
			MethodName: "GetYouMayAlsoLikeFeedV10",
			Handler:    _ContentFeedService_GetYouMayAlsoLikeFeedV10_Handler,
		},
		{
			MethodName: "GetRecommendedForYouFeedV10",
			Handler:    _ContentFeedService_GetRecommendedForYouFeedV10_Handler,
		},
		{
			MethodName: "GetDroppedInPriceFeedV10",
			Handler:    _ContentFeedService_GetDroppedInPriceFeedV10_Handler,
		},
		{
			MethodName: "GetDailyDiscoveryV10",
			Handler:    _ContentFeedService_GetDailyDiscoveryV10_Handler,
		},
		{
			MethodName: "GetDailyDiscoveryListingsV10",
			Handler:    _ContentFeedService_GetDailyDiscoveryListingsV10_Handler,
		},
		{
			MethodName: "GetContinueShoppingForFeedV10",
			Handler:    _ContentFeedService_GetContinueShoppingForFeedV10_Handler,
		},
		{
			MethodName: "GetTopPicksFeedV10",
			Handler:    _ContentFeedService_GetTopPicksFeedV10_Handler,
		},
		{
			MethodName: "GetEdmListingUrlV10",
			Handler:    _ContentFeedService_GetEdmListingUrlV10_Handler,
		},
		{
			MethodName: "GetEdmListingImageV10",
			Handler:    _ContentFeedService_GetEdmListingImageV10_Handler,
		},
		{
			MethodName: "GetEdmListingDescV10",
			Handler:    _ContentFeedService_GetEdmListingDescV10_Handler,
		},
		{
			MethodName: "GetHomeFeedFreeV10",
			Handler:    _ContentFeedService_GetHomeFeedFreeV10_Handler,
		},
		{
			MethodName: "SearchCGProductListingsV10",
			Handler:    _ContentFeedService_SearchCGProductListingsV10_Handler,
		},
		{
			MethodName: "GetCGProductVariantCountsV10",
			Handler:    _ContentFeedService_GetCGProductVariantCountsV10_Handler,
		},
		{
			MethodName: "GetProductsHomeFeedV10",
			Handler:    _ContentFeedService_GetProductsHomeFeedV10_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content-feed/contentfeed.proto",
}
