// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content-feed/group.proto

package ContentFeedService_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupPostCollection_Post_Type int32

const (
	GroupPostCollection_Post_Text GroupPostCollection_Post_Type = 0
)

var GroupPostCollection_Post_Type_name = map[int32]string{
	0: "Text",
}

var GroupPostCollection_Post_Type_value = map[string]int32{
	"Text": 0,
}

func (x GroupPostCollection_Post_Type) String() string {
	return proto.EnumName(GroupPostCollection_Post_Type_name, int32(x))
}

func (GroupPostCollection_Post_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 0, 0}
}

type GroupPostCollection_Post_Status int32

const (
	GroupPostCollection_Post_Published GroupPostCollection_Post_Status = 0
	GroupPostCollection_Post_Deleted   GroupPostCollection_Post_Status = 1
	GroupPostCollection_Post_Hidden    GroupPostCollection_Post_Status = 2
)

var GroupPostCollection_Post_Status_name = map[int32]string{
	0: "Published",
	1: "Deleted",
	2: "Hidden",
}

var GroupPostCollection_Post_Status_value = map[string]int32{
	"Published": 0,
	"Deleted":   1,
	"Hidden":    2,
}

func (x GroupPostCollection_Post_Status) String() string {
	return proto.EnumName(GroupPostCollection_Post_Status_name, int32(x))
}

func (GroupPostCollection_Post_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 0, 1}
}

type GroupPostCollection_Comment_Type int32

const (
	GroupPostCollection_Comment_Text  GroupPostCollection_Comment_Type = 0
	GroupPostCollection_Comment_Image GroupPostCollection_Comment_Type = 1
)

var GroupPostCollection_Comment_Type_name = map[int32]string{
	0: "Text",
	1: "Image",
}

var GroupPostCollection_Comment_Type_value = map[string]int32{
	"Text":  0,
	"Image": 1,
}

func (x GroupPostCollection_Comment_Type) String() string {
	return proto.EnumName(GroupPostCollection_Comment_Type_name, int32(x))
}

func (GroupPostCollection_Comment_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 1, 0}
}

type GroupPostCollection_Comment_Status int32

const (
	GroupPostCollection_Comment_Published GroupPostCollection_Comment_Status = 0
	GroupPostCollection_Comment_Deleted   GroupPostCollection_Comment_Status = 1
	GroupPostCollection_Comment_Hidden    GroupPostCollection_Comment_Status = 2
)

var GroupPostCollection_Comment_Status_name = map[int32]string{
	0: "Published",
	1: "Deleted",
	2: "Hidden",
}

var GroupPostCollection_Comment_Status_value = map[string]int32{
	"Published": 0,
	"Deleted":   1,
	"Hidden":    2,
}

func (x GroupPostCollection_Comment_Status) String() string {
	return proto.EnumName(GroupPostCollection_Comment_Status_name, int32(x))
}

func (GroupPostCollection_Comment_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 1, 1}
}

type GroupPostCollection_Attachment_Type int32

const (
	GroupPostCollection_Attachment_Unknown GroupPostCollection_Attachment_Type = 0
	GroupPostCollection_Attachment_Image   GroupPostCollection_Attachment_Type = 1
)

var GroupPostCollection_Attachment_Type_name = map[int32]string{
	0: "Unknown",
	1: "Image",
}

var GroupPostCollection_Attachment_Type_value = map[string]int32{
	"Unknown": 0,
	"Image":   1,
}

func (x GroupPostCollection_Attachment_Type) String() string {
	return proto.EnumName(GroupPostCollection_Attachment_Type_name, int32(x))
}

func (GroupPostCollection_Attachment_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 3, 0}
}

// GroupPostCollection is a horizontal component containing an array of group post search results
type GroupPostCollection struct {
	Posts                []*GroupPostCollection_Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GroupPostCollection) Reset()         { *m = GroupPostCollection{} }
func (m *GroupPostCollection) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection) ProtoMessage()    {}
func (*GroupPostCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0}
}

func (m *GroupPostCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection.Unmarshal(m, b)
}
func (m *GroupPostCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection.Merge(m, src)
}
func (m *GroupPostCollection) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection.Size(m)
}
func (m *GroupPostCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection proto.InternalMessageInfo

func (m *GroupPostCollection) GetPosts() []*GroupPostCollection_Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type GroupPostCollection_Post struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// string group_id = 2;
	// string user_id = 3;
	// Type post_type = 4;
	// Status status = 5;
	Title   string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	// int64 pinned = 8;
	Comments      []*GroupPostCollection_Comment `protobuf:"bytes,9,rep,name=comments,proto3" json:"comments,omitempty"`
	CommentsCount int64                          `protobuf:"varint,10,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	UpVotesCount  int64                          `protobuf:"varint,11,opt,name=up_votes_count,json=upVotesCount,proto3" json:"up_votes_count,omitempty"`
	// int64 vote_status = 12;
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// google.protobuf.Timestamp updated_at = 14;
	// google.protobuf.Timestamp deleted_at = 15;
	// google.protobuf.Timestamp last_edited_at = 16;
	User                 *GroupPostCollection_User         `protobuf:"bytes,17,opt,name=user,proto3" json:"user,omitempty"`
	Attachments          []*GroupPostCollection_Attachment `protobuf:"bytes,18,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Group                *GroupPostCollection_Group        `protobuf:"bytes,19,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GroupPostCollection_Post) Reset()         { *m = GroupPostCollection_Post{} }
func (m *GroupPostCollection_Post) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection_Post) ProtoMessage()    {}
func (*GroupPostCollection_Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 0}
}

func (m *GroupPostCollection_Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection_Post.Unmarshal(m, b)
}
func (m *GroupPostCollection_Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection_Post.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection_Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection_Post.Merge(m, src)
}
func (m *GroupPostCollection_Post) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection_Post.Size(m)
}
func (m *GroupPostCollection_Post) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection_Post.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection_Post proto.InternalMessageInfo

func (m *GroupPostCollection_Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupPostCollection_Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GroupPostCollection_Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *GroupPostCollection_Post) GetComments() []*GroupPostCollection_Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *GroupPostCollection_Post) GetCommentsCount() int64 {
	if m != nil {
		return m.CommentsCount
	}
	return 0
}

func (m *GroupPostCollection_Post) GetUpVotesCount() int64 {
	if m != nil {
		return m.UpVotesCount
	}
	return 0
}

func (m *GroupPostCollection_Post) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GroupPostCollection_Post) GetUser() *GroupPostCollection_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GroupPostCollection_Post) GetAttachments() []*GroupPostCollection_Attachment {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *GroupPostCollection_Post) GetGroup() *GroupPostCollection_Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupPostCollection_Comment struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// string post_id = 2;
	// string user_id = 3;
	// Type type = 4;
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// Status status = 6;
	// google.protobuf.Timestamp created_at = 7;
	// google.protobuf.Timestamp updated_at = 8;
	// google.protobuf.Timestamp last_edited_at = 9;
	// google.protobuf.Timestamp deleted_at = 10;
	User                 *GroupPostCollection_User `protobuf:"bytes,11,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GroupPostCollection_Comment) Reset()         { *m = GroupPostCollection_Comment{} }
func (m *GroupPostCollection_Comment) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection_Comment) ProtoMessage()    {}
func (*GroupPostCollection_Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 1}
}

func (m *GroupPostCollection_Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection_Comment.Unmarshal(m, b)
}
func (m *GroupPostCollection_Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection_Comment.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection_Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection_Comment.Merge(m, src)
}
func (m *GroupPostCollection_Comment) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection_Comment.Size(m)
}
func (m *GroupPostCollection_Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection_Comment proto.InternalMessageInfo

func (m *GroupPostCollection_Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupPostCollection_Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *GroupPostCollection_Comment) GetUser() *GroupPostCollection_User {
	if m != nil {
		return m.User
	}
	return nil
}

type GroupPostCollection_Group struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ImageSmallUrl        string   `protobuf:"bytes,4,opt,name=image_small_url,json=imageSmallUrl,proto3" json:"image_small_url,omitempty"`
	ImageMediumUrl       string   `protobuf:"bytes,5,opt,name=image_medium_url,json=imageMediumUrl,proto3" json:"image_medium_url,omitempty"`
	ImageLargeUrl        string   `protobuf:"bytes,6,opt,name=image_large_url,json=imageLargeUrl,proto3" json:"image_large_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupPostCollection_Group) Reset()         { *m = GroupPostCollection_Group{} }
func (m *GroupPostCollection_Group) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection_Group) ProtoMessage()    {}
func (*GroupPostCollection_Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 2}
}

func (m *GroupPostCollection_Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection_Group.Unmarshal(m, b)
}
func (m *GroupPostCollection_Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection_Group.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection_Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection_Group.Merge(m, src)
}
func (m *GroupPostCollection_Group) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection_Group.Size(m)
}
func (m *GroupPostCollection_Group) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection_Group.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection_Group proto.InternalMessageInfo

func (m *GroupPostCollection_Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupPostCollection_Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupPostCollection_Group) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *GroupPostCollection_Group) GetImageSmallUrl() string {
	if m != nil {
		return m.ImageSmallUrl
	}
	return ""
}

func (m *GroupPostCollection_Group) GetImageMediumUrl() string {
	if m != nil {
		return m.ImageMediumUrl
	}
	return ""
}

func (m *GroupPostCollection_Group) GetImageLargeUrl() string {
	if m != nil {
		return m.ImageLargeUrl
	}
	return ""
}

type GroupPostCollection_Attachment struct {
	Id                   string                                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attribute            *GroupPostCollection_Attachment_Attribute `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Type                 GroupPostCollection_Attachment_Type       `protobuf:"varint,3,opt,name=type,proto3,enum=ContentFeedService_proto.GroupPostCollection_Attachment_Type" json:"type,omitempty"`
	Position             int64                                     `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	UserId               string                                    `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp                      `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp                      `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *GroupPostCollection_Attachment) Reset()         { *m = GroupPostCollection_Attachment{} }
func (m *GroupPostCollection_Attachment) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection_Attachment) ProtoMessage()    {}
func (*GroupPostCollection_Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 3}
}

func (m *GroupPostCollection_Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection_Attachment.Unmarshal(m, b)
}
func (m *GroupPostCollection_Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection_Attachment.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection_Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection_Attachment.Merge(m, src)
}
func (m *GroupPostCollection_Attachment) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection_Attachment.Size(m)
}
func (m *GroupPostCollection_Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection_Attachment proto.InternalMessageInfo

func (m *GroupPostCollection_Attachment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupPostCollection_Attachment) GetAttribute() *GroupPostCollection_Attachment_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *GroupPostCollection_Attachment) GetType() GroupPostCollection_Attachment_Type {
	if m != nil {
		return m.Type
	}
	return GroupPostCollection_Attachment_Unknown
}

func (m *GroupPostCollection_Attachment) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *GroupPostCollection_Attachment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GroupPostCollection_Attachment) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GroupPostCollection_Attachment) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GroupPostCollection_Attachment_Attribute struct {
	Url                             string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ImageProgressiveUrl             string   `protobuf:"bytes,2,opt,name=image_progressive_url,json=imageProgressiveUrl,proto3" json:"image_progressive_url,omitempty"`
	ImageProgressiveLowRange        int32    `protobuf:"varint,3,opt,name=image_progressive_low_range,json=imageProgressiveLowRange,proto3" json:"image_progressive_low_range,omitempty"`
	ImageProgressiveMediumRange     int32    `protobuf:"varint,4,opt,name=image_progressive_medium_range,json=imageProgressiveMediumRange,proto3" json:"image_progressive_medium_range,omitempty"`
	ThumbnailProgressiveUrl         string   `protobuf:"bytes,5,opt,name=thumbnail_progressive_url,json=thumbnailProgressiveUrl,proto3" json:"thumbnail_progressive_url,omitempty"`
	ThumbnailProgressiveLowRange    int32    `protobuf:"varint,6,opt,name=thumbnail_progressive_low_range,json=thumbnailProgressiveLowRange,proto3" json:"thumbnail_progressive_low_range,omitempty"`
	ThumbnailProgressiveMediumRange int32    `protobuf:"varint,7,opt,name=thumbnail_progressive_medium_range,json=thumbnailProgressiveMediumRange,proto3" json:"thumbnail_progressive_medium_range,omitempty"`
	ThumbnailUrl                    string   `protobuf:"bytes,8,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *GroupPostCollection_Attachment_Attribute) Reset() {
	*m = GroupPostCollection_Attachment_Attribute{}
}
func (m *GroupPostCollection_Attachment_Attribute) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection_Attachment_Attribute) ProtoMessage()    {}
func (*GroupPostCollection_Attachment_Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 3, 0}
}

func (m *GroupPostCollection_Attachment_Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection_Attachment_Attribute.Unmarshal(m, b)
}
func (m *GroupPostCollection_Attachment_Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection_Attachment_Attribute.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection_Attachment_Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection_Attachment_Attribute.Merge(m, src)
}
func (m *GroupPostCollection_Attachment_Attribute) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection_Attachment_Attribute.Size(m)
}
func (m *GroupPostCollection_Attachment_Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection_Attachment_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection_Attachment_Attribute proto.InternalMessageInfo

func (m *GroupPostCollection_Attachment_Attribute) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GroupPostCollection_Attachment_Attribute) GetImageProgressiveUrl() string {
	if m != nil {
		return m.ImageProgressiveUrl
	}
	return ""
}

func (m *GroupPostCollection_Attachment_Attribute) GetImageProgressiveLowRange() int32 {
	if m != nil {
		return m.ImageProgressiveLowRange
	}
	return 0
}

func (m *GroupPostCollection_Attachment_Attribute) GetImageProgressiveMediumRange() int32 {
	if m != nil {
		return m.ImageProgressiveMediumRange
	}
	return 0
}

func (m *GroupPostCollection_Attachment_Attribute) GetThumbnailProgressiveUrl() string {
	if m != nil {
		return m.ThumbnailProgressiveUrl
	}
	return ""
}

func (m *GroupPostCollection_Attachment_Attribute) GetThumbnailProgressiveLowRange() int32 {
	if m != nil {
		return m.ThumbnailProgressiveLowRange
	}
	return 0
}

func (m *GroupPostCollection_Attachment_Attribute) GetThumbnailProgressiveMediumRange() int32 {
	if m != nil {
		return m.ThumbnailProgressiveMediumRange
	}
	return 0
}

func (m *GroupPostCollection_Attachment_Attribute) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

type GroupPostCollection_User struct {
	Username             string                           `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Profile              *GroupPostCollection_UserProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Id                   string                           `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GroupPostCollection_User) Reset()         { *m = GroupPostCollection_User{} }
func (m *GroupPostCollection_User) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection_User) ProtoMessage()    {}
func (*GroupPostCollection_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 4}
}

func (m *GroupPostCollection_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection_User.Unmarshal(m, b)
}
func (m *GroupPostCollection_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection_User.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection_User.Merge(m, src)
}
func (m *GroupPostCollection_User) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection_User.Size(m)
}
func (m *GroupPostCollection_User) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection_User.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection_User proto.InternalMessageInfo

func (m *GroupPostCollection_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GroupPostCollection_User) GetProfile() *GroupPostCollection_UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *GroupPostCollection_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GroupPostCollection_UserProfile struct {
	ImageUrl             string   `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupPostCollection_UserProfile) Reset()         { *m = GroupPostCollection_UserProfile{} }
func (m *GroupPostCollection_UserProfile) String() string { return proto.CompactTextString(m) }
func (*GroupPostCollection_UserProfile) ProtoMessage()    {}
func (*GroupPostCollection_UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f899013dfcc7c36, []int{0, 5}
}

func (m *GroupPostCollection_UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPostCollection_UserProfile.Unmarshal(m, b)
}
func (m *GroupPostCollection_UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPostCollection_UserProfile.Marshal(b, m, deterministic)
}
func (m *GroupPostCollection_UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPostCollection_UserProfile.Merge(m, src)
}
func (m *GroupPostCollection_UserProfile) XXX_Size() int {
	return xxx_messageInfo_GroupPostCollection_UserProfile.Size(m)
}
func (m *GroupPostCollection_UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPostCollection_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPostCollection_UserProfile proto.InternalMessageInfo

func (m *GroupPostCollection_UserProfile) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("ContentFeedService_proto.GroupPostCollection_Post_Type", GroupPostCollection_Post_Type_name, GroupPostCollection_Post_Type_value)
	proto.RegisterEnum("ContentFeedService_proto.GroupPostCollection_Post_Status", GroupPostCollection_Post_Status_name, GroupPostCollection_Post_Status_value)
	proto.RegisterEnum("ContentFeedService_proto.GroupPostCollection_Comment_Type", GroupPostCollection_Comment_Type_name, GroupPostCollection_Comment_Type_value)
	proto.RegisterEnum("ContentFeedService_proto.GroupPostCollection_Comment_Status", GroupPostCollection_Comment_Status_name, GroupPostCollection_Comment_Status_value)
	proto.RegisterEnum("ContentFeedService_proto.GroupPostCollection_Attachment_Type", GroupPostCollection_Attachment_Type_name, GroupPostCollection_Attachment_Type_value)
	proto.RegisterType((*GroupPostCollection)(nil), "ContentFeedService_proto.GroupPostCollection")
	proto.RegisterType((*GroupPostCollection_Post)(nil), "ContentFeedService_proto.GroupPostCollection.Post")
	proto.RegisterType((*GroupPostCollection_Comment)(nil), "ContentFeedService_proto.GroupPostCollection.Comment")
	proto.RegisterType((*GroupPostCollection_Group)(nil), "ContentFeedService_proto.GroupPostCollection.Group")
	proto.RegisterType((*GroupPostCollection_Attachment)(nil), "ContentFeedService_proto.GroupPostCollection.Attachment")
	proto.RegisterType((*GroupPostCollection_Attachment_Attribute)(nil), "ContentFeedService_proto.GroupPostCollection.Attachment.Attribute")
	proto.RegisterType((*GroupPostCollection_User)(nil), "ContentFeedService_proto.GroupPostCollection.User")
	proto.RegisterType((*GroupPostCollection_UserProfile)(nil), "ContentFeedService_proto.GroupPostCollection.UserProfile")
}

func init() { proto.RegisterFile("content-feed/group.proto", fileDescriptor_4f899013dfcc7c36) }

var fileDescriptor_4f899013dfcc7c36 = []byte{
	// 1071 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xdb, 0x46,
	0x13, 0x8d, 0xa4, 0x15, 0x45, 0x0e, 0x23, 0x79, 0xb3, 0x4e, 0x10, 0x7e, 0xf2, 0x87, 0xd8, 0x50,
	0x7f, 0xe0, 0x9b, 0x48, 0x85, 0x82, 0x02, 0x75, 0x0b, 0x5f, 0x38, 0x6a, 0xdd, 0x98, 0x4d, 0x0b,
	0x87, 0xb6, 0x7a, 0x11, 0x14, 0x50, 0x29, 0x71, 0x2d, 0x11, 0x59, 0x72, 0x09, 0x72, 0x69, 0x37,
	0x4f, 0xd0, 0x67, 0x6a, 0x9f, 0xa0, 0xe8, 0x9b, 0xf4, 0xba, 0x0f, 0xd0, 0x62, 0x77, 0x49, 0x89,
	0xb2, 0x1c, 0x14, 0x4a, 0x7b, 0xc7, 0x3d, 0x3b, 0x73, 0x34, 0x73, 0xe6, 0xec, 0x40, 0xe0, 0xcc,
	0x78, 0x2c, 0x68, 0x2c, 0x9e, 0x5e, 0x51, 0x1a, 0x0c, 0xe6, 0x29, 0xcf, 0x93, 0x7e, 0x92, 0x72,
	0xc1, 0x89, 0x33, 0xd2, 0x37, 0xa7, 0x94, 0x06, 0x17, 0x34, 0xbd, 0x0e, 0x67, 0x74, 0xa2, 0x6e,
	0xba, 0xfb, 0x73, 0xce, 0xe7, 0x8c, 0x0e, 0xd4, 0x69, 0x9a, 0x5f, 0x0d, 0x44, 0x18, 0xd1, 0x4c,
	0xf8, 0x51, 0x91, 0xda, 0xfb, 0x6d, 0x17, 0x76, 0xbf, 0x96, 0x54, 0xe7, 0x3c, 0x13, 0x23, 0xce,
	0x18, 0x9d, 0x89, 0x90, 0xc7, 0xe4, 0x05, 0x34, 0x13, 0x9e, 0x89, 0xcc, 0xa9, 0x1d, 0x34, 0x0e,
	0xed, 0xe1, 0xb0, 0xff, 0xae, 0x9f, 0xe8, 0xdf, 0x91, 0xdd, 0x97, 0x47, 0x4f, 0x13, 0x74, 0xff,
	0x6a, 0x02, 0x92, 0x67, 0xd2, 0x81, 0x7a, 0x18, 0x38, 0xb5, 0x83, 0xda, 0xa1, 0xe5, 0xd5, 0xc3,
	0x80, 0x3c, 0x84, 0xa6, 0x08, 0x05, 0xa3, 0x8e, 0xa1, 0x20, 0x7d, 0x20, 0x0e, 0xb4, 0x8a, 0x3e,
	0x9d, 0x96, 0xc2, 0xcb, 0x23, 0x79, 0x05, 0xe6, 0x8c, 0x47, 0x11, 0x8d, 0x45, 0xe6, 0x58, 0xaa,
	0xaa, 0x4f, 0xb7, 0xab, 0x6a, 0xa4, 0xb3, 0xbd, 0x25, 0x0d, 0xf9, 0x08, 0x3a, 0xe5, 0xf7, 0x64,
	0xc6, 0xf3, 0x58, 0x38, 0x70, 0x50, 0x3b, 0x6c, 0x78, 0xed, 0x12, 0x1d, 0x49, 0x90, 0x7c, 0x08,
	0x9d, 0x3c, 0x99, 0x5c, 0x73, 0x41, 0xcb, 0x30, 0x5b, 0x85, 0xdd, 0xcf, 0x93, 0xef, 0x25, 0xa8,
	0xa3, 0x8e, 0x00, 0x66, 0x29, 0xf5, 0x05, 0x0d, 0x26, 0xbe, 0x70, 0xda, 0x07, 0xb5, 0x43, 0x7b,
	0xd8, 0xed, 0xeb, 0x01, 0xf4, 0xcb, 0x01, 0xf4, 0x2f, 0xcb, 0x01, 0x78, 0x56, 0x11, 0x7d, 0x22,
	0xc8, 0x29, 0xa0, 0x3c, 0xa3, 0xa9, 0xf3, 0x40, 0x25, 0x6d, 0x29, 0xf6, 0x38, 0xa3, 0xa9, 0xa7,
	0xf2, 0xc9, 0x6b, 0xb0, 0x7d, 0x21, 0xfc, 0xd9, 0x42, 0xab, 0x44, 0x94, 0x4a, 0x9f, 0x6d, 0x47,
	0x77, 0xb2, 0x24, 0xf0, 0xaa, 0x64, 0xe4, 0x0c, 0x9a, 0xca, 0x73, 0xce, 0xae, 0x2a, 0xf2, 0xd9,
	0x76, 0xac, 0x0a, 0xf3, 0x34, 0x43, 0x0f, 0x03, 0xba, 0x7c, 0x9b, 0x50, 0x62, 0x02, 0xba, 0xa4,
	0x3f, 0x09, 0x7c, 0xaf, 0xf7, 0x09, 0x18, 0x17, 0xc2, 0x17, 0x79, 0x46, 0xda, 0x60, 0x9d, 0xe7,
	0x53, 0x16, 0x66, 0x0b, 0x1a, 0xe0, 0x7b, 0xc4, 0x86, 0xd6, 0x97, 0x94, 0x51, 0x41, 0x03, 0x5c,
	0x23, 0x00, 0xc6, 0x8b, 0x30, 0x08, 0x68, 0x8c, 0xeb, 0x2e, 0x32, 0xeb, 0xb8, 0xe1, 0x22, 0xb3,
	0x81, 0x91, 0x8b, 0x4c, 0x84, 0x9b, 0x2e, 0x32, 0x9b, 0xd8, 0x70, 0x91, 0x69, 0x62, 0xcb, 0x45,
	0xe6, 0x7d, 0xdc, 0x76, 0x91, 0xd9, 0xc1, 0x3b, 0x2e, 0x32, 0x77, 0x30, 0x76, 0x91, 0x89, 0xf1,
	0x03, 0x17, 0x99, 0x0f, 0xf1, 0x23, 0xcf, 0x54, 0x65, 0x4c, 0xc2, 0xc0, 0x6b, 0x49, 0xd9, 0xe4,
	0x87, 0x25, 0xcd, 0x3a, 0x11, 0x6f, 0x13, 0xea, 0x19, 0x99, 0xaa, 0xc4, 0x33, 0x92, 0x30, 0x8e,
	0x69, 0xe0, 0xd9, 0x72, 0xf0, 0x93, 0x02, 0x84, 0x3c, 0x09, 0x8a, 0x11, 0x7b, 0x10, 0xe8, 0xca,
	0xe4, 0x77, 0x87, 0xf9, 0x99, 0x98, 0xd0, 0x20, 0x2c, 0xef, 0x22, 0x1a, 0x4d, 0x69, 0x9a, 0x2d,
	0xc2, 0xa4, 0xfb, 0x67, 0x1d, 0x5a, 0x85, 0xf7, 0x36, 0x1e, 0x41, 0xc5, 0xee, 0xcd, 0x75, 0xbb,
	0x97, 0x9e, 0xb0, 0xff, 0x9d, 0x27, 0x7a, 0x7b, 0xb7, 0xc5, 0x26, 0x16, 0x34, 0xcf, 0x22, 0x7f,
	0x4e, 0x71, 0xed, 0x3f, 0xd2, 0xdd, 0xc0, 0x2d, 0x17, 0x99, 0x2d, 0x6c, 0x2e, 0xd5, 0xb7, 0x30,
	0xb8, 0xc8, 0x04, 0x6c, 0x2f, 0x27, 0xd1, 0xc6, 0x1d, 0xaf, 0xa5, 0x44, 0xae, 0xca, 0x8e, 0xd6,
	0x14, 0xaf, 0xbc, 0x9f, 0x35, 0xa1, 0x37, 0xc4, 0xad, 0x08, 0x5f, 0x11, 0x7a, 0xcd, 0xaf, 0xdd,
	0x5f, 0x6a, 0xd0, 0x54, 0xd2, 0x6c, 0x68, 0x4e, 0x00, 0xc5, 0x7e, 0x44, 0x9d, 0xba, 0x42, 0xd4,
	0xb7, 0xc4, 0x32, 0x96, 0xcf, 0x9d, 0x86, 0xc6, 0xe4, 0x37, 0xf9, 0x18, 0x76, 0x42, 0xa9, 0xd3,
	0x24, 0x8b, 0x7c, 0xc6, 0x26, 0x79, 0xca, 0x1c, 0xa4, 0xae, 0xdb, 0x0a, 0xbe, 0x90, 0xe8, 0x38,
	0x65, 0xe4, 0x10, 0xb0, 0x8e, 0x8b, 0x68, 0x10, 0xe6, 0x91, 0x0a, 0xd4, 0xc3, 0xec, 0x28, 0xfc,
	0x5b, 0x05, 0xcb, 0xc8, 0x25, 0x23, 0xf3, 0xd3, 0x39, 0x55, 0x81, 0x46, 0x85, 0xf1, 0xa5, 0x44,
	0xc7, 0x29, 0xeb, 0xfe, 0x61, 0x00, 0xac, 0xde, 0xe1, 0x46, 0x03, 0x3f, 0x82, 0xe5, 0x0b, 0x91,
	0x86, 0xd3, 0x5c, 0xe8, 0x2e, 0xec, 0xe1, 0xf3, 0xf7, 0x7d, 0xe4, 0xf2, 0x53, 0x33, 0x79, 0x2b,
	0x52, 0xf2, 0x0a, 0xd4, 0x64, 0x94, 0x1c, 0x9d, 0xe1, 0xf1, 0x7b, 0x93, 0x4b, 0xe7, 0xe9, 0x21,
	0x93, 0x2e, 0x98, 0x09, 0xcf, 0x42, 0x19, 0xa1, 0x9a, 0x6e, 0x78, 0xcb, 0x33, 0x79, 0x0c, 0xa5,
	0x23, 0x8a, 0xa5, 0x6f, 0xc8, 0xe3, 0x59, 0x70, 0x6b, 0xa7, 0xa2, 0x6d, 0x76, 0xea, 0x11, 0x54,
	0x2c, 0xa4, 0xe6, 0xf1, 0x0f, 0xa9, 0x45, 0xf4, 0x89, 0xe8, 0xfe, 0xde, 0x00, 0x6b, 0x29, 0x0b,
	0xc1, 0xd0, 0x90, 0x83, 0xd2, 0xf2, 0xcb, 0x4f, 0x32, 0x84, 0x47, 0x7a, 0x8c, 0x49, 0xca, 0xe7,
	0x29, 0xcd, 0xb2, 0xf0, 0x5a, 0x0f, 0x53, 0x3b, 0x6a, 0x57, 0x5d, 0x9e, 0xaf, 0xee, 0xe4, 0xe8,
	0x8f, 0x61, 0x6f, 0x33, 0x87, 0xf1, 0x9b, 0x49, 0xea, 0xc7, 0x73, 0x2d, 0x74, 0xd3, 0x73, 0x6e,
	0x67, 0xbe, 0xe4, 0x37, 0x9e, 0xbc, 0x27, 0x23, 0x78, 0xb2, 0x99, 0x5e, 0xf8, 0x4d, 0x33, 0x20,
	0xc5, 0xb0, 0x77, 0x9b, 0x41, 0x9b, 0x4f, 0x93, 0x7c, 0x0e, 0xff, 0x13, 0x8b, 0x3c, 0x9a, 0xc6,
	0x7e, 0xc8, 0x36, 0x6a, 0xd7, 0x8e, 0x7d, 0xbc, 0x0c, 0xb8, 0x55, 0xff, 0x57, 0xb0, 0x7f, 0x77,
	0xee, 0xaa, 0x07, 0x43, 0x55, 0xf0, 0xff, 0xbb, 0x18, 0x96, 0x7d, 0x7c, 0x03, 0xbd, 0xbb, 0x69,
	0xd6, 0x7a, 0x69, 0x29, 0xa6, 0xfd, 0xbb, 0x98, 0xaa, 0xfd, 0x7c, 0x00, 0xed, 0x15, 0x99, 0xec,
	0xc1, 0x54, 0x3d, 0xdc, 0x5f, 0x82, 0xe3, 0x94, 0xf5, 0x9e, 0x14, 0xfb, 0xcf, 0x86, 0xd6, 0x38,
	0x7e, 0x13, 0xf3, 0x9b, 0x78, 0x6d, 0x05, 0x76, 0x7f, 0xae, 0x01, 0x92, 0xeb, 0x52, 0x1a, 0x54,
	0xba, 0x4e, 0xad, 0x06, 0x3d, 0xec, 0xe5, 0x99, 0x5c, 0x40, 0x2b, 0x49, 0xf9, 0x55, 0xc8, 0xca,
	0xf7, 0x76, 0xb4, 0xfd, 0x3e, 0x3e, 0xd7, 0x04, 0x5e, 0xc9, 0x54, 0x3c, 0xeb, 0x46, 0xf9, 0xac,
	0xbb, 0xc7, 0x60, 0x57, 0xe2, 0xc8, 0x1e, 0x58, 0x7a, 0xe4, 0x2b, 0xf7, 0x99, 0x0a, 0x18, 0xa7,
	0x4c, 0xaf, 0x61, 0xcf, 0x8e, 0xfc, 0xf4, 0x0d, 0x15, 0x09, 0xf3, 0x67, 0xf4, 0xf9, 0x0f, 0xaf,
	0xbf, 0x9b, 0x87, 0x62, 0x91, 0x4f, 0xfb, 0x33, 0x1e, 0x0d, 0x66, 0x7e, 0xca, 0xf3, 0x8c, 0x32,
	0x36, 0xc8, 0x16, 0x7e, 0x4a, 0x83, 0xa7, 0xaa, 0xb8, 0xc1, 0x9c, 0xc6, 0x83, 0x39, 0x1f, 0x54,
	0xff, 0x4a, 0x7e, 0xf1, 0xae, 0x4e, 0x7e, 0xad, 0x5b, 0xa3, 0xd3, 0x02, 0x99, 0x1a, 0x0a, 0x7a,
	0xf6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x46, 0x78, 0x66, 0x86, 0x0a, 0x00, 0x00,
}
