// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content-feed/product_search.proto

package ContentFeedService_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchProductsRequestV1 struct {
	AuthUserContainer *AuthUserContainer                     `protobuf:"bytes,1,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	Count             *wrappers.Int32Value                   `protobuf:"bytes,2,opt,name=count,proto3" json:"count,omitempty"`
	Session           *wrappers.StringValue                  `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	CountryId         *wrappers.Int64Value                   `protobuf:"bytes,4,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Query             *QueryParamV4                          `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Filters           []*FilterParamV4                       `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
	UiInfoOptions     *SearchProductsRequestV1_UIInfoOptions `protobuf:"bytes,7,opt,name=ui_info_options,json=uiInfoOptions,proto3" json:"ui_info_options,omitempty"`
	// Internal use
	IncludeDebuggingInfo bool     `protobuf:"varint,15,opt,name=include_debugging_info,json=includeDebuggingInfo,proto3" json:"include_debugging_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsRequestV1) Reset()         { *m = SearchProductsRequestV1{} }
func (m *SearchProductsRequestV1) String() string { return proto.CompactTextString(m) }
func (*SearchProductsRequestV1) ProtoMessage()    {}
func (*SearchProductsRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{0}
}

func (m *SearchProductsRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsRequestV1.Unmarshal(m, b)
}
func (m *SearchProductsRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsRequestV1.Marshal(b, m, deterministic)
}
func (m *SearchProductsRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsRequestV1.Merge(m, src)
}
func (m *SearchProductsRequestV1) XXX_Size() int {
	return xxx_messageInfo_SearchProductsRequestV1.Size(m)
}
func (m *SearchProductsRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsRequestV1 proto.InternalMessageInfo

func (m *SearchProductsRequestV1) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *SearchProductsRequestV1) GetCount() *wrappers.Int32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *SearchProductsRequestV1) GetSession() *wrappers.StringValue {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SearchProductsRequestV1) GetCountryId() *wrappers.Int64Value {
	if m != nil {
		return m.CountryId
	}
	return nil
}

func (m *SearchProductsRequestV1) GetQuery() *QueryParamV4 {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchProductsRequestV1) GetFilters() []*FilterParamV4 {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *SearchProductsRequestV1) GetUiInfoOptions() *SearchProductsRequestV1_UIInfoOptions {
	if m != nil {
		return m.UiInfoOptions
	}
	return nil
}

func (m *SearchProductsRequestV1) GetIncludeDebuggingInfo() bool {
	if m != nil {
		return m.IncludeDebuggingInfo
	}
	return false
}

type SearchProductsRequestV1_UIInfoOptions struct {
	IncludeTab                    bool     `protobuf:"varint,1,opt,name=include_tab,json=includeTab,proto3" json:"include_tab,omitempty"`
	IncludeHeader                 bool     `protobuf:"varint,2,opt,name=include_header,json=includeHeader,proto3" json:"include_header,omitempty"`
	IncludeCtaButton              bool     `protobuf:"varint,3,opt,name=include_cta_button,json=includeCtaButton,proto3" json:"include_cta_button,omitempty"`
	IncludeAmountInfo             bool     `protobuf:"varint,4,opt,name=include_amount_info,json=includeAmountInfo,proto3" json:"include_amount_info,omitempty"`
	IncludeValuePropositionRibbon bool     `protobuf:"varint,5,opt,name=include_value_proposition_ribbon,json=includeValuePropositionRibbon,proto3" json:"include_value_proposition_ribbon,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *SearchProductsRequestV1_UIInfoOptions) Reset()         { *m = SearchProductsRequestV1_UIInfoOptions{} }
func (m *SearchProductsRequestV1_UIInfoOptions) String() string { return proto.CompactTextString(m) }
func (*SearchProductsRequestV1_UIInfoOptions) ProtoMessage()    {}
func (*SearchProductsRequestV1_UIInfoOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{0, 0}
}

func (m *SearchProductsRequestV1_UIInfoOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsRequestV1_UIInfoOptions.Unmarshal(m, b)
}
func (m *SearchProductsRequestV1_UIInfoOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsRequestV1_UIInfoOptions.Marshal(b, m, deterministic)
}
func (m *SearchProductsRequestV1_UIInfoOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsRequestV1_UIInfoOptions.Merge(m, src)
}
func (m *SearchProductsRequestV1_UIInfoOptions) XXX_Size() int {
	return xxx_messageInfo_SearchProductsRequestV1_UIInfoOptions.Size(m)
}
func (m *SearchProductsRequestV1_UIInfoOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsRequestV1_UIInfoOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsRequestV1_UIInfoOptions proto.InternalMessageInfo

func (m *SearchProductsRequestV1_UIInfoOptions) GetIncludeTab() bool {
	if m != nil {
		return m.IncludeTab
	}
	return false
}

func (m *SearchProductsRequestV1_UIInfoOptions) GetIncludeHeader() bool {
	if m != nil {
		return m.IncludeHeader
	}
	return false
}

func (m *SearchProductsRequestV1_UIInfoOptions) GetIncludeCtaButton() bool {
	if m != nil {
		return m.IncludeCtaButton
	}
	return false
}

func (m *SearchProductsRequestV1_UIInfoOptions) GetIncludeAmountInfo() bool {
	if m != nil {
		return m.IncludeAmountInfo
	}
	return false
}

func (m *SearchProductsRequestV1_UIInfoOptions) GetIncludeValuePropositionRibbon() bool {
	if m != nil {
		return m.IncludeValuePropositionRibbon
	}
	return false
}

type SearchProductsResponseV1 struct {
	Session    string                               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Results    []*SearchProductsResponseV1_Content  `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Pagination *SearchProductsResponseV1_Pagination `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Indicates whether product search is supported for the given query and filters.
	// In case is_supported is false, search result related fields like session or results will be empty.
	IsSupported          bool                                    `protobuf:"varint,4,opt,name=is_supported,json=isSupported,proto3" json:"is_supported,omitempty"`
	UiInfo               *SearchProductsResponseV1_UIInfo        `protobuf:"bytes,5,opt,name=ui_info,json=uiInfo,proto3" json:"ui_info,omitempty"`
	DebuggingInfo        *SearchProductsResponseV1_DebuggingInfo `protobuf:"bytes,15,opt,name=debugging_info,json=debuggingInfo,proto3" json:"debugging_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *SearchProductsResponseV1) Reset()         { *m = SearchProductsResponseV1{} }
func (m *SearchProductsResponseV1) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1) ProtoMessage()    {}
func (*SearchProductsResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1}
}

func (m *SearchProductsResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1.Merge(m, src)
}
func (m *SearchProductsResponseV1) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1.Size(m)
}
func (m *SearchProductsResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1 proto.InternalMessageInfo

func (m *SearchProductsResponseV1) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *SearchProductsResponseV1) GetResults() []*SearchProductsResponseV1_Content {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchProductsResponseV1) GetPagination() *SearchProductsResponseV1_Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *SearchProductsResponseV1) GetIsSupported() bool {
	if m != nil {
		return m.IsSupported
	}
	return false
}

func (m *SearchProductsResponseV1) GetUiInfo() *SearchProductsResponseV1_UIInfo {
	if m != nil {
		return m.UiInfo
	}
	return nil
}

func (m *SearchProductsResponseV1) GetDebuggingInfo() *SearchProductsResponseV1_DebuggingInfo {
	if m != nil {
		return m.DebuggingInfo
	}
	return nil
}

type SearchProductsResponseV1_Content struct {
	// Types that are valid to be assigned to Response:
	//	*SearchProductsResponseV1_Content_ProductCard
	Response             isSearchProductsResponseV1_Content_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *SearchProductsResponseV1_Content) Reset()         { *m = SearchProductsResponseV1_Content{} }
func (m *SearchProductsResponseV1_Content) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_Content) ProtoMessage()    {}
func (*SearchProductsResponseV1_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 0}
}

func (m *SearchProductsResponseV1_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_Content.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_Content.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_Content.Merge(m, src)
}
func (m *SearchProductsResponseV1_Content) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_Content.Size(m)
}
func (m *SearchProductsResponseV1_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_Content.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_Content proto.InternalMessageInfo

type isSearchProductsResponseV1_Content_Response interface {
	isSearchProductsResponseV1_Content_Response()
}

type SearchProductsResponseV1_Content_ProductCard struct {
	ProductCard *ProductCard `protobuf:"bytes,1,opt,name=product_card,json=productCard,proto3,oneof"`
}

func (*SearchProductsResponseV1_Content_ProductCard) isSearchProductsResponseV1_Content_Response() {}

func (m *SearchProductsResponseV1_Content) GetResponse() isSearchProductsResponseV1_Content_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SearchProductsResponseV1_Content) GetProductCard() *ProductCard {
	if x, ok := m.GetResponse().(*SearchProductsResponseV1_Content_ProductCard); ok {
		return x.ProductCard
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SearchProductsResponseV1_Content) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchProductsResponseV1_Content_ProductCard)(nil),
	}
}

type SearchProductsResponseV1_Pagination struct {
	Total                *wrappers.Int64Value `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	HasMore              bool                 `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchProductsResponseV1_Pagination) Reset()         { *m = SearchProductsResponseV1_Pagination{} }
func (m *SearchProductsResponseV1_Pagination) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_Pagination) ProtoMessage()    {}
func (*SearchProductsResponseV1_Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 1}
}

func (m *SearchProductsResponseV1_Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_Pagination.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_Pagination.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_Pagination.Merge(m, src)
}
func (m *SearchProductsResponseV1_Pagination) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_Pagination.Size(m)
}
func (m *SearchProductsResponseV1_Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_Pagination proto.InternalMessageInfo

func (m *SearchProductsResponseV1_Pagination) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *SearchProductsResponseV1_Pagination) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type SearchProductsResponseV1_UIInfo struct {
	Tab                  *SearchProductsResponseV1_UIInfo_Tab        `protobuf:"bytes,1,opt,name=tab,proto3" json:"tab,omitempty"`
	Header               *SearchProductsResponseV1_UIInfo_Header     `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	CtaButton            *SearchProductsResponseV1_UIInfo_CtaButton  `protobuf:"bytes,3,opt,name=cta_button,json=ctaButton,proto3" json:"cta_button,omitempty"`
	AmountInfo           *SearchProductsResponseV1_UIInfo_AmountInfo `protobuf:"bytes,4,opt,name=amount_info,json=amountInfo,proto3" json:"amount_info,omitempty"`
	Ribbon               *SearchProductsResponseV1_UIInfo_Ribbon     `protobuf:"bytes,5,opt,name=ribbon,proto3" json:"ribbon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo) Reset()         { *m = SearchProductsResponseV1_UIInfo{} }
func (m *SearchProductsResponseV1_UIInfo) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_UIInfo) ProtoMessage()    {}
func (*SearchProductsResponseV1_UIInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2}
}

func (m *SearchProductsResponseV1_UIInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo) GetTab() *SearchProductsResponseV1_UIInfo_Tab {
	if m != nil {
		return m.Tab
	}
	return nil
}

func (m *SearchProductsResponseV1_UIInfo) GetHeader() *SearchProductsResponseV1_UIInfo_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SearchProductsResponseV1_UIInfo) GetCtaButton() *SearchProductsResponseV1_UIInfo_CtaButton {
	if m != nil {
		return m.CtaButton
	}
	return nil
}

func (m *SearchProductsResponseV1_UIInfo) GetAmountInfo() *SearchProductsResponseV1_UIInfo_AmountInfo {
	if m != nil {
		return m.AmountInfo
	}
	return nil
}

func (m *SearchProductsResponseV1_UIInfo) GetRibbon() *SearchProductsResponseV1_UIInfo_Ribbon {
	if m != nil {
		return m.Ribbon
	}
	return nil
}

type SearchProductsResponseV1_UIInfo_Tab struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ShowTitleTag         bool     `protobuf:"varint,2,opt,name=showTitleTag,proto3" json:"showTitleTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo_Tab) Reset()         { *m = SearchProductsResponseV1_UIInfo_Tab{} }
func (m *SearchProductsResponseV1_UIInfo_Tab) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_UIInfo_Tab) ProtoMessage()    {}
func (*SearchProductsResponseV1_UIInfo_Tab) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2, 0}
}

func (m *SearchProductsResponseV1_UIInfo_Tab) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Tab.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo_Tab) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Tab.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo_Tab) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Tab.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo_Tab) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Tab.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo_Tab) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Tab.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo_Tab proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo_Tab) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_Tab) GetShowTitleTag() bool {
	if m != nil {
		return m.ShowTitleTag
	}
	return false
}

type SearchProductsResponseV1_UIInfo_Header struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo_Header) Reset() {
	*m = SearchProductsResponseV1_UIInfo_Header{}
}
func (m *SearchProductsResponseV1_UIInfo_Header) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_UIInfo_Header) ProtoMessage()    {}
func (*SearchProductsResponseV1_UIInfo_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2, 1}
}

func (m *SearchProductsResponseV1_UIInfo_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Header.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Header.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Header.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo_Header) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Header.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo_Header proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo_Header) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_Header) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type SearchProductsResponseV1_UIInfo_CtaButton struct {
	ButtonText           string   `protobuf:"bytes,1,opt,name=button_text,json=buttonText,proto3" json:"button_text,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo_CtaButton) Reset() {
	*m = SearchProductsResponseV1_UIInfo_CtaButton{}
}
func (m *SearchProductsResponseV1_UIInfo_CtaButton) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_UIInfo_CtaButton) ProtoMessage()    {}
func (*SearchProductsResponseV1_UIInfo_CtaButton) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2, 2}
}

func (m *SearchProductsResponseV1_UIInfo_CtaButton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_CtaButton.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo_CtaButton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_CtaButton.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo_CtaButton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_CtaButton.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo_CtaButton) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_CtaButton.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo_CtaButton) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_CtaButton.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo_CtaButton proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo_CtaButton) GetButtonText() string {
	if m != nil {
		return m.ButtonText
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_CtaButton) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type SearchProductsResponseV1_UIInfo_AmountInfo struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo_AmountInfo) Reset() {
	*m = SearchProductsResponseV1_UIInfo_AmountInfo{}
}
func (m *SearchProductsResponseV1_UIInfo_AmountInfo) String() string {
	return proto.CompactTextString(m)
}
func (*SearchProductsResponseV1_UIInfo_AmountInfo) ProtoMessage() {}
func (*SearchProductsResponseV1_UIInfo_AmountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2, 3}
}

func (m *SearchProductsResponseV1_UIInfo_AmountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_AmountInfo.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo_AmountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_AmountInfo.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo_AmountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_AmountInfo.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo_AmountInfo) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_AmountInfo.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo_AmountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_AmountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo_AmountInfo proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo_AmountInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_AmountInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type SearchProductsResponseV1_UIInfo_Ribbon struct {
	Title                string                                        `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                                        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags                 []*SearchProductsResponseV1_UIInfo_Ribbon_Tag `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Cta                  *SearchProductsResponseV1_UIInfo_Ribbon_CTA   `protobuf:"bytes,4,opt,name=cta,proto3" json:"cta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon) Reset() {
	*m = SearchProductsResponseV1_UIInfo_Ribbon{}
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_UIInfo_Ribbon) ProtoMessage()    {}
func (*SearchProductsResponseV1_UIInfo_Ribbon) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2, 4}
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo_Ribbon) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon) GetTags() []*SearchProductsResponseV1_UIInfo_Ribbon_Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon) GetCta() *SearchProductsResponseV1_UIInfo_Ribbon_CTA {
	if m != nil {
		return m.Cta
	}
	return nil
}

type SearchProductsResponseV1_UIInfo_Ribbon_Tag struct {
	IconUrl              string   `protobuf:"bytes,1,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) Reset() {
	*m = SearchProductsResponseV1_UIInfo_Ribbon_Tag{}
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) String() string {
	return proto.CompactTextString(m)
}
func (*SearchProductsResponseV1_UIInfo_Ribbon_Tag) ProtoMessage() {}
func (*SearchProductsResponseV1_UIInfo_Ribbon_Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2, 4, 0}
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_Tag.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_Tag.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_Tag.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_Tag.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_Tag proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon_Tag) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SearchProductsResponseV1_UIInfo_Ribbon_CTA struct {
	// This type indicates what client should do along with the data, such as opening a bottom sheet or a link
	// One example is used for opening a bottom sheet of value proposition details
	// {
	//   type: "go_to_value_proposition bottom_sheet",
	//   data: "{\"value_propostion_details\": {...}}" // a json string of the payload
	// }
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) Reset() {
	*m = SearchProductsResponseV1_UIInfo_Ribbon_CTA{}
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) String() string {
	return proto.CompactTextString(m)
}
func (*SearchProductsResponseV1_UIInfo_Ribbon_CTA) ProtoMessage() {}
func (*SearchProductsResponseV1_UIInfo_Ribbon_CTA) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 2, 4, 1}
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_CTA.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_CTA.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_CTA.Merge(m, src)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_CTA.Size(m)
}
func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_CTA.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_UIInfo_Ribbon_CTA proto.InternalMessageInfo

func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchProductsResponseV1_UIInfo_Ribbon_CTA) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Debugging information for us to get info of each search query.
type SearchProductsResponseV1_DebuggingInfo struct {
	Experiments          []*ExpSegment                                         `protobuf:"bytes,1,rep,name=experiments,proto3" json:"experiments,omitempty"`
	FeatureFlags         []*FeatureFlag                                        `protobuf:"bytes,2,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty"`
	SearchQueries        []*SearchProductsResponseV1_DebuggingInfo_SearchQuery `protobuf:"bytes,3,rep,name=search_queries,json=searchQueries,proto3" json:"search_queries,omitempty"`
	Total                *wrappers.Int64Value                                  `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *SearchProductsResponseV1_DebuggingInfo) Reset() {
	*m = SearchProductsResponseV1_DebuggingInfo{}
}
func (m *SearchProductsResponseV1_DebuggingInfo) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponseV1_DebuggingInfo) ProtoMessage()    {}
func (*SearchProductsResponseV1_DebuggingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 3}
}

func (m *SearchProductsResponseV1_DebuggingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_DebuggingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_DebuggingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo.Merge(m, src)
}
func (m *SearchProductsResponseV1_DebuggingInfo) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo.Size(m)
}
func (m *SearchProductsResponseV1_DebuggingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo proto.InternalMessageInfo

func (m *SearchProductsResponseV1_DebuggingInfo) GetExperiments() []*ExpSegment {
	if m != nil {
		return m.Experiments
	}
	return nil
}

func (m *SearchProductsResponseV1_DebuggingInfo) GetFeatureFlags() []*FeatureFlag {
	if m != nil {
		return m.FeatureFlags
	}
	return nil
}

func (m *SearchProductsResponseV1_DebuggingInfo) GetSearchQueries() []*SearchProductsResponseV1_DebuggingInfo_SearchQuery {
	if m != nil {
		return m.SearchQueries
	}
	return nil
}

func (m *SearchProductsResponseV1_DebuggingInfo) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

type SearchProductsResponseV1_DebuggingInfo_SearchQuery struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	EsQuery              string   `protobuf:"bytes,2,opt,name=es_query,json=esQuery,proto3" json:"es_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) Reset() {
	*m = SearchProductsResponseV1_DebuggingInfo_SearchQuery{}
}
func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) String() string {
	return proto.CompactTextString(m)
}
func (*SearchProductsResponseV1_DebuggingInfo_SearchQuery) ProtoMessage() {}
func (*SearchProductsResponseV1_DebuggingInfo_SearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{1, 3, 0}
}

func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo_SearchQuery.Unmarshal(m, b)
}
func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo_SearchQuery.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo_SearchQuery.Merge(m, src)
}
func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo_SearchQuery.Size(m)
}
func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo_SearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponseV1_DebuggingInfo_SearchQuery proto.InternalMessageInfo

func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchProductsResponseV1_DebuggingInfo_SearchQuery) GetEsQuery() string {
	if m != nil {
		return m.EsQuery
	}
	return ""
}

type GetProductsHomeFeedRequestV1 struct {
	AuthUserContainer *AuthUserContainer    `protobuf:"bytes,1,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	Count             *wrappers.Int32Value  `protobuf:"bytes,2,opt,name=count,proto3" json:"count,omitempty"`
	Session           *wrappers.StringValue `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	CountryId         *wrappers.Int64Value  `protobuf:"bytes,4,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	// Internal use
	IncludeDebuggingInfo bool     `protobuf:"varint,15,opt,name=include_debugging_info,json=includeDebuggingInfo,proto3" json:"include_debugging_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsHomeFeedRequestV1) Reset()         { *m = GetProductsHomeFeedRequestV1{} }
func (m *GetProductsHomeFeedRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetProductsHomeFeedRequestV1) ProtoMessage()    {}
func (*GetProductsHomeFeedRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{2}
}

func (m *GetProductsHomeFeedRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsHomeFeedRequestV1.Unmarshal(m, b)
}
func (m *GetProductsHomeFeedRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsHomeFeedRequestV1.Marshal(b, m, deterministic)
}
func (m *GetProductsHomeFeedRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsHomeFeedRequestV1.Merge(m, src)
}
func (m *GetProductsHomeFeedRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetProductsHomeFeedRequestV1.Size(m)
}
func (m *GetProductsHomeFeedRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsHomeFeedRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsHomeFeedRequestV1 proto.InternalMessageInfo

func (m *GetProductsHomeFeedRequestV1) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *GetProductsHomeFeedRequestV1) GetCount() *wrappers.Int32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *GetProductsHomeFeedRequestV1) GetSession() *wrappers.StringValue {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetProductsHomeFeedRequestV1) GetCountryId() *wrappers.Int64Value {
	if m != nil {
		return m.CountryId
	}
	return nil
}

func (m *GetProductsHomeFeedRequestV1) GetIncludeDebuggingInfo() bool {
	if m != nil {
		return m.IncludeDebuggingInfo
	}
	return false
}

type ProductCard struct {
	CgproductId          string                `protobuf:"bytes,1,opt,name=cgproduct_id,json=cgproductId,proto3" json:"cgproduct_id,omitempty"`
	LegacyListingId      int64                 `protobuf:"varint,2,opt,name=legacy_listing_id,json=legacyListingId,proto3" json:"legacy_listing_id,omitempty"`
	CardUi               *CardUI               `protobuf:"bytes,3,opt,name=card_ui,json=cardUi,proto3" json:"card_ui,omitempty"`
	CgproductVariantId   *wrappers.StringValue `protobuf:"bytes,4,opt,name=cgproduct_variant_id,json=cgproductVariantId,proto3" json:"cgproduct_variant_id,omitempty"`
	DeepLink             *wrappers.StringValue `protobuf:"bytes,5,opt,name=deep_link,json=deepLink,proto3" json:"deep_link,omitempty"`
	Price                string                `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProductCard) Reset()         { *m = ProductCard{} }
func (m *ProductCard) String() string { return proto.CompactTextString(m) }
func (*ProductCard) ProtoMessage()    {}
func (*ProductCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c4aebbcbd9cb55b, []int{3}
}

func (m *ProductCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCard.Unmarshal(m, b)
}
func (m *ProductCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCard.Marshal(b, m, deterministic)
}
func (m *ProductCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCard.Merge(m, src)
}
func (m *ProductCard) XXX_Size() int {
	return xxx_messageInfo_ProductCard.Size(m)
}
func (m *ProductCard) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCard.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCard proto.InternalMessageInfo

func (m *ProductCard) GetCgproductId() string {
	if m != nil {
		return m.CgproductId
	}
	return ""
}

func (m *ProductCard) GetLegacyListingId() int64 {
	if m != nil {
		return m.LegacyListingId
	}
	return 0
}

func (m *ProductCard) GetCardUi() *CardUI {
	if m != nil {
		return m.CardUi
	}
	return nil
}

func (m *ProductCard) GetCgproductVariantId() *wrappers.StringValue {
	if m != nil {
		return m.CgproductVariantId
	}
	return nil
}

func (m *ProductCard) GetDeepLink() *wrappers.StringValue {
	if m != nil {
		return m.DeepLink
	}
	return nil
}

func (m *ProductCard) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchProductsRequestV1)(nil), "ContentFeedService_proto.SearchProductsRequestV1")
	proto.RegisterType((*SearchProductsRequestV1_UIInfoOptions)(nil), "ContentFeedService_proto.SearchProductsRequestV1.UIInfoOptions")
	proto.RegisterType((*SearchProductsResponseV1)(nil), "ContentFeedService_proto.SearchProductsResponseV1")
	proto.RegisterType((*SearchProductsResponseV1_Content)(nil), "ContentFeedService_proto.SearchProductsResponseV1.Content")
	proto.RegisterType((*SearchProductsResponseV1_Pagination)(nil), "ContentFeedService_proto.SearchProductsResponseV1.Pagination")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo_Tab)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo.Tab")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo_Header)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo.Header")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo_CtaButton)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo.CtaButton")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo_AmountInfo)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo.AmountInfo")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo_Ribbon)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo.Ribbon")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo_Ribbon_Tag)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo.Ribbon.Tag")
	proto.RegisterType((*SearchProductsResponseV1_UIInfo_Ribbon_CTA)(nil), "ContentFeedService_proto.SearchProductsResponseV1.UIInfo.Ribbon.CTA")
	proto.RegisterType((*SearchProductsResponseV1_DebuggingInfo)(nil), "ContentFeedService_proto.SearchProductsResponseV1.DebuggingInfo")
	proto.RegisterType((*SearchProductsResponseV1_DebuggingInfo_SearchQuery)(nil), "ContentFeedService_proto.SearchProductsResponseV1.DebuggingInfo.SearchQuery")
	proto.RegisterType((*GetProductsHomeFeedRequestV1)(nil), "ContentFeedService_proto.GetProductsHomeFeedRequestV1")
	proto.RegisterType((*ProductCard)(nil), "ContentFeedService_proto.ProductCard")
}

func init() { proto.RegisterFile("content-feed/product_search.proto", fileDescriptor_5c4aebbcbd9cb55b) }

var fileDescriptor_5c4aebbcbd9cb55b = []byte{
	// 1293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xed, 0x6e, 0x13, 0x47,
	0x17, 0x7e, 0x13, 0x27, 0xb6, 0x73, 0x36, 0xe6, 0x63, 0x40, 0xef, 0xbb, 0xec, 0x4b, 0x4b, 0x88,
	0x4a, 0x8b, 0xda, 0x62, 0x8b, 0x10, 0x21, 0x41, 0xa9, 0x20, 0x38, 0x0d, 0x18, 0x51, 0x48, 0x27,
	0x4e, 0x84, 0xa8, 0xaa, 0xd5, 0x78, 0x77, 0xbc, 0x1e, 0xb1, 0xde, 0x59, 0x66, 0x66, 0x43, 0x72,
	0x09, 0xbd, 0xa3, 0xfe, 0x69, 0xaf, 0xa2, 0x52, 0x7b, 0x35, 0x55, 0x35, 0x1f, 0x9b, 0xb5, 0x53,
	0x8c, 0x90, 0xf3, 0xb7, 0xbf, 0xbc, 0x73, 0xce, 0x73, 0x9e, 0x99, 0x39, 0xe7, 0xcc, 0x33, 0x63,
	0xb8, 0x1e, 0xf1, 0x4c, 0xd1, 0x4c, 0xdd, 0x1a, 0x52, 0x1a, 0x77, 0x72, 0xc1, 0xe3, 0x22, 0x52,
	0xa1, 0xa4, 0x44, 0x44, 0xa3, 0x76, 0x2e, 0xb8, 0xe2, 0xc8, 0xef, 0x5a, 0xc8, 0x0e, 0xa5, 0xf1,
	0x1e, 0x15, 0x87, 0x2c, 0xa2, 0xa1, 0xf1, 0x04, 0x9f, 0x26, 0x9c, 0x27, 0x29, 0xed, 0x98, 0xd1,
	0xa0, 0x18, 0x76, 0xde, 0x09, 0x92, 0xe7, 0x54, 0x48, 0x1b, 0x19, 0x5c, 0x99, 0x22, 0x8f, 0xf8,
	0x78, 0xcc, 0x33, 0xe7, 0xba, 0x3a, 0xe5, 0xb2, 0xf3, 0x85, 0x87, 0x9b, 0xce, 0x1b, 0x4c, 0x79,
	0x53, 0x26, 0x15, 0xcb, 0x12, 0xeb, 0x5b, 0xff, 0xad, 0x0e, 0xff, 0xdb, 0x33, 0xf8, 0x5d, 0xbb,
	0x5a, 0x89, 0xe9, 0xdb, 0x82, 0x4a, 0x75, 0x70, 0x1b, 0xfd, 0x08, 0x97, 0x48, 0xa1, 0x46, 0x61,
	0x21, 0xa9, 0x08, 0x35, 0x07, 0x61, 0x19, 0x15, 0xfe, 0xc2, 0xda, 0xc2, 0x4d, 0x6f, 0xe3, 0xab,
	0xf6, 0xac, 0x8d, 0xb4, 0xb7, 0x0a, 0x35, 0xda, 0x97, 0x54, 0x74, 0xcb, 0x10, 0x7c, 0x91, 0x9c,
	0x36, 0xa1, 0xdb, 0xb0, 0x1c, 0xf1, 0x22, 0x53, 0xfe, 0xa2, 0xa1, 0xfb, 0x7f, 0xdb, 0xee, 0xbe,
	0x5d, 0xee, 0xbe, 0xdd, 0xcb, 0xd4, 0x9d, 0x8d, 0x03, 0x92, 0x16, 0x14, 0x5b, 0x24, 0xba, 0x0b,
	0x0d, 0x49, 0xa5, 0x64, 0x3c, 0xf3, 0x6b, 0x26, 0xe8, 0xea, 0x3f, 0x82, 0xf6, 0x94, 0x60, 0x59,
	0x62, 0xa3, 0x4a, 0x30, 0xba, 0x0f, 0x60, 0x08, 0xc4, 0x71, 0xc8, 0x62, 0x7f, 0x69, 0xf6, 0x7c,
	0x77, 0x37, 0x6d, 0xe4, 0x8a, 0x83, 0xf7, 0x62, 0xf4, 0x00, 0x96, 0xdf, 0x16, 0x54, 0x1c, 0xfb,
	0xcb, 0x26, 0xec, 0xf3, 0xd9, 0xbb, 0xfe, 0x41, 0xc3, 0x76, 0x89, 0x20, 0xe3, 0x83, 0x4d, 0x6c,
	0x83, 0xd0, 0x16, 0x34, 0x86, 0x2c, 0x55, 0x54, 0x48, 0xbf, 0xbe, 0x56, 0xbb, 0xe9, 0x6d, 0x7c,
	0x31, 0x3b, 0x7e, 0xc7, 0x00, 0x4b, 0x82, 0x32, 0x0e, 0x25, 0x70, 0xbe, 0x60, 0x21, 0xcb, 0x86,
	0x3c, 0xe4, 0xb9, 0x62, 0x3c, 0x93, 0x7e, 0xc3, 0x2c, 0xe5, 0xe1, 0x6c, 0xaa, 0x19, 0x05, 0x6d,
	0xef, 0xf7, 0x7a, 0xd9, 0x90, 0xbf, 0xb4, 0x34, 0xb8, 0x55, 0xb0, 0x89, 0x21, 0xda, 0x84, 0xff,
	0xb2, 0x2c, 0x4a, 0x8b, 0x98, 0x86, 0x31, 0x1d, 0x14, 0x49, 0xc2, 0xb2, 0xc4, 0xcc, 0xeb, 0x9f,
	0x5f, 0x5b, 0xb8, 0xd9, 0xc4, 0x97, 0x9d, 0x77, 0xbb, 0x74, 0xea, 0xe0, 0xe0, 0xaf, 0x05, 0x68,
	0x4d, 0xd1, 0xa2, 0x6b, 0xe0, 0x95, 0x3c, 0x8a, 0x0c, 0x4c, 0xb7, 0x34, 0x31, 0x38, 0x53, 0x9f,
	0x0c, 0xd0, 0x0d, 0x38, 0x57, 0x02, 0x46, 0x94, 0xc4, 0x54, 0x98, 0x16, 0x68, 0xe2, 0x96, 0xb3,
	0x3e, 0x35, 0x46, 0xf4, 0x35, 0xa0, 0x12, 0x16, 0x29, 0x12, 0x0e, 0x0a, 0xa5, 0x5c, 0xe1, 0x9b,
	0xf8, 0x82, 0xf3, 0x74, 0x15, 0x79, 0x6c, 0xec, 0xa8, 0x0d, 0x97, 0x4a, 0x34, 0x19, 0xeb, 0xea,
	0xd9, 0xa5, 0x2f, 0x19, 0xf8, 0x45, 0xe7, 0xda, 0x32, 0x1e, 0xbd, 0x58, 0xf4, 0x04, 0xd6, 0x4a,
	0xfc, 0xa1, 0xae, 0xb9, 0xce, 0x5c, 0xce, 0x25, 0xd3, 0x7b, 0x08, 0x05, 0x1b, 0x0c, 0x78, 0x66,
	0x4a, 0xde, 0xc4, 0x9f, 0x38, 0x9c, 0x69, 0x8d, 0xdd, 0x0a, 0x85, 0x0d, 0x68, 0xfd, 0xf7, 0x0b,
	0xe0, 0x9f, 0xce, 0xb7, 0xcc, 0x79, 0x26, 0xe9, 0xc1, 0x6d, 0xe4, 0x57, 0x1d, 0xab, 0xf3, 0xb0,
	0x52, 0xf5, 0x64, 0x1f, 0x1a, 0x82, 0xca, 0x22, 0x55, 0xd2, 0x5f, 0x34, 0x9d, 0x71, 0xff, 0xe3,
	0xcb, 0x59, 0xd2, 0x97, 0x11, 0xb8, 0xa4, 0x42, 0x3f, 0x01, 0xe4, 0x24, 0x61, 0x19, 0x51, 0xd5,
	0x21, 0xf9, 0x76, 0x0e, 0xe2, 0xdd, 0x13, 0x12, 0x3c, 0x41, 0x88, 0xae, 0xc3, 0x2a, 0x93, 0xa1,
	0x2c, 0xf2, 0x9c, 0x0b, 0x45, 0x63, 0x97, 0x5d, 0x8f, 0xc9, 0xbd, 0xd2, 0x84, 0x30, 0x34, 0x5c,
	0xbb, 0xba, 0x13, 0x73, 0x6f, 0x8e, 0xe9, 0x6d, 0x43, 0xe1, 0xba, 0x6d, 0x50, 0x94, 0xc0, 0xb9,
	0xf7, 0x74, 0xa4, 0xb7, 0xf1, 0x68, 0x0e, 0xea, 0xa9, 0xee, 0xc5, 0xad, 0x78, 0xaa, 0x99, 0x09,
	0x34, 0x1c, 0x23, 0x7a, 0x06, 0xab, 0xa5, 0x7c, 0x47, 0x44, 0xc4, 0x4e, 0xf4, 0x6e, 0xcc, 0x9e,
	0xd1, 0xcd, 0xd5, 0x25, 0x22, 0x7e, 0xfa, 0x1f, 0xec, 0xe5, 0xd5, 0xf0, 0x31, 0x40, 0x53, 0xb8,
	0x15, 0x04, 0xaf, 0x01, 0xaa, 0xe4, 0x6a, 0x11, 0x54, 0x5c, 0x91, 0xd4, 0xd1, 0x7f, 0x50, 0x94,
	0x2c, 0x12, 0x5d, 0x81, 0xe6, 0x88, 0xc8, 0x70, 0xcc, 0x05, 0x75, 0xe7, 0xa6, 0x31, 0x22, 0xf2,
	0x7b, 0x2e, 0x68, 0xf0, 0x6b, 0x13, 0xea, 0x36, 0x75, 0xe8, 0x25, 0xd4, 0xca, 0xc3, 0x37, 0x5f,
	0x07, 0x58, 0x9e, 0x76, 0x9f, 0x0c, 0xb0, 0x66, 0x42, 0xaf, 0xa0, 0x3e, 0x71, 0x58, 0xe7, 0xcb,
	0xbd, 0xe3, 0xb4, 0xe7, 0x1b, 0x3b, 0x3e, 0x34, 0x00, 0x38, 0x75, 0xbe, 0xbd, 0x8d, 0xee, 0xfc,
	0xec, 0x27, 0x92, 0x80, 0x57, 0xa2, 0x13, 0x75, 0xa0, 0xe0, 0x9d, 0x56, 0x05, 0x6f, 0x63, 0x7b,
	0xfe, 0x49, 0x2a, 0x21, 0xc1, 0x40, 0x2a, 0x51, 0x79, 0x05, 0xf5, 0x09, 0xe9, 0x38, 0x53, 0x92,
	0xac, 0xba, 0x60, 0xc7, 0x17, 0x3c, 0x84, 0x9a, 0x96, 0xce, 0xcb, 0xb0, 0xac, 0x98, 0x4a, 0xa9,
	0x53, 0x13, 0x3b, 0x40, 0xeb, 0xb0, 0x2a, 0x47, 0xfc, 0x5d, 0x5f, 0x0f, 0xfa, 0x24, 0x71, 0x6d,
	0x31, 0x65, 0x0b, 0x1e, 0x41, 0xdd, 0xe9, 0xea, 0xfb, 0x39, 0xd6, 0xc0, 0x8b, 0xa9, 0x8c, 0x04,
	0x33, 0x2a, 0x6e, 0x28, 0x56, 0xf0, 0xa4, 0x29, 0x78, 0x04, 0x2b, 0x95, 0xdc, 0x5e, 0x03, 0xcf,
	0x16, 0x2c, 0x54, 0xf4, 0x48, 0x39, 0x2a, 0xb0, 0xa6, 0x3e, 0x3d, 0x52, 0x08, 0xc1, 0x52, 0xca,
	0xb2, 0x37, 0x8e, 0xc8, 0x7c, 0x07, 0xdb, 0x00, 0x13, 0x0a, 0x3c, 0xef, 0x3a, 0xfe, 0x58, 0x84,
	0xba, 0xcd, 0xce, 0xbc, 0x14, 0xe8, 0x15, 0x2c, 0x29, 0x92, 0x48, 0xbf, 0x66, 0x94, 0x77, 0xfb,
	0xac, 0x55, 0x6a, 0xf7, 0x49, 0x82, 0x0d, 0x23, 0x3a, 0x80, 0x5a, 0xa4, 0xc8, 0xd9, 0x1b, 0xcc,
	0x11, 0x77, 0xfb, 0x5b, 0x58, 0x13, 0x06, 0x9b, 0xba, 0xfe, 0x89, 0x3e, 0xfc, 0x2c, 0xe2, 0x59,
	0x58, 0x88, 0xb4, 0xbc, 0x50, 0xf4, 0x78, 0x5f, 0xa4, 0x3a, 0xe1, 0xa6, 0x14, 0x2e, 0xe1, 0xfa,
	0x3b, 0xb8, 0x05, 0xb5, 0x6e, 0x7f, 0xcb, 0xb8, 0x8e, 0xf3, 0x32, 0x4b, 0xe6, 0x5b, 0xdb, 0x62,
	0xa2, 0x48, 0x09, 0xd7, 0xdf, 0xc1, 0xcf, 0x35, 0x68, 0x4d, 0xe9, 0x23, 0xda, 0x01, 0x8f, 0x1e,
	0xe5, 0x54, 0xb0, 0x31, 0xcd, 0x94, 0xf4, 0x17, 0x4c, 0xbe, 0x3e, 0x9b, 0xbd, 0xad, 0xef, 0x8e,
	0xf2, 0x3d, 0x9a, 0x68, 0x30, 0x9e, 0x0c, 0x44, 0xcf, 0xa0, 0x35, 0xa4, 0x44, 0x15, 0x82, 0x86,
	0xc3, 0x54, 0x67, 0xde, 0xde, 0x79, 0x1f, 0x90, 0xd3, 0x1d, 0x0b, 0xdf, 0x49, 0x49, 0x82, 0x57,
	0x87, 0xd5, 0x40, 0x22, 0x09, 0xe7, 0xdc, 0x03, 0x57, 0xbf, 0xb1, 0x18, 0x2d, 0xcb, 0xf8, 0xfc,
	0xac, 0xb7, 0x81, 0x83, 0x99, 0x77, 0x1c, 0x6e, 0xc9, 0x93, 0x01, 0xa3, 0xb2, 0x12, 0xea, 0xa5,
	0x8f, 0x15, 0xea, 0xe0, 0x01, 0x78, 0x13, 0x84, 0xef, 0x2d, 0xc2, 0x15, 0x68, 0x52, 0x19, 0xda,
	0xf7, 0xa5, 0x2d, 0x44, 0x83, 0x4a, 0x03, 0x5f, 0xff, 0x73, 0x11, 0xae, 0x3e, 0xa1, 0xaa, 0x5c,
	0xf3, 0x53, 0x3e, 0xa6, 0x7a, 0x5f, 0xff, 0x3e, 0xce, 0x27, 0x1f, 0xe7, 0x73, 0x3d, 0x59, 0xd7,
	0x7f, 0x59, 0x04, 0x6f, 0xe2, 0xb6, 0xd6, 0xaf, 0x9a, 0x28, 0x29, 0x2f, 0x7b, 0x16, 0xbb, 0x0a,
	0x79, 0x27, 0xb6, 0x5e, 0x8c, 0xbe, 0x84, 0x8b, 0x29, 0x4d, 0x48, 0x74, 0x1c, 0xba, 0x7f, 0x4f,
	0x1a, 0xa7, 0x73, 0x53, 0xc3, 0xe7, 0xad, 0xe3, 0xb9, 0xb5, 0xf7, 0x62, 0x74, 0x0f, 0x1a, 0xfa,
	0xc5, 0x10, 0x16, 0xcc, 0x25, 0x62, 0x6d, 0x76, 0x31, 0xf4, 0xfc, 0xfb, 0x3d, 0x5c, 0xd7, 0x01,
	0xfb, 0x0c, 0xbd, 0x80, 0xcb, 0xd5, 0x4a, 0x0e, 0x89, 0x60, 0x24, 0x53, 0x55, 0x56, 0x3e, 0x9c,
	0x50, 0x74, 0x12, 0x79, 0x60, 0x03, 0xcd, 0x52, 0x56, 0x62, 0x4a, 0xf3, 0xd0, 0x28, 0xf1, 0xf2,
	0x47, 0x90, 0x34, 0x35, 0xfc, 0x39, 0xcb, 0xde, 0x68, 0x69, 0xcd, 0x05, 0x8b, 0xa8, 0x5f, 0xb7,
	0xd2, 0x6a, 0x06, 0x8f, 0x77, 0x5f, 0xbf, 0x48, 0x98, 0x1a, 0x15, 0x83, 0x76, 0xc4, 0xc7, 0x9d,
	0x88, 0x08, 0x5e, 0x48, 0x9a, 0xa6, 0x1d, 0x39, 0x22, 0x82, 0xc6, 0xb7, 0x0c, 0x67, 0x27, 0xa1,
	0x59, 0x27, 0xe1, 0x9d, 0xc9, 0x3f, 0x9d, 0xdf, 0xcc, 0xca, 0xc0, 0xa0, 0x6e, 0x7e, 0xee, 0xfc,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x36, 0x9d, 0x60, 0x26, 0x3a, 0x0f, 0x00, 0x00,
}
