// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content-feed/search_v3.proto

package ContentFeedService_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client int32

const (
	Client_IOS     Client = 0
	Client_ANDROID Client = 1
	Client_WEB     Client = 2
)

var Client_name = map[int32]string{
	0: "IOS",
	1: "ANDROID",
	2: "WEB",
}

var Client_value = map[string]int32{
	"IOS":     0,
	"ANDROID": 1,
	"WEB":     2,
}

func (x Client) String() string {
	return proto.EnumName(Client_name, int32(x))
}

func (Client) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{0}
}

type Version int32

const (
	Version_UNKNOWN_VERSION  Version = 0
	Version_SINGLE_SLOT_ONLY Version = 1
)

var Version_name = map[int32]string{
	0: "UNKNOWN_VERSION",
	1: "SINGLE_SLOT_ONLY",
}

var Version_value = map[string]int32{
	"UNKNOWN_VERSION":  0,
	"SINGLE_SLOT_ONLY": 1,
}

func (x Version) String() string {
	return proto.EnumName(Version_name, int32(x))
}

func (Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{1}
}

// QueryType instructs which field to be matched by query string. The Default type matches several key fields defined by search algorithm.
// TitleOnly, DescOnly and TitleDescOnly, which matches query to title/desc or both, are typically used by internal tools (eg lumos).
type QueryParam_QueryType int32

const (
	QueryParam_Default       QueryParam_QueryType = 0
	QueryParam_TitleOnly     QueryParam_QueryType = 1
	QueryParam_DescOnly      QueryParam_QueryType = 2
	QueryParam_TitleDescOnly QueryParam_QueryType = 3
)

var QueryParam_QueryType_name = map[int32]string{
	0: "Default",
	1: "TitleOnly",
	2: "DescOnly",
	3: "TitleDescOnly",
}

var QueryParam_QueryType_value = map[string]int32{
	"Default":       0,
	"TitleOnly":     1,
	"DescOnly":      2,
	"TitleDescOnly": 3,
}

func (x QueryParam_QueryType) String() string {
	return proto.EnumName(QueryParam_QueryType_name, int32(x))
}

func (QueryParam_QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{21, 0}
}

type ImageSearchContext_EncodedImage_Format int32

const (
	ImageSearchContext_EncodedImage_UNKNOWN ImageSearchContext_EncodedImage_Format = 0
	ImageSearchContext_EncodedImage_JPEG    ImageSearchContext_EncodedImage_Format = 1
)

var ImageSearchContext_EncodedImage_Format_name = map[int32]string{
	0: "UNKNOWN",
	1: "JPEG",
}

var ImageSearchContext_EncodedImage_Format_value = map[string]int32{
	"UNKNOWN": 0,
	"JPEG":    1,
}

func (x ImageSearchContext_EncodedImage_Format) String() string {
	return proto.EnumName(ImageSearchContext_EncodedImage_Format_name, int32(x))
}

func (ImageSearchContext_EncodedImage_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{23, 0, 0}
}

//*
// Response object.
//
// @param
// session: Pagination context; Next query should have this session for next page.
// SearchResponseV34: array of search result
// sf_context: SF context including country collection id
// is_context: ImageSearch context including some of caching info for result
// available_collections: list of collections based in search result for more accurate filtering by collection
// pagination: information about future pages
type SearchListingsResponseV34 struct {
	Session              string               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Results              []*SearchResponseV34 `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	SfContext            *SFContext           `protobuf:"bytes,3,opt,name=sf_context,json=sfContext,proto3" json:"sf_context,omitempty"`
	Total                *wrappers.Int64Value `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	IsContext            *ImageSearchContext  `protobuf:"bytes,5,opt,name=is_context,json=isContext,proto3" json:"is_context,omitempty"`
	AvailableCollections []*Collection        `protobuf:"bytes,6,rep,name=available_collections,json=availableCollections,proto3" json:"available_collections,omitempty"`
	Pagination           *PaginationContext   `protobuf:"bytes,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchListingsResponseV34) Reset()         { *m = SearchListingsResponseV34{} }
func (m *SearchListingsResponseV34) String() string { return proto.CompactTextString(m) }
func (*SearchListingsResponseV34) ProtoMessage()    {}
func (*SearchListingsResponseV34) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{0}
}

func (m *SearchListingsResponseV34) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchListingsResponseV34.Unmarshal(m, b)
}
func (m *SearchListingsResponseV34) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchListingsResponseV34.Marshal(b, m, deterministic)
}
func (m *SearchListingsResponseV34) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchListingsResponseV34.Merge(m, src)
}
func (m *SearchListingsResponseV34) XXX_Size() int {
	return xxx_messageInfo_SearchListingsResponseV34.Size(m)
}
func (m *SearchListingsResponseV34) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchListingsResponseV34.DiscardUnknown(m)
}

var xxx_messageInfo_SearchListingsResponseV34 proto.InternalMessageInfo

func (m *SearchListingsResponseV34) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *SearchListingsResponseV34) GetResults() []*SearchResponseV34 {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchListingsResponseV34) GetSfContext() *SFContext {
	if m != nil {
		return m.SfContext
	}
	return nil
}

func (m *SearchListingsResponseV34) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *SearchListingsResponseV34) GetIsContext() *ImageSearchContext {
	if m != nil {
		return m.IsContext
	}
	return nil
}

func (m *SearchListingsResponseV34) GetAvailableCollections() []*Collection {
	if m != nil {
		return m.AvailableCollections
	}
	return nil
}

func (m *SearchListingsResponseV34) GetPagination() *PaginationContext {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type SearchResponseV34 struct {
	// Types that are valid to be assigned to Response:
	//	*SearchResponseV34_ListingCard
	//	*SearchResponseV34_PromotedListingCard
	//	*SearchResponseV34_ExternalAd
	//	*SearchResponseV34_BumpTouchpointCard
	//	*SearchResponseV34_GroupPostCollection
	//	*SearchResponseV34_ProfilePromotionCard
	//	*SearchResponseV34_ExternalVidAd
	//	*SearchResponseV34_DedicatedSpotlightSection
	//	*SearchResponseV34_ShoutoutPromotionCard
	Response             isSearchResponseV34_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SearchResponseV34) Reset()         { *m = SearchResponseV34{} }
func (m *SearchResponseV34) String() string { return proto.CompactTextString(m) }
func (*SearchResponseV34) ProtoMessage()    {}
func (*SearchResponseV34) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{1}
}

func (m *SearchResponseV34) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponseV34.Unmarshal(m, b)
}
func (m *SearchResponseV34) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponseV34.Marshal(b, m, deterministic)
}
func (m *SearchResponseV34) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponseV34.Merge(m, src)
}
func (m *SearchResponseV34) XXX_Size() int {
	return xxx_messageInfo_SearchResponseV34.Size(m)
}
func (m *SearchResponseV34) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponseV34.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponseV34 proto.InternalMessageInfo

type isSearchResponseV34_Response interface {
	isSearchResponseV34_Response()
}

type SearchResponseV34_ListingCard struct {
	ListingCard *ListingCard `protobuf:"bytes,1,opt,name=listing_card,json=listingCard,proto3,oneof"`
}

type SearchResponseV34_PromotedListingCard struct {
	PromotedListingCard *PromotedListingCard `protobuf:"bytes,2,opt,name=promoted_listing_card,json=promotedListingCard,proto3,oneof"`
}

type SearchResponseV34_ExternalAd struct {
	ExternalAd *ExternalAd `protobuf:"bytes,3,opt,name=external_ad,json=externalAd,proto3,oneof"`
}

type SearchResponseV34_BumpTouchpointCard struct {
	BumpTouchpointCard *BumpTouchPointCard `protobuf:"bytes,4,opt,name=bump_touchpoint_card,json=bumpTouchpointCard,proto3,oneof"`
}

type SearchResponseV34_GroupPostCollection struct {
	GroupPostCollection *GroupPostCollection `protobuf:"bytes,5,opt,name=group_post_collection,json=groupPostCollection,proto3,oneof"`
}

type SearchResponseV34_ProfilePromotionCard struct {
	ProfilePromotionCard *ProfilePromotionCard `protobuf:"bytes,6,opt,name=profile_promotion_card,json=profilePromotionCard,proto3,oneof"`
}

type SearchResponseV34_ExternalVidAd struct {
	ExternalVidAd *ExternalVidAd `protobuf:"bytes,7,opt,name=external_vid_ad,json=externalVidAd,proto3,oneof"`
}

type SearchResponseV34_DedicatedSpotlightSection struct {
	DedicatedSpotlightSection *DedicatedSpotlightSection `protobuf:"bytes,8,opt,name=dedicated_spotlight_section,json=dedicatedSpotlightSection,proto3,oneof"`
}

type SearchResponseV34_ShoutoutPromotionCard struct {
	ShoutoutPromotionCard *ShoutoutPromotionCard `protobuf:"bytes,9,opt,name=shoutout_promotion_card,json=shoutoutPromotionCard,proto3,oneof"`
}

func (*SearchResponseV34_ListingCard) isSearchResponseV34_Response() {}

func (*SearchResponseV34_PromotedListingCard) isSearchResponseV34_Response() {}

func (*SearchResponseV34_ExternalAd) isSearchResponseV34_Response() {}

func (*SearchResponseV34_BumpTouchpointCard) isSearchResponseV34_Response() {}

func (*SearchResponseV34_GroupPostCollection) isSearchResponseV34_Response() {}

func (*SearchResponseV34_ProfilePromotionCard) isSearchResponseV34_Response() {}

func (*SearchResponseV34_ExternalVidAd) isSearchResponseV34_Response() {}

func (*SearchResponseV34_DedicatedSpotlightSection) isSearchResponseV34_Response() {}

func (*SearchResponseV34_ShoutoutPromotionCard) isSearchResponseV34_Response() {}

func (m *SearchResponseV34) GetResponse() isSearchResponseV34_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SearchResponseV34) GetListingCard() *ListingCard {
	if x, ok := m.GetResponse().(*SearchResponseV34_ListingCard); ok {
		return x.ListingCard
	}
	return nil
}

func (m *SearchResponseV34) GetPromotedListingCard() *PromotedListingCard {
	if x, ok := m.GetResponse().(*SearchResponseV34_PromotedListingCard); ok {
		return x.PromotedListingCard
	}
	return nil
}

func (m *SearchResponseV34) GetExternalAd() *ExternalAd {
	if x, ok := m.GetResponse().(*SearchResponseV34_ExternalAd); ok {
		return x.ExternalAd
	}
	return nil
}

func (m *SearchResponseV34) GetBumpTouchpointCard() *BumpTouchPointCard {
	if x, ok := m.GetResponse().(*SearchResponseV34_BumpTouchpointCard); ok {
		return x.BumpTouchpointCard
	}
	return nil
}

func (m *SearchResponseV34) GetGroupPostCollection() *GroupPostCollection {
	if x, ok := m.GetResponse().(*SearchResponseV34_GroupPostCollection); ok {
		return x.GroupPostCollection
	}
	return nil
}

func (m *SearchResponseV34) GetProfilePromotionCard() *ProfilePromotionCard {
	if x, ok := m.GetResponse().(*SearchResponseV34_ProfilePromotionCard); ok {
		return x.ProfilePromotionCard
	}
	return nil
}

func (m *SearchResponseV34) GetExternalVidAd() *ExternalVidAd {
	if x, ok := m.GetResponse().(*SearchResponseV34_ExternalVidAd); ok {
		return x.ExternalVidAd
	}
	return nil
}

func (m *SearchResponseV34) GetDedicatedSpotlightSection() *DedicatedSpotlightSection {
	if x, ok := m.GetResponse().(*SearchResponseV34_DedicatedSpotlightSection); ok {
		return x.DedicatedSpotlightSection
	}
	return nil
}

func (m *SearchResponseV34) GetShoutoutPromotionCard() *ShoutoutPromotionCard {
	if x, ok := m.GetResponse().(*SearchResponseV34_ShoutoutPromotionCard); ok {
		return x.ShoutoutPromotionCard
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SearchResponseV34) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchResponseV34_ListingCard)(nil),
		(*SearchResponseV34_PromotedListingCard)(nil),
		(*SearchResponseV34_ExternalAd)(nil),
		(*SearchResponseV34_BumpTouchpointCard)(nil),
		(*SearchResponseV34_GroupPostCollection)(nil),
		(*SearchResponseV34_ProfilePromotionCard)(nil),
		(*SearchResponseV34_ExternalVidAd)(nil),
		(*SearchResponseV34_DedicatedSpotlightSection)(nil),
		(*SearchResponseV34_ShoutoutPromotionCard)(nil),
	}
}

type GetUserLikedListingsRequestV3 struct {
	AuthUserContainer    *AuthUserContainer `protobuf:"bytes,1,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	Start                int64              `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Count                int64              `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	CategoryIds          []string           `protobuf:"bytes,4,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetUserLikedListingsRequestV3) Reset()         { *m = GetUserLikedListingsRequestV3{} }
func (m *GetUserLikedListingsRequestV3) String() string { return proto.CompactTextString(m) }
func (*GetUserLikedListingsRequestV3) ProtoMessage()    {}
func (*GetUserLikedListingsRequestV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{2}
}

func (m *GetUserLikedListingsRequestV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserLikedListingsRequestV3.Unmarshal(m, b)
}
func (m *GetUserLikedListingsRequestV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserLikedListingsRequestV3.Marshal(b, m, deterministic)
}
func (m *GetUserLikedListingsRequestV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserLikedListingsRequestV3.Merge(m, src)
}
func (m *GetUserLikedListingsRequestV3) XXX_Size() int {
	return xxx_messageInfo_GetUserLikedListingsRequestV3.Size(m)
}
func (m *GetUserLikedListingsRequestV3) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserLikedListingsRequestV3.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserLikedListingsRequestV3 proto.InternalMessageInfo

func (m *GetUserLikedListingsRequestV3) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *GetUserLikedListingsRequestV3) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetUserLikedListingsRequestV3) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetUserLikedListingsRequestV3) GetCategoryIds() []string {
	if m != nil {
		return m.CategoryIds
	}
	return nil
}

//*
// Response object.
//
// @param
// session: Pagination context; Next query should have this session for next page.
// SearchResponseV33: array of search result
// sfcontext: SF context including country collection id
type SearchListingsResponseV33 struct {
	Session              string               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Results              []*SearchResponseV33 `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	SfContext            *SFContext           `protobuf:"bytes,3,opt,name=sf_context,json=sfContext,proto3" json:"sf_context,omitempty"`
	Total                *wrappers.Int64Value `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchListingsResponseV33) Reset()         { *m = SearchListingsResponseV33{} }
func (m *SearchListingsResponseV33) String() string { return proto.CompactTextString(m) }
func (*SearchListingsResponseV33) ProtoMessage()    {}
func (*SearchListingsResponseV33) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{3}
}

func (m *SearchListingsResponseV33) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchListingsResponseV33.Unmarshal(m, b)
}
func (m *SearchListingsResponseV33) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchListingsResponseV33.Marshal(b, m, deterministic)
}
func (m *SearchListingsResponseV33) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchListingsResponseV33.Merge(m, src)
}
func (m *SearchListingsResponseV33) XXX_Size() int {
	return xxx_messageInfo_SearchListingsResponseV33.Size(m)
}
func (m *SearchListingsResponseV33) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchListingsResponseV33.DiscardUnknown(m)
}

var xxx_messageInfo_SearchListingsResponseV33 proto.InternalMessageInfo

func (m *SearchListingsResponseV33) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *SearchListingsResponseV33) GetResults() []*SearchResponseV33 {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchListingsResponseV33) GetSfContext() *SFContext {
	if m != nil {
		return m.SfContext
	}
	return nil
}

func (m *SearchListingsResponseV33) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

type SearchResponseV33 struct {
	// Types that are valid to be assigned to Response:
	//	*SearchResponseV33_ListingCard
	//	*SearchResponseV33_PromotedListingCard
	//	*SearchResponseV33_ExternalAd
	Response             isSearchResponseV33_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SearchResponseV33) Reset()         { *m = SearchResponseV33{} }
func (m *SearchResponseV33) String() string { return proto.CompactTextString(m) }
func (*SearchResponseV33) ProtoMessage()    {}
func (*SearchResponseV33) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{4}
}

func (m *SearchResponseV33) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponseV33.Unmarshal(m, b)
}
func (m *SearchResponseV33) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponseV33.Marshal(b, m, deterministic)
}
func (m *SearchResponseV33) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponseV33.Merge(m, src)
}
func (m *SearchResponseV33) XXX_Size() int {
	return xxx_messageInfo_SearchResponseV33.Size(m)
}
func (m *SearchResponseV33) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponseV33.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponseV33 proto.InternalMessageInfo

type isSearchResponseV33_Response interface {
	isSearchResponseV33_Response()
}

type SearchResponseV33_ListingCard struct {
	ListingCard *ListingCard `protobuf:"bytes,1,opt,name=listing_card,json=listingCard,proto3,oneof"`
}

type SearchResponseV33_PromotedListingCard struct {
	PromotedListingCard *PromotedListingCard `protobuf:"bytes,2,opt,name=promoted_listing_card,json=promotedListingCard,proto3,oneof"`
}

type SearchResponseV33_ExternalAd struct {
	ExternalAd *ExternalAd `protobuf:"bytes,3,opt,name=external_ad,json=externalAd,proto3,oneof"`
}

func (*SearchResponseV33_ListingCard) isSearchResponseV33_Response() {}

func (*SearchResponseV33_PromotedListingCard) isSearchResponseV33_Response() {}

func (*SearchResponseV33_ExternalAd) isSearchResponseV33_Response() {}

func (m *SearchResponseV33) GetResponse() isSearchResponseV33_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SearchResponseV33) GetListingCard() *ListingCard {
	if x, ok := m.GetResponse().(*SearchResponseV33_ListingCard); ok {
		return x.ListingCard
	}
	return nil
}

func (m *SearchResponseV33) GetPromotedListingCard() *PromotedListingCard {
	if x, ok := m.GetResponse().(*SearchResponseV33_PromotedListingCard); ok {
		return x.PromotedListingCard
	}
	return nil
}

func (m *SearchResponseV33) GetExternalAd() *ExternalAd {
	if x, ok := m.GetResponse().(*SearchResponseV33_ExternalAd); ok {
		return x.ExternalAd
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SearchResponseV33) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchResponseV33_ListingCard)(nil),
		(*SearchResponseV33_PromotedListingCard)(nil),
		(*SearchResponseV33_ExternalAd)(nil),
	}
}

type GatewayRequestV30 struct {
	Count     *wrappers.Int32Value  `protobuf:"bytes,2,opt,name=count,proto3" json:"count,omitempty"`
	Session   *wrappers.StringValue `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	SortParam *SortParam            `protobuf:"bytes,4,opt,name=sortParam,proto3" json:"sortParam,omitempty"`
	Filters   []*FilterParam        `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	Query     *QueryParam           `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	CountryId *wrappers.Int64Value  `protobuf:"bytes,7,opt,name=countryId,proto3" json:"countryId,omitempty"`
	Platform  string                `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
	Locale    string                `protobuf:"bytes,9,opt,name=locale,proto3" json:"locale,omitempty"`
	Client    Client                `protobuf:"varint,11,opt,name=client,proto3,enum=ContentFeedService_proto.Client" json:"client,omitempty"`
	//    Source source = 12;  deprecated
	//In order to identify unique users, Google created ‘GAID’ (Google Advertising ID), and Apple created ‘IDFA’ (Identifier For Advertising).
	AdvertisingId string `protobuf:"bytes,13,opt,name=advertising_id,json=advertisingId,proto3" json:"advertising_id,omitempty"`
	//if in the OS settings the user has enabled the limit ad tracking, then the OS will return true to us when we call to retrieve that info from `AdvertisingIdentifier`
	DoNotTrack bool      `protobuf:"varint,14,opt,name=do_not_track,json=doNotTrack,proto3" json:"do_not_track,omitempty"`
	AdVersion  AdVersion `protobuf:"varint,15,opt,name=ad_version,json=adVersion,proto3,enum=ContentFeedService_proto.AdVersion" json:"ad_version,omitempty"`
	SoldSlot   bool      `protobuf:"varint,16,opt,name=soldSlot,proto3" json:"soldSlot,omitempty"`
	//    Version version = 17;  deprecated
	IgnoreCount          bool     `protobuf:"varint,18,opt,name=ignore_count,json=ignoreCount,proto3" json:"ignore_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayRequestV30) Reset()         { *m = GatewayRequestV30{} }
func (m *GatewayRequestV30) String() string { return proto.CompactTextString(m) }
func (*GatewayRequestV30) ProtoMessage()    {}
func (*GatewayRequestV30) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{5}
}

func (m *GatewayRequestV30) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayRequestV30.Unmarshal(m, b)
}
func (m *GatewayRequestV30) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayRequestV30.Marshal(b, m, deterministic)
}
func (m *GatewayRequestV30) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayRequestV30.Merge(m, src)
}
func (m *GatewayRequestV30) XXX_Size() int {
	return xxx_messageInfo_GatewayRequestV30.Size(m)
}
func (m *GatewayRequestV30) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayRequestV30.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayRequestV30 proto.InternalMessageInfo

func (m *GatewayRequestV30) GetCount() *wrappers.Int32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *GatewayRequestV30) GetSession() *wrappers.StringValue {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GatewayRequestV30) GetSortParam() *SortParam {
	if m != nil {
		return m.SortParam
	}
	return nil
}

func (m *GatewayRequestV30) GetFilters() []*FilterParam {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *GatewayRequestV30) GetQuery() *QueryParam {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GatewayRequestV30) GetCountryId() *wrappers.Int64Value {
	if m != nil {
		return m.CountryId
	}
	return nil
}

func (m *GatewayRequestV30) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *GatewayRequestV30) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *GatewayRequestV30) GetClient() Client {
	if m != nil {
		return m.Client
	}
	return Client_IOS
}

func (m *GatewayRequestV30) GetAdvertisingId() string {
	if m != nil {
		return m.AdvertisingId
	}
	return ""
}

func (m *GatewayRequestV30) GetDoNotTrack() bool {
	if m != nil {
		return m.DoNotTrack
	}
	return false
}

func (m *GatewayRequestV30) GetAdVersion() AdVersion {
	if m != nil {
		return m.AdVersion
	}
	return AdVersion_DEFAULT_AD_VERSION
}

func (m *GatewayRequestV30) GetSoldSlot() bool {
	if m != nil {
		return m.SoldSlot
	}
	return false
}

func (m *GatewayRequestV30) GetIgnoreCount() bool {
	if m != nil {
		return m.IgnoreCount
	}
	return false
}

type GetSearchListingsTotalResponseV3 struct {
	Total                *wrappers.Int64Value `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetSearchListingsTotalResponseV3) Reset()         { *m = GetSearchListingsTotalResponseV3{} }
func (m *GetSearchListingsTotalResponseV3) String() string { return proto.CompactTextString(m) }
func (*GetSearchListingsTotalResponseV3) ProtoMessage()    {}
func (*GetSearchListingsTotalResponseV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{6}
}

func (m *GetSearchListingsTotalResponseV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSearchListingsTotalResponseV3.Unmarshal(m, b)
}
func (m *GetSearchListingsTotalResponseV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSearchListingsTotalResponseV3.Marshal(b, m, deterministic)
}
func (m *GetSearchListingsTotalResponseV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSearchListingsTotalResponseV3.Merge(m, src)
}
func (m *GetSearchListingsTotalResponseV3) XXX_Size() int {
	return xxx_messageInfo_GetSearchListingsTotalResponseV3.Size(m)
}
func (m *GetSearchListingsTotalResponseV3) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSearchListingsTotalResponseV3.DiscardUnknown(m)
}

var xxx_messageInfo_GetSearchListingsTotalResponseV3 proto.InternalMessageInfo

func (m *GetSearchListingsTotalResponseV3) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

type SearchListingsRequestV3 struct {
	AuthUserContainer *AuthUserContainer `protobuf:"bytes,1,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	//    TraceContext tc = 2; deprecated. trace context should be passed via grpc header
	GatewayRequest       *GatewayRequestV30 `protobuf:"bytes,4,opt,name=gateway_request,json=gatewayRequest,proto3" json:"gateway_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchListingsRequestV3) Reset()         { *m = SearchListingsRequestV3{} }
func (m *SearchListingsRequestV3) String() string { return proto.CompactTextString(m) }
func (*SearchListingsRequestV3) ProtoMessage()    {}
func (*SearchListingsRequestV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{7}
}

func (m *SearchListingsRequestV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchListingsRequestV3.Unmarshal(m, b)
}
func (m *SearchListingsRequestV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchListingsRequestV3.Marshal(b, m, deterministic)
}
func (m *SearchListingsRequestV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchListingsRequestV3.Merge(m, src)
}
func (m *SearchListingsRequestV3) XXX_Size() int {
	return xxx_messageInfo_SearchListingsRequestV3.Size(m)
}
func (m *SearchListingsRequestV3) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchListingsRequestV3.DiscardUnknown(m)
}

var xxx_messageInfo_SearchListingsRequestV3 proto.InternalMessageInfo

func (m *SearchListingsRequestV3) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *SearchListingsRequestV3) GetGatewayRequest() *GatewayRequestV30 {
	if m != nil {
		return m.GatewayRequest
	}
	return nil
}

type SearchProfileListingsRequestV3 struct {
	AuthUserContainer *AuthUserContainer `protobuf:"bytes,1,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	//    TraceContext tc = 2; deprecated. trace context should be passed via grpc header
	GatewayRequest       *GatewayRequestV30 `protobuf:"bytes,4,opt,name=gateway_request,json=gatewayRequest,proto3" json:"gateway_request,omitempty"`
	UserName             string             `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchProfileListingsRequestV3) Reset()         { *m = SearchProfileListingsRequestV3{} }
func (m *SearchProfileListingsRequestV3) String() string { return proto.CompactTextString(m) }
func (*SearchProfileListingsRequestV3) ProtoMessage()    {}
func (*SearchProfileListingsRequestV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{8}
}

func (m *SearchProfileListingsRequestV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProfileListingsRequestV3.Unmarshal(m, b)
}
func (m *SearchProfileListingsRequestV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProfileListingsRequestV3.Marshal(b, m, deterministic)
}
func (m *SearchProfileListingsRequestV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProfileListingsRequestV3.Merge(m, src)
}
func (m *SearchProfileListingsRequestV3) XXX_Size() int {
	return xxx_messageInfo_SearchProfileListingsRequestV3.Size(m)
}
func (m *SearchProfileListingsRequestV3) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProfileListingsRequestV3.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProfileListingsRequestV3 proto.InternalMessageInfo

func (m *SearchProfileListingsRequestV3) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *SearchProfileListingsRequestV3) GetGatewayRequest() *GatewayRequestV30 {
	if m != nil {
		return m.GatewayRequest
	}
	return nil
}

func (m *SearchProfileListingsRequestV3) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type SearchSpcListingsRequestV3 struct {
	AuthUserContainer *AuthUserContainer `protobuf:"bytes,1,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	//    TraceContext tc = 2; deprecated. trace context should be passed via grpc header
	GatewayRequest       *GatewayRequestV30 `protobuf:"bytes,4,opt,name=gateway_request,json=gatewayRequest,proto3" json:"gateway_request,omitempty"`
	SpcId                string             `protobuf:"bytes,5,opt,name=spcId,proto3" json:"spcId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchSpcListingsRequestV3) Reset()         { *m = SearchSpcListingsRequestV3{} }
func (m *SearchSpcListingsRequestV3) String() string { return proto.CompactTextString(m) }
func (*SearchSpcListingsRequestV3) ProtoMessage()    {}
func (*SearchSpcListingsRequestV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{9}
}

func (m *SearchSpcListingsRequestV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSpcListingsRequestV3.Unmarshal(m, b)
}
func (m *SearchSpcListingsRequestV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSpcListingsRequestV3.Marshal(b, m, deterministic)
}
func (m *SearchSpcListingsRequestV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSpcListingsRequestV3.Merge(m, src)
}
func (m *SearchSpcListingsRequestV3) XXX_Size() int {
	return xxx_messageInfo_SearchSpcListingsRequestV3.Size(m)
}
func (m *SearchSpcListingsRequestV3) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSpcListingsRequestV3.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSpcListingsRequestV3 proto.InternalMessageInfo

func (m *SearchSpcListingsRequestV3) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *SearchSpcListingsRequestV3) GetGatewayRequest() *GatewayRequestV30 {
	if m != nil {
		return m.GatewayRequest
	}
	return nil
}

func (m *SearchSpcListingsRequestV3) GetSpcId() string {
	if m != nil {
		return m.SpcId
	}
	return ""
}

type GetMoreFromThisSellerFeedRequestV1 struct {
	AuthUserContainer    *AuthUserContainer `protobuf:"bytes,1,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	ProductId            string             `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ClientInfo           *ClientInfo        `protobuf:"bytes,3,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetMoreFromThisSellerFeedRequestV1) Reset()         { *m = GetMoreFromThisSellerFeedRequestV1{} }
func (m *GetMoreFromThisSellerFeedRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetMoreFromThisSellerFeedRequestV1) ProtoMessage()    {}
func (*GetMoreFromThisSellerFeedRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{10}
}

func (m *GetMoreFromThisSellerFeedRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMoreFromThisSellerFeedRequestV1.Unmarshal(m, b)
}
func (m *GetMoreFromThisSellerFeedRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMoreFromThisSellerFeedRequestV1.Marshal(b, m, deterministic)
}
func (m *GetMoreFromThisSellerFeedRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMoreFromThisSellerFeedRequestV1.Merge(m, src)
}
func (m *GetMoreFromThisSellerFeedRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetMoreFromThisSellerFeedRequestV1.Size(m)
}
func (m *GetMoreFromThisSellerFeedRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMoreFromThisSellerFeedRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetMoreFromThisSellerFeedRequestV1 proto.InternalMessageInfo

func (m *GetMoreFromThisSellerFeedRequestV1) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *GetMoreFromThisSellerFeedRequestV1) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *GetMoreFromThisSellerFeedRequestV1) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type GetHyperlocalFeedRequestV1 struct {
	Count *wrappers.Int32Value `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	// Session is required for paging. When session is present, all the following fields are ignored.
	Session *wrappers.StringValue `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	// The geographical center
	Location             *Location          `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	AuthUserContainer    *AuthUserContainer `protobuf:"bytes,14,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	ClientInfo           *ClientInfo        `protobuf:"bytes,15,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetHyperlocalFeedRequestV1) Reset()         { *m = GetHyperlocalFeedRequestV1{} }
func (m *GetHyperlocalFeedRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetHyperlocalFeedRequestV1) ProtoMessage()    {}
func (*GetHyperlocalFeedRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{11}
}

func (m *GetHyperlocalFeedRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperlocalFeedRequestV1.Unmarshal(m, b)
}
func (m *GetHyperlocalFeedRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperlocalFeedRequestV1.Marshal(b, m, deterministic)
}
func (m *GetHyperlocalFeedRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperlocalFeedRequestV1.Merge(m, src)
}
func (m *GetHyperlocalFeedRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetHyperlocalFeedRequestV1.Size(m)
}
func (m *GetHyperlocalFeedRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperlocalFeedRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperlocalFeedRequestV1 proto.InternalMessageInfo

func (m *GetHyperlocalFeedRequestV1) GetCount() *wrappers.Int32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV1) GetSession() *wrappers.StringValue {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV1) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV1) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV1) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type GetHyperlocalFeedResponseV1 struct {
	Session              string                                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Results              []*GetHyperlocalFeedResponseV1_Content `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Pagination           *Pagination                            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetHyperlocalFeedResponseV1) Reset()         { *m = GetHyperlocalFeedResponseV1{} }
func (m *GetHyperlocalFeedResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetHyperlocalFeedResponseV1) ProtoMessage()    {}
func (*GetHyperlocalFeedResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{12}
}

func (m *GetHyperlocalFeedResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperlocalFeedResponseV1.Unmarshal(m, b)
}
func (m *GetHyperlocalFeedResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperlocalFeedResponseV1.Marshal(b, m, deterministic)
}
func (m *GetHyperlocalFeedResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperlocalFeedResponseV1.Merge(m, src)
}
func (m *GetHyperlocalFeedResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetHyperlocalFeedResponseV1.Size(m)
}
func (m *GetHyperlocalFeedResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperlocalFeedResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperlocalFeedResponseV1 proto.InternalMessageInfo

func (m *GetHyperlocalFeedResponseV1) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *GetHyperlocalFeedResponseV1) GetResults() []*GetHyperlocalFeedResponseV1_Content {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *GetHyperlocalFeedResponseV1) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetHyperlocalFeedResponseV1_Content struct {
	// Types that are valid to be assigned to Response:
	//	*GetHyperlocalFeedResponseV1_Content_ListingCard
	Response             isGetHyperlocalFeedResponseV1_Content_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *GetHyperlocalFeedResponseV1_Content) Reset()         { *m = GetHyperlocalFeedResponseV1_Content{} }
func (m *GetHyperlocalFeedResponseV1_Content) String() string { return proto.CompactTextString(m) }
func (*GetHyperlocalFeedResponseV1_Content) ProtoMessage()    {}
func (*GetHyperlocalFeedResponseV1_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{12, 0}
}

func (m *GetHyperlocalFeedResponseV1_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperlocalFeedResponseV1_Content.Unmarshal(m, b)
}
func (m *GetHyperlocalFeedResponseV1_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperlocalFeedResponseV1_Content.Marshal(b, m, deterministic)
}
func (m *GetHyperlocalFeedResponseV1_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperlocalFeedResponseV1_Content.Merge(m, src)
}
func (m *GetHyperlocalFeedResponseV1_Content) XXX_Size() int {
	return xxx_messageInfo_GetHyperlocalFeedResponseV1_Content.Size(m)
}
func (m *GetHyperlocalFeedResponseV1_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperlocalFeedResponseV1_Content.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperlocalFeedResponseV1_Content proto.InternalMessageInfo

type isGetHyperlocalFeedResponseV1_Content_Response interface {
	isGetHyperlocalFeedResponseV1_Content_Response()
}

type GetHyperlocalFeedResponseV1_Content_ListingCard struct {
	ListingCard *ListingCard `protobuf:"bytes,1,opt,name=listing_card,json=listingCard,proto3,oneof"`
}

func (*GetHyperlocalFeedResponseV1_Content_ListingCard) isGetHyperlocalFeedResponseV1_Content_Response() {
}

func (m *GetHyperlocalFeedResponseV1_Content) GetResponse() isGetHyperlocalFeedResponseV1_Content_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetHyperlocalFeedResponseV1_Content) GetListingCard() *ListingCard {
	if x, ok := m.GetResponse().(*GetHyperlocalFeedResponseV1_Content_ListingCard); ok {
		return x.ListingCard
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetHyperlocalFeedResponseV1_Content) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetHyperlocalFeedResponseV1_Content_ListingCard)(nil),
	}
}

type GetHyperlocalFeedRequestV2 struct {
	Count   *wrappers.Int32Value  `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	Session *wrappers.StringValue `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	// The geographical center
	Location *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// The hyperlocal filter id that user query
	FilterId int32 `protobuf:"varint,4,opt,name=filter_id,json=filterId,proto3" json:"filter_id,omitempty"`
	// The geographical search range
	Range *GeoRange `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	// The country ID
	CountryId *wrappers.Int64Value `protobuf:"bytes,6,opt,name=countryId,proto3" json:"countryId,omitempty"`
	// Instruct service to return non-cached result. Service decides whether or not to do so.
	ForceRefresh         bool               `protobuf:"varint,7,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	AuthUserContainer    *AuthUserContainer `protobuf:"bytes,14,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	ClientInfo           *ClientInfo        `protobuf:"bytes,15,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetHyperlocalFeedRequestV2) Reset()         { *m = GetHyperlocalFeedRequestV2{} }
func (m *GetHyperlocalFeedRequestV2) String() string { return proto.CompactTextString(m) }
func (*GetHyperlocalFeedRequestV2) ProtoMessage()    {}
func (*GetHyperlocalFeedRequestV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{13}
}

func (m *GetHyperlocalFeedRequestV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperlocalFeedRequestV2.Unmarshal(m, b)
}
func (m *GetHyperlocalFeedRequestV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperlocalFeedRequestV2.Marshal(b, m, deterministic)
}
func (m *GetHyperlocalFeedRequestV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperlocalFeedRequestV2.Merge(m, src)
}
func (m *GetHyperlocalFeedRequestV2) XXX_Size() int {
	return xxx_messageInfo_GetHyperlocalFeedRequestV2.Size(m)
}
func (m *GetHyperlocalFeedRequestV2) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperlocalFeedRequestV2.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperlocalFeedRequestV2 proto.InternalMessageInfo

func (m *GetHyperlocalFeedRequestV2) GetCount() *wrappers.Int32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV2) GetSession() *wrappers.StringValue {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV2) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV2) GetFilterId() int32 {
	if m != nil {
		return m.FilterId
	}
	return 0
}

func (m *GetHyperlocalFeedRequestV2) GetRange() *GeoRange {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV2) GetCountryId() *wrappers.Int64Value {
	if m != nil {
		return m.CountryId
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV2) GetForceRefresh() bool {
	if m != nil {
		return m.ForceRefresh
	}
	return false
}

func (m *GetHyperlocalFeedRequestV2) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

func (m *GetHyperlocalFeedRequestV2) GetClientInfo() *ClientInfo {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

type GetHyperlocalFeedResponseV2 struct {
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Array of nearby listings
	Results    []*GetHyperlocalFeedResponseV2_Content `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Pagination *Pagination                            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Details of hyperlocal filter
	Filters []*GetHyperlocalFeedResponseV2_Filter `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	// The hyperlocal filter id that user query
	FilterId             int32    `protobuf:"varint,5,opt,name=filter_id,json=filterId,proto3" json:"filter_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHyperlocalFeedResponseV2) Reset()         { *m = GetHyperlocalFeedResponseV2{} }
func (m *GetHyperlocalFeedResponseV2) String() string { return proto.CompactTextString(m) }
func (*GetHyperlocalFeedResponseV2) ProtoMessage()    {}
func (*GetHyperlocalFeedResponseV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{14}
}

func (m *GetHyperlocalFeedResponseV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2.Unmarshal(m, b)
}
func (m *GetHyperlocalFeedResponseV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2.Marshal(b, m, deterministic)
}
func (m *GetHyperlocalFeedResponseV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperlocalFeedResponseV2.Merge(m, src)
}
func (m *GetHyperlocalFeedResponseV2) XXX_Size() int {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2.Size(m)
}
func (m *GetHyperlocalFeedResponseV2) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperlocalFeedResponseV2.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperlocalFeedResponseV2 proto.InternalMessageInfo

func (m *GetHyperlocalFeedResponseV2) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *GetHyperlocalFeedResponseV2) GetResults() []*GetHyperlocalFeedResponseV2_Content {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *GetHyperlocalFeedResponseV2) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *GetHyperlocalFeedResponseV2) GetFilters() []*GetHyperlocalFeedResponseV2_Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *GetHyperlocalFeedResponseV2) GetFilterId() int32 {
	if m != nil {
		return m.FilterId
	}
	return 0
}

type GetHyperlocalFeedResponseV2_Content struct {
	// Types that are valid to be assigned to Response:
	//	*GetHyperlocalFeedResponseV2_Content_ListingCard
	Response             isGetHyperlocalFeedResponseV2_Content_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *GetHyperlocalFeedResponseV2_Content) Reset()         { *m = GetHyperlocalFeedResponseV2_Content{} }
func (m *GetHyperlocalFeedResponseV2_Content) String() string { return proto.CompactTextString(m) }
func (*GetHyperlocalFeedResponseV2_Content) ProtoMessage()    {}
func (*GetHyperlocalFeedResponseV2_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{14, 0}
}

func (m *GetHyperlocalFeedResponseV2_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2_Content.Unmarshal(m, b)
}
func (m *GetHyperlocalFeedResponseV2_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2_Content.Marshal(b, m, deterministic)
}
func (m *GetHyperlocalFeedResponseV2_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperlocalFeedResponseV2_Content.Merge(m, src)
}
func (m *GetHyperlocalFeedResponseV2_Content) XXX_Size() int {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2_Content.Size(m)
}
func (m *GetHyperlocalFeedResponseV2_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperlocalFeedResponseV2_Content.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperlocalFeedResponseV2_Content proto.InternalMessageInfo

type isGetHyperlocalFeedResponseV2_Content_Response interface {
	isGetHyperlocalFeedResponseV2_Content_Response()
}

type GetHyperlocalFeedResponseV2_Content_ListingCard struct {
	ListingCard *ListingCard `protobuf:"bytes,1,opt,name=listing_card,json=listingCard,proto3,oneof"`
}

func (*GetHyperlocalFeedResponseV2_Content_ListingCard) isGetHyperlocalFeedResponseV2_Content_Response() {
}

func (m *GetHyperlocalFeedResponseV2_Content) GetResponse() isGetHyperlocalFeedResponseV2_Content_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetHyperlocalFeedResponseV2_Content) GetListingCard() *ListingCard {
	if x, ok := m.GetResponse().(*GetHyperlocalFeedResponseV2_Content_ListingCard); ok {
		return x.ListingCard
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetHyperlocalFeedResponseV2_Content) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetHyperlocalFeedResponseV2_Content_ListingCard)(nil),
	}
}

type GetHyperlocalFeedResponseV2_Filter struct {
	// hyperlocal filter id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name on category chip
	DisplayedName        string   `protobuf:"bytes,2,opt,name=displayed_name,json=displayedName,proto3" json:"displayed_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHyperlocalFeedResponseV2_Filter) Reset()         { *m = GetHyperlocalFeedResponseV2_Filter{} }
func (m *GetHyperlocalFeedResponseV2_Filter) String() string { return proto.CompactTextString(m) }
func (*GetHyperlocalFeedResponseV2_Filter) ProtoMessage()    {}
func (*GetHyperlocalFeedResponseV2_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{14, 1}
}

func (m *GetHyperlocalFeedResponseV2_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2_Filter.Unmarshal(m, b)
}
func (m *GetHyperlocalFeedResponseV2_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2_Filter.Marshal(b, m, deterministic)
}
func (m *GetHyperlocalFeedResponseV2_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperlocalFeedResponseV2_Filter.Merge(m, src)
}
func (m *GetHyperlocalFeedResponseV2_Filter) XXX_Size() int {
	return xxx_messageInfo_GetHyperlocalFeedResponseV2_Filter.Size(m)
}
func (m *GetHyperlocalFeedResponseV2_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperlocalFeedResponseV2_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperlocalFeedResponseV2_Filter proto.InternalMessageInfo

func (m *GetHyperlocalFeedResponseV2_Filter) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetHyperlocalFeedResponseV2_Filter) GetDisplayedName() string {
	if m != nil {
		return m.DisplayedName
	}
	return ""
}

//*
// Sort parameter
//
// @param
// fieldname:
//		- If fieldName is null, it is popular sort.
//		- If fieldName is time_created, it is recent sort.  In this case, you do not need to put ascending field.  It is always working like ascending order.
//		- If fieldName is price and ascending is true, it is price ascending sort.
//		- If fieldName is price and ascending is false, it is price descending sort.
//		- If fieldName is location, it is nearby sort.  In this case, latitude and longitue should be put in GeoLocation of FilterParam.
// ascending: optional
type SortParam struct {
	FieldName            string              `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	Ascending            *wrappers.BoolValue `protobuf:"bytes,2,opt,name=ascending,proto3" json:"ascending,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SortParam) Reset()         { *m = SortParam{} }
func (m *SortParam) String() string { return proto.CompactTextString(m) }
func (*SortParam) ProtoMessage()    {}
func (*SortParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{15}
}

func (m *SortParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortParam.Unmarshal(m, b)
}
func (m *SortParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortParam.Marshal(b, m, deterministic)
}
func (m *SortParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortParam.Merge(m, src)
}
func (m *SortParam) XXX_Size() int {
	return xxx_messageInfo_SortParam.Size(m)
}
func (m *SortParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SortParam.DiscardUnknown(m)
}

var xxx_messageInfo_SortParam proto.InternalMessageInfo

func (m *SortParam) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *SortParam) GetAscending() *wrappers.BoolValue {
	if m != nil {
		return m.Ascending
	}
	return nil
}

//*
// Filter parameter
//
// @param
// fieldname: This should be same as the ES field name.
// filterType: Put in the filterType you want to search.
type FilterParam struct {
	FieldName string `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	// Types that are valid to be assigned to FilterType:
	//	*FilterParam_IdsOrKeywords
	//	*FilterParam_RangedInt
	//	*FilterParam_RangedFloat
	//	*FilterParam_RangedDate
	//	*FilterParam_GeoLocation
	//	*FilterParam_Boolean
	//	*FilterParam_ExactMatches
	//	*FilterParam_OrFilter
	//	*FilterParam_NotFilter
	//	*FilterParam_AndFilter
	FilterType           isFilterParam_FilterType `protobuf_oneof:"filterType"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FilterParam) Reset()         { *m = FilterParam{} }
func (m *FilterParam) String() string { return proto.CompactTextString(m) }
func (*FilterParam) ProtoMessage()    {}
func (*FilterParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{16}
}

func (m *FilterParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterParam.Unmarshal(m, b)
}
func (m *FilterParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterParam.Marshal(b, m, deterministic)
}
func (m *FilterParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterParam.Merge(m, src)
}
func (m *FilterParam) XXX_Size() int {
	return xxx_messageInfo_FilterParam.Size(m)
}
func (m *FilterParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterParam.DiscardUnknown(m)
}

var xxx_messageInfo_FilterParam proto.InternalMessageInfo

func (m *FilterParam) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

type isFilterParam_FilterType interface {
	isFilterParam_FilterType()
}

type FilterParam_IdsOrKeywords struct {
	IdsOrKeywords *IdsOrKeywords `protobuf:"bytes,4,opt,name=idsOrKeywords,proto3,oneof"`
}

type FilterParam_RangedInt struct {
	RangedInt *IntegerRange `protobuf:"bytes,3,opt,name=rangedInt,proto3,oneof"`
}

type FilterParam_RangedFloat struct {
	RangedFloat *FloatRange `protobuf:"bytes,6,opt,name=rangedFloat,proto3,oneof"`
}

type FilterParam_RangedDate struct {
	RangedDate *DateRange `protobuf:"bytes,7,opt,name=rangedDate,proto3,oneof"`
}

type FilterParam_GeoLocation struct {
	GeoLocation *GeoLocation `protobuf:"bytes,8,opt,name=geoLocation,proto3,oneof"`
}

type FilterParam_Boolean struct {
	Boolean *wrappers.BoolValue `protobuf:"bytes,9,opt,name=boolean,proto3,oneof"`
}

type FilterParam_ExactMatches struct {
	ExactMatches *ExactMatches `protobuf:"bytes,11,opt,name=exactMatches,proto3,oneof"`
}

type FilterParam_OrFilter struct {
	OrFilter *OrFilter `protobuf:"bytes,10,opt,name=orFilter,proto3,oneof"`
}

type FilterParam_NotFilter struct {
	NotFilter *NotFilter `protobuf:"bytes,12,opt,name=notFilter,proto3,oneof"`
}

type FilterParam_AndFilter struct {
	AndFilter *AndFilter `protobuf:"bytes,13,opt,name=andFilter,proto3,oneof"`
}

func (*FilterParam_IdsOrKeywords) isFilterParam_FilterType() {}

func (*FilterParam_RangedInt) isFilterParam_FilterType() {}

func (*FilterParam_RangedFloat) isFilterParam_FilterType() {}

func (*FilterParam_RangedDate) isFilterParam_FilterType() {}

func (*FilterParam_GeoLocation) isFilterParam_FilterType() {}

func (*FilterParam_Boolean) isFilterParam_FilterType() {}

func (*FilterParam_ExactMatches) isFilterParam_FilterType() {}

func (*FilterParam_OrFilter) isFilterParam_FilterType() {}

func (*FilterParam_NotFilter) isFilterParam_FilterType() {}

func (*FilterParam_AndFilter) isFilterParam_FilterType() {}

func (m *FilterParam) GetFilterType() isFilterParam_FilterType {
	if m != nil {
		return m.FilterType
	}
	return nil
}

func (m *FilterParam) GetIdsOrKeywords() *IdsOrKeywords {
	if x, ok := m.GetFilterType().(*FilterParam_IdsOrKeywords); ok {
		return x.IdsOrKeywords
	}
	return nil
}

func (m *FilterParam) GetRangedInt() *IntegerRange {
	if x, ok := m.GetFilterType().(*FilterParam_RangedInt); ok {
		return x.RangedInt
	}
	return nil
}

func (m *FilterParam) GetRangedFloat() *FloatRange {
	if x, ok := m.GetFilterType().(*FilterParam_RangedFloat); ok {
		return x.RangedFloat
	}
	return nil
}

func (m *FilterParam) GetRangedDate() *DateRange {
	if x, ok := m.GetFilterType().(*FilterParam_RangedDate); ok {
		return x.RangedDate
	}
	return nil
}

func (m *FilterParam) GetGeoLocation() *GeoLocation {
	if x, ok := m.GetFilterType().(*FilterParam_GeoLocation); ok {
		return x.GeoLocation
	}
	return nil
}

func (m *FilterParam) GetBoolean() *wrappers.BoolValue {
	if x, ok := m.GetFilterType().(*FilterParam_Boolean); ok {
		return x.Boolean
	}
	return nil
}

func (m *FilterParam) GetExactMatches() *ExactMatches {
	if x, ok := m.GetFilterType().(*FilterParam_ExactMatches); ok {
		return x.ExactMatches
	}
	return nil
}

func (m *FilterParam) GetOrFilter() *OrFilter {
	if x, ok := m.GetFilterType().(*FilterParam_OrFilter); ok {
		return x.OrFilter
	}
	return nil
}

func (m *FilterParam) GetNotFilter() *NotFilter {
	if x, ok := m.GetFilterType().(*FilterParam_NotFilter); ok {
		return x.NotFilter
	}
	return nil
}

func (m *FilterParam) GetAndFilter() *AndFilter {
	if x, ok := m.GetFilterType().(*FilterParam_AndFilter); ok {
		return x.AndFilter
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterParam) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterParam_IdsOrKeywords)(nil),
		(*FilterParam_RangedInt)(nil),
		(*FilterParam_RangedFloat)(nil),
		(*FilterParam_RangedDate)(nil),
		(*FilterParam_GeoLocation)(nil),
		(*FilterParam_Boolean)(nil),
		(*FilterParam_ExactMatches)(nil),
		(*FilterParam_OrFilter)(nil),
		(*FilterParam_NotFilter)(nil),
		(*FilterParam_AndFilter)(nil),
	}
}

type OrFilter struct {
	Filters              []*FilterParam `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OrFilter) Reset()         { *m = OrFilter{} }
func (m *OrFilter) String() string { return proto.CompactTextString(m) }
func (*OrFilter) ProtoMessage()    {}
func (*OrFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{17}
}

func (m *OrFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrFilter.Unmarshal(m, b)
}
func (m *OrFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrFilter.Marshal(b, m, deterministic)
}
func (m *OrFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrFilter.Merge(m, src)
}
func (m *OrFilter) XXX_Size() int {
	return xxx_messageInfo_OrFilter.Size(m)
}
func (m *OrFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_OrFilter.DiscardUnknown(m)
}

var xxx_messageInfo_OrFilter proto.InternalMessageInfo

func (m *OrFilter) GetFilters() []*FilterParam {
	if m != nil {
		return m.Filters
	}
	return nil
}

type NotFilter struct {
	Filters              []*FilterParam `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NotFilter) Reset()         { *m = NotFilter{} }
func (m *NotFilter) String() string { return proto.CompactTextString(m) }
func (*NotFilter) ProtoMessage()    {}
func (*NotFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{18}
}

func (m *NotFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotFilter.Unmarshal(m, b)
}
func (m *NotFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotFilter.Marshal(b, m, deterministic)
}
func (m *NotFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotFilter.Merge(m, src)
}
func (m *NotFilter) XXX_Size() int {
	return xxx_messageInfo_NotFilter.Size(m)
}
func (m *NotFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_NotFilter.DiscardUnknown(m)
}

var xxx_messageInfo_NotFilter proto.InternalMessageInfo

func (m *NotFilter) GetFilters() []*FilterParam {
	if m != nil {
		return m.Filters
	}
	return nil
}

type AndFilter struct {
	Filters              []*FilterParam `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AndFilter) Reset()         { *m = AndFilter{} }
func (m *AndFilter) String() string { return proto.CompactTextString(m) }
func (*AndFilter) ProtoMessage()    {}
func (*AndFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{19}
}

func (m *AndFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndFilter.Unmarshal(m, b)
}
func (m *AndFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndFilter.Marshal(b, m, deterministic)
}
func (m *AndFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndFilter.Merge(m, src)
}
func (m *AndFilter) XXX_Size() int {
	return xxx_messageInfo_AndFilter.Size(m)
}
func (m *AndFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AndFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AndFilter proto.InternalMessageInfo

func (m *AndFilter) GetFilters() []*FilterParam {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ExactMatches struct {
	Matches              []string `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExactMatches) Reset()         { *m = ExactMatches{} }
func (m *ExactMatches) String() string { return proto.CompactTextString(m) }
func (*ExactMatches) ProtoMessage()    {}
func (*ExactMatches) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{20}
}

func (m *ExactMatches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExactMatches.Unmarshal(m, b)
}
func (m *ExactMatches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExactMatches.Marshal(b, m, deterministic)
}
func (m *ExactMatches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExactMatches.Merge(m, src)
}
func (m *ExactMatches) XXX_Size() int {
	return xxx_messageInfo_ExactMatches.Size(m)
}
func (m *ExactMatches) XXX_DiscardUnknown() {
	xxx_messageInfo_ExactMatches.DiscardUnknown(m)
}

var xxx_messageInfo_ExactMatches proto.InternalMessageInfo

func (m *ExactMatches) GetMatches() []string {
	if m != nil {
		return m.Matches
	}
	return nil
}

//*
// Query parameter
//
// @param
// queryString: put in the query string the user choose; optional
type QueryParam struct {
	QueryString          string               `protobuf:"bytes,1,opt,name=queryString,proto3" json:"queryString,omitempty"`
	QueryType            QueryParam_QueryType `protobuf:"varint,2,opt,name=query_type,json=queryType,proto3,enum=ContentFeedService_proto.QueryParam_QueryType" json:"query_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryParam) Reset()         { *m = QueryParam{} }
func (m *QueryParam) String() string { return proto.CompactTextString(m) }
func (*QueryParam) ProtoMessage()    {}
func (*QueryParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{21}
}

func (m *QueryParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParam.Unmarshal(m, b)
}
func (m *QueryParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParam.Marshal(b, m, deterministic)
}
func (m *QueryParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParam.Merge(m, src)
}
func (m *QueryParam) XXX_Size() int {
	return xxx_messageInfo_QueryParam.Size(m)
}
func (m *QueryParam) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParam.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParam proto.InternalMessageInfo

func (m *QueryParam) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *QueryParam) GetQueryType() QueryParam_QueryType {
	if m != nil {
		return m.QueryType
	}
	return QueryParam_Default
}

//*
// SF Context
//
// @param
// collection_id: country collection id.
type SFContext struct {
	CollectionId         string   `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SFContext) Reset()         { *m = SFContext{} }
func (m *SFContext) String() string { return proto.CompactTextString(m) }
func (*SFContext) ProtoMessage()    {}
func (*SFContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{22}
}

func (m *SFContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SFContext.Unmarshal(m, b)
}
func (m *SFContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SFContext.Marshal(b, m, deterministic)
}
func (m *SFContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SFContext.Merge(m, src)
}
func (m *SFContext) XXX_Size() int {
	return xxx_messageInfo_SFContext.Size(m)
}
func (m *SFContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SFContext.DiscardUnknown(m)
}

var xxx_messageInfo_SFContext proto.InternalMessageInfo

func (m *SFContext) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

//*
// Image Search Context
//
// @param
// image_cache_id: a UUID for user re-visit image search result
// query_image: it's to show query image on result page (e.g. web)
type ImageSearchContext struct {
	ImageCacheId         string                           `protobuf:"bytes,1,opt,name=image_cache_id,json=imageCacheId,proto3" json:"image_cache_id,omitempty"`
	QueryImage           *ImageSearchContext_EncodedImage `protobuf:"bytes,2,opt,name=query_image,json=queryImage,proto3" json:"query_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ImageSearchContext) Reset()         { *m = ImageSearchContext{} }
func (m *ImageSearchContext) String() string { return proto.CompactTextString(m) }
func (*ImageSearchContext) ProtoMessage()    {}
func (*ImageSearchContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{23}
}

func (m *ImageSearchContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageSearchContext.Unmarshal(m, b)
}
func (m *ImageSearchContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageSearchContext.Marshal(b, m, deterministic)
}
func (m *ImageSearchContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageSearchContext.Merge(m, src)
}
func (m *ImageSearchContext) XXX_Size() int {
	return xxx_messageInfo_ImageSearchContext.Size(m)
}
func (m *ImageSearchContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageSearchContext.DiscardUnknown(m)
}

var xxx_messageInfo_ImageSearchContext proto.InternalMessageInfo

func (m *ImageSearchContext) GetImageCacheId() string {
	if m != nil {
		return m.ImageCacheId
	}
	return ""
}

func (m *ImageSearchContext) GetQueryImage() *ImageSearchContext_EncodedImage {
	if m != nil {
		return m.QueryImage
	}
	return nil
}

type ImageSearchContext_EncodedImage struct {
	EncodedImage         []byte                                 `protobuf:"bytes,1,opt,name=encoded_image,json=encodedImage,proto3" json:"encoded_image,omitempty"`
	Format               ImageSearchContext_EncodedImage_Format `protobuf:"varint,2,opt,name=format,proto3,enum=ContentFeedService_proto.ImageSearchContext_EncodedImage_Format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ImageSearchContext_EncodedImage) Reset()         { *m = ImageSearchContext_EncodedImage{} }
func (m *ImageSearchContext_EncodedImage) String() string { return proto.CompactTextString(m) }
func (*ImageSearchContext_EncodedImage) ProtoMessage()    {}
func (*ImageSearchContext_EncodedImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{23, 0}
}

func (m *ImageSearchContext_EncodedImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageSearchContext_EncodedImage.Unmarshal(m, b)
}
func (m *ImageSearchContext_EncodedImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageSearchContext_EncodedImage.Marshal(b, m, deterministic)
}
func (m *ImageSearchContext_EncodedImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageSearchContext_EncodedImage.Merge(m, src)
}
func (m *ImageSearchContext_EncodedImage) XXX_Size() int {
	return xxx_messageInfo_ImageSearchContext_EncodedImage.Size(m)
}
func (m *ImageSearchContext_EncodedImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageSearchContext_EncodedImage.DiscardUnknown(m)
}

var xxx_messageInfo_ImageSearchContext_EncodedImage proto.InternalMessageInfo

func (m *ImageSearchContext_EncodedImage) GetEncodedImage() []byte {
	if m != nil {
		return m.EncodedImage
	}
	return nil
}

func (m *ImageSearchContext_EncodedImage) GetFormat() ImageSearchContext_EncodedImage_Format {
	if m != nil {
		return m.Format
	}
	return ImageSearchContext_EncodedImage_UNKNOWN
}

// it's sharable across all messages
type Collection struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{24}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//*
// Pagination Context
//
// @param
// has_more: true if there is another page of results after this one
type PaginationContext struct {
	HasMore              bool     `protobuf:"varint,1,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationContext) Reset()         { *m = PaginationContext{} }
func (m *PaginationContext) String() string { return proto.CompactTextString(m) }
func (*PaginationContext) ProtoMessage()    {}
func (*PaginationContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{25}
}

func (m *PaginationContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationContext.Unmarshal(m, b)
}
func (m *PaginationContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationContext.Marshal(b, m, deterministic)
}
func (m *PaginationContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationContext.Merge(m, src)
}
func (m *PaginationContext) XXX_Size() int {
	return xxx_messageInfo_PaginationContext.Size(m)
}
func (m *PaginationContext) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationContext.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationContext proto.InternalMessageInfo

func (m *PaginationContext) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type Pagination struct {
	Total                *wrappers.Int64Value `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	HasMore              bool                 `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d95fb88423073, []int{26}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *Pagination) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func init() {
	proto.RegisterEnum("ContentFeedService_proto.Client", Client_name, Client_value)
	proto.RegisterEnum("ContentFeedService_proto.Version", Version_name, Version_value)
	proto.RegisterEnum("ContentFeedService_proto.QueryParam_QueryType", QueryParam_QueryType_name, QueryParam_QueryType_value)
	proto.RegisterEnum("ContentFeedService_proto.ImageSearchContext_EncodedImage_Format", ImageSearchContext_EncodedImage_Format_name, ImageSearchContext_EncodedImage_Format_value)
	proto.RegisterType((*SearchListingsResponseV34)(nil), "ContentFeedService_proto.SearchListingsResponseV34")
	proto.RegisterType((*SearchResponseV34)(nil), "ContentFeedService_proto.SearchResponseV34")
	proto.RegisterType((*GetUserLikedListingsRequestV3)(nil), "ContentFeedService_proto.GetUserLikedListingsRequestV3")
	proto.RegisterType((*SearchListingsResponseV33)(nil), "ContentFeedService_proto.SearchListingsResponseV33")
	proto.RegisterType((*SearchResponseV33)(nil), "ContentFeedService_proto.SearchResponseV33")
	proto.RegisterType((*GatewayRequestV30)(nil), "ContentFeedService_proto.GatewayRequestV30")
	proto.RegisterType((*GetSearchListingsTotalResponseV3)(nil), "ContentFeedService_proto.GetSearchListingsTotalResponseV3")
	proto.RegisterType((*SearchListingsRequestV3)(nil), "ContentFeedService_proto.SearchListingsRequestV3")
	proto.RegisterType((*SearchProfileListingsRequestV3)(nil), "ContentFeedService_proto.SearchProfileListingsRequestV3")
	proto.RegisterType((*SearchSpcListingsRequestV3)(nil), "ContentFeedService_proto.SearchSpcListingsRequestV3")
	proto.RegisterType((*GetMoreFromThisSellerFeedRequestV1)(nil), "ContentFeedService_proto.GetMoreFromThisSellerFeedRequestV1")
	proto.RegisterType((*GetHyperlocalFeedRequestV1)(nil), "ContentFeedService_proto.GetHyperlocalFeedRequestV1")
	proto.RegisterType((*GetHyperlocalFeedResponseV1)(nil), "ContentFeedService_proto.GetHyperlocalFeedResponseV1")
	proto.RegisterType((*GetHyperlocalFeedResponseV1_Content)(nil), "ContentFeedService_proto.GetHyperlocalFeedResponseV1.Content")
	proto.RegisterType((*GetHyperlocalFeedRequestV2)(nil), "ContentFeedService_proto.GetHyperlocalFeedRequestV2")
	proto.RegisterType((*GetHyperlocalFeedResponseV2)(nil), "ContentFeedService_proto.GetHyperlocalFeedResponseV2")
	proto.RegisterType((*GetHyperlocalFeedResponseV2_Content)(nil), "ContentFeedService_proto.GetHyperlocalFeedResponseV2.Content")
	proto.RegisterType((*GetHyperlocalFeedResponseV2_Filter)(nil), "ContentFeedService_proto.GetHyperlocalFeedResponseV2.Filter")
	proto.RegisterType((*SortParam)(nil), "ContentFeedService_proto.SortParam")
	proto.RegisterType((*FilterParam)(nil), "ContentFeedService_proto.FilterParam")
	proto.RegisterType((*OrFilter)(nil), "ContentFeedService_proto.OrFilter")
	proto.RegisterType((*NotFilter)(nil), "ContentFeedService_proto.NotFilter")
	proto.RegisterType((*AndFilter)(nil), "ContentFeedService_proto.AndFilter")
	proto.RegisterType((*ExactMatches)(nil), "ContentFeedService_proto.ExactMatches")
	proto.RegisterType((*QueryParam)(nil), "ContentFeedService_proto.QueryParam")
	proto.RegisterType((*SFContext)(nil), "ContentFeedService_proto.SFContext")
	proto.RegisterType((*ImageSearchContext)(nil), "ContentFeedService_proto.ImageSearchContext")
	proto.RegisterType((*ImageSearchContext_EncodedImage)(nil), "ContentFeedService_proto.ImageSearchContext.EncodedImage")
	proto.RegisterType((*Collection)(nil), "ContentFeedService_proto.Collection")
	proto.RegisterType((*PaginationContext)(nil), "ContentFeedService_proto.PaginationContext")
	proto.RegisterType((*Pagination)(nil), "ContentFeedService_proto.Pagination")
}

func init() { proto.RegisterFile("content-feed/search_v3.proto", fileDescriptor_0f4d95fb88423073) }

var fileDescriptor_0f4d95fb88423073 = []byte{
	// 2183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x59, 0xcd, 0x72, 0x1b, 0xc7,
	0x11, 0x26, 0x00, 0x12, 0xc4, 0x36, 0x40, 0x0a, 0x1a, 0x49, 0x16, 0x44, 0xc9, 0x36, 0xb3, 0xb2,
	0x62, 0x96, 0x13, 0x81, 0x12, 0xa9, 0x72, 0xc9, 0xf9, 0xb3, 0xf9, 0x4f, 0x48, 0x14, 0x49, 0x2f,
	0x28, 0x2a, 0x76, 0x0e, 0xeb, 0xe1, 0xee, 0x00, 0xd8, 0xf2, 0x62, 0x67, 0x35, 0x33, 0xa0, 0xc4,
	0x5b, 0x5e, 0x23, 0xc7, 0xbc, 0x40, 0x2e, 0x39, 0xe5, 0x09, 0x7c, 0x48, 0x5e, 0x23, 0xa9, 0x54,
	0x2e, 0x49, 0x55, 0xce, 0xa9, 0x4a, 0xcd, 0xcf, 0x2e, 0x16, 0xa4, 0xb0, 0x8c, 0x18, 0xc9, 0x29,
	0x3b, 0x27, 0xec, 0xf4, 0xf4, 0xd7, 0xd3, 0xd3, 0x7f, 0xd3, 0x33, 0x80, 0x5b, 0x1e, 0x8d, 0x04,
	0x89, 0xc4, 0xdd, 0x0e, 0x21, 0xfe, 0x22, 0x27, 0x98, 0x79, 0x3d, 0xf7, 0x78, 0xb9, 0x19, 0x33,
	0x2a, 0x28, 0x6a, 0xac, 0xe9, 0xd9, 0x4d, 0x42, 0xfc, 0x36, 0x61, 0xc7, 0x81, 0x47, 0x5c, 0x35,
	0x33, 0xf7, 0x7e, 0x97, 0xd2, 0x6e, 0x48, 0x16, 0xd5, 0xe8, 0x68, 0xd0, 0x59, 0x14, 0x41, 0x9f,
	0x70, 0x81, 0xfb, 0xb1, 0x86, 0xce, 0xbd, 0x77, 0x9a, 0xe1, 0x05, 0xc3, 0x71, 0x4c, 0x18, 0x37,
	0xf3, 0x37, 0x46, 0x16, 0xf6, 0x68, 0xbf, 0x4f, 0x23, 0x33, 0x35, 0x37, 0x32, 0x15, 0x06, 0x5c,
	0x04, 0x51, 0xd7, 0xcc, 0x5d, 0x1f, 0x85, 0x61, 0x91, 0xc8, 0xbb, 0x3d, 0x32, 0x71, 0x34, 0xe8,
	0xc7, 0x77, 0x05, 0x1d, 0x78, 0xbd, 0xbb, 0x31, 0x0d, 0x22, 0x61, 0x98, 0x1a, 0x23, 0x4c, 0x5d,
	0x46, 0x07, 0x46, 0x5d, 0xfb, 0xaf, 0x25, 0xb8, 0xd1, 0x56, 0xbb, 0xdf, 0xd1, 0xeb, 0x71, 0x87,
	0xf0, 0x98, 0x46, 0x9c, 0x1c, 0x2e, 0x3f, 0x40, 0x0d, 0x98, 0xe6, 0x84, 0xf3, 0x80, 0x46, 0x8d,
	0xc2, 0x7c, 0x61, 0xc1, 0x72, 0x92, 0x21, 0xda, 0x80, 0x69, 0x46, 0xf8, 0x20, 0x14, 0xbc, 0x51,
	0x9c, 0x2f, 0x2d, 0x54, 0x97, 0x7e, 0xd4, 0x1c, 0x67, 0xb3, 0xa6, 0x96, 0x9f, 0x91, 0xeb, 0x24,
	0x58, 0xb4, 0x0a, 0xc0, 0x3b, 0xae, 0xd2, 0xee, 0xa5, 0x68, 0x94, 0xe6, 0x0b, 0x0b, 0xd5, 0xa5,
	0xdb, 0x39, 0x92, 0x36, 0xd7, 0x34, 0xab, 0x63, 0xf1, 0x8e, 0xf9, 0x44, 0xf7, 0x61, 0x4a, 0x50,
	0x81, 0xc3, 0xc6, 0xa4, 0x82, 0xdf, 0x6c, 0x6a, 0x0f, 0x34, 0x13, 0x0f, 0x34, 0x5b, 0x91, 0xf8,
	0xf8, 0xc1, 0x21, 0x0e, 0x07, 0xc4, 0xd1, 0x9c, 0xe8, 0x31, 0x40, 0xc0, 0xd3, 0x65, 0xa7, 0x14,
	0xee, 0xc7, 0xe3, 0x97, 0x6d, 0xf5, 0x71, 0x97, 0xe8, 0x5d, 0xa4, 0xeb, 0x07, 0x3c, 0x59, 0xff,
	0x0b, 0xb8, 0x86, 0x8f, 0x71, 0x10, 0xe2, 0xa3, 0x90, 0xb8, 0x1e, 0x0d, 0x43, 0xe2, 0x89, 0x80,
	0x46, 0xbc, 0x51, 0x56, 0x86, 0xf9, 0x60, 0xbc, 0xdc, 0xb5, 0x94, 0xd9, 0xb9, 0x9a, 0x8a, 0x18,
	0x12, 0xb9, 0xd4, 0x33, 0xc6, 0xdd, 0x20, 0xc2, 0x72, 0xd8, 0x98, 0x56, 0x7a, 0xe6, 0x18, 0x7a,
	0x3f, 0xe5, 0x4d, 0xd4, 0xcc, 0xc0, 0xed, 0x7f, 0x95, 0xe1, 0xf2, 0x19, 0x57, 0xa0, 0x47, 0x50,
	0x33, 0x91, 0xe6, 0x7a, 0x98, 0xf9, 0xca, 0xcf, 0xd5, 0xa5, 0x3b, 0xe3, 0x17, 0x31, 0x71, 0xb2,
	0x86, 0x99, 0xbf, 0x3d, 0xe1, 0x54, 0xc3, 0xe1, 0x10, 0x79, 0x70, 0x2d, 0x66, 0xb4, 0x4f, 0x05,
	0xf1, 0xdd, 0x11, 0xa1, 0x45, 0x25, 0xf4, 0x6e, 0x8e, 0xe6, 0x06, 0x36, 0x2a, 0xfc, 0x4a, 0x7c,
	0x96, 0x8c, 0xb6, 0xa0, 0x4a, 0x5e, 0x0a, 0xc2, 0x22, 0x1c, 0xba, 0xd8, 0x37, 0x31, 0x93, 0x63,
	0xe4, 0x0d, 0xc3, 0xbc, 0x22, 0x25, 0x02, 0x49, 0x47, 0xe8, 0x2b, 0xb8, 0x2a, 0xd3, 0xc5, 0x55,
	0xe9, 0xa2, 0xb2, 0x45, 0x2b, 0x3b, 0x79, 0x5e, 0x38, 0xac, 0x0e, 0xfa, 0xf1, 0x81, 0x04, 0xed,
	0x4b, 0x90, 0xd1, 0x15, 0x1d, 0x25, 0xd4, 0x38, 0xa1, 0x4a, 0x7b, 0xa8, 0x5c, 0x73, 0x63, 0xca,
	0x45, 0x26, 0x34, 0x4c, 0xc4, 0xe5, 0xd8, 0x63, 0x4b, 0xc2, 0xf6, 0x29, 0x17, 0xc3, 0x68, 0x90,
	0xf6, 0xe8, 0x9e, 0x25, 0xa3, 0x0e, 0xbc, 0x13, 0x33, 0xda, 0x09, 0x42, 0x85, 0xed, 0x53, 0x49,
	0xd4, 0x1b, 0x29, 0xab, 0x55, 0x9a, 0xb9, 0x56, 0x97, 0xb8, 0xfd, 0x04, 0x66, 0xb6, 0x72, 0x35,
	0x7e, 0x05, 0x1d, 0x7d, 0x0e, 0x97, 0x52, 0xbb, 0x1f, 0x07, 0xbe, 0xb4, 0xbd, 0x0e, 0xc8, 0x0f,
	0xcf, 0xb7, 0xfd, 0x61, 0xe0, 0x2b, 0xf3, 0xcf, 0x90, 0x2c, 0x01, 0x0d, 0xe0, 0xa6, 0x4f, 0xfc,
	0xc0, 0xc3, 0x32, 0x60, 0x78, 0x4c, 0x45, 0x18, 0x74, 0x7b, 0xc2, 0xe5, 0xc6, 0x4a, 0x15, 0x25,
	0x7e, 0x79, 0xbc, 0xf8, 0xf5, 0x04, 0xdc, 0x4e, 0xb0, 0xed, 0xd4, 0x56, 0x37, 0xfc, 0x71, 0x93,
	0x28, 0x80, 0xeb, 0xbc, 0x47, 0x07, 0x82, 0x0e, 0xc4, 0x69, 0x93, 0x59, 0x6a, 0xc9, 0xc5, 0x9c,
	0x0a, 0x64, 0x80, 0xa7, 0x6d, 0x76, 0x8d, 0xbf, 0x6a, 0x62, 0x15, 0xa0, 0xc2, 0x4c, 0xb2, 0xd9,
	0x7f, 0x2c, 0xc0, 0xbb, 0x5b, 0x44, 0x3c, 0xe5, 0x84, 0xed, 0x04, 0x5f, 0xa7, 0x41, 0xcd, 0x1d,
	0xf2, 0x7c, 0x40, 0xb8, 0x38, 0x5c, 0x46, 0xbf, 0x82, 0x2b, 0x78, 0x20, 0x7a, 0xee, 0x80, 0x13,
	0xa6, 0xaa, 0x13, 0x0e, 0x22, 0xc2, 0x4c, 0x4a, 0xe6, 0xe4, 0xfd, 0xca, 0x40, 0xf4, 0xa4, 0xd8,
	0xb5, 0x04, 0xe2, 0x5c, 0xc6, 0xa7, 0x49, 0xe8, 0x2a, 0x4c, 0x71, 0x81, 0x99, 0x50, 0xc9, 0x58,
	0x72, 0xf4, 0x40, 0x52, 0x3d, 0x3a, 0x88, 0x74, 0xed, 0x2d, 0x39, 0x7a, 0x80, 0x7e, 0x00, 0x35,
	0x69, 0xba, 0x2e, 0x65, 0x27, 0x6e, 0xe0, 0xf3, 0xc6, 0xe4, 0x7c, 0x69, 0xc1, 0x72, 0xaa, 0x09,
	0xad, 0xe5, 0x73, 0xfb, 0x9f, 0x85, 0xf1, 0x07, 0xc7, 0xf2, 0x5b, 0x3a, 0x38, 0x96, 0xff, 0xd7,
	0x07, 0x87, 0xfd, 0x9b, 0xe2, 0xd9, 0x1a, 0xba, 0xfc, 0xff, 0x5b, 0x43, 0x47, 0xe2, 0xfb, 0xf7,
	0x53, 0x70, 0x79, 0x0b, 0x0b, 0xf2, 0x02, 0x9f, 0xa4, 0x21, 0x7d, 0x4f, 0x1a, 0x59, 0x07, 0x58,
	0x71, 0xbc, 0x91, 0x97, 0x97, 0x8c, 0x91, 0x75, 0xf4, 0x7d, 0x3c, 0x0c, 0x1e, 0xad, 0xd9, 0xad,
	0x33, 0xa0, 0xb6, 0x60, 0x41, 0xd4, 0xd5, 0xa8, 0x34, 0xb4, 0x56, 0xc0, 0xe2, 0x94, 0x89, 0x7d,
	0xcc, 0x70, 0xdf, 0xf8, 0x34, 0x2f, 0x24, 0x12, 0x56, 0x67, 0x88, 0x42, 0x9f, 0xc2, 0x74, 0x27,
	0x08, 0x05, 0x61, 0xbc, 0x31, 0xa5, 0xa2, 0x33, 0xc7, 0x89, 0x9b, 0x8a, 0x51, 0x8b, 0x48, 0x50,
	0xe8, 0x27, 0x30, 0xf5, 0x7c, 0x40, 0xd8, 0x89, 0x29, 0xbe, 0x39, 0x36, 0xfd, 0x5c, 0xb2, 0x69,
	0xb4, 0x86, 0xa0, 0x4f, 0xc0, 0x52, 0x06, 0x90, 0x09, 0x66, 0x6a, 0x6b, 0x6e, 0x4c, 0x0e, 0xb9,
	0xd1, 0x1c, 0x54, 0xe2, 0x10, 0x8b, 0x0e, 0x65, 0x7d, 0x55, 0x36, 0x2d, 0x27, 0x1d, 0xa3, 0x77,
	0xa0, 0x1c, 0x52, 0x0f, 0x87, 0x44, 0x55, 0x37, 0xcb, 0x31, 0x23, 0xf4, 0x10, 0xca, 0x5e, 0x18,
	0x90, 0x48, 0x34, 0xaa, 0xf3, 0x85, 0x85, 0xd9, 0xa5, 0xf9, 0x9c, 0x46, 0x45, 0xf1, 0x39, 0x86,
	0x1f, 0xdd, 0x81, 0x59, 0xec, 0x1f, 0x13, 0x26, 0x02, 0x2e, 0xc3, 0x33, 0xf0, 0x1b, 0x33, 0x4a,
	0xf2, 0x4c, 0x86, 0xda, 0xf2, 0xd1, 0x3c, 0xd4, 0x7c, 0xea, 0x46, 0x54, 0xb8, 0x82, 0x61, 0xef,
	0xeb, 0xc6, 0xec, 0x7c, 0x61, 0xa1, 0xe2, 0x80, 0x4f, 0x77, 0xa9, 0x38, 0x90, 0x14, 0x99, 0xc5,
	0xd8, 0x77, 0x8f, 0x09, 0x53, 0xce, 0xbe, 0xa4, 0xd4, 0xc8, 0x71, 0xd9, 0x8a, 0x7f, 0xa8, 0x59,
	0x1d, 0x0b, 0x27, 0x9f, 0x72, 0xeb, 0x9c, 0x86, 0x7e, 0x3b, 0xa4, 0xa2, 0x51, 0x57, 0x2b, 0xa4,
	0x63, 0x59, 0xc7, 0x82, 0x6e, 0x44, 0x99, 0xec, 0xcb, 0x64, 0x0c, 0x22, 0x35, 0x5f, 0xd5, 0xb4,
	0x35, 0x49, 0xb2, 0x9f, 0xc2, 0xfc, 0x16, 0x11, 0xa3, 0x95, 0xec, 0x40, 0xe6, 0xfa, 0x30, 0xc1,
	0x87, 0x85, 0xa2, 0xf0, 0x1f, 0x17, 0x8a, 0x3f, 0x15, 0xe0, 0xfa, 0xe9, 0xf2, 0xf8, 0xad, 0x94,
	0xf9, 0x03, 0xb8, 0xd4, 0xd5, 0x49, 0xe8, 0x32, 0xbd, 0xa2, 0x49, 0x85, 0x1c, 0xc1, 0x67, 0xb2,
	0xd6, 0x99, 0xed, 0x8e, 0x90, 0xec, 0x7f, 0x14, 0xe0, 0x3d, 0xbd, 0x1d, 0xd3, 0x33, 0x7c, 0x1f,
	0x76, 0x85, 0x6e, 0x82, 0xa5, 0xb4, 0x8d, 0x70, 0x9f, 0xa8, 0x9e, 0xcc, 0x72, 0x2a, 0x92, 0xb0,
	0x8b, 0xfb, 0xc4, 0xfe, 0x73, 0x01, 0xe6, 0xf4, 0x96, 0xdb, 0xb1, 0xf7, 0xbd, 0xd8, 0xae, 0xec,
	0x00, 0x62, 0xaf, 0xe5, 0x9b, 0xad, 0xea, 0x81, 0xfd, 0x97, 0x02, 0xd8, 0x5b, 0x44, 0x3c, 0xa1,
	0x8c, 0x6c, 0x32, 0xda, 0x3f, 0xe8, 0x05, 0xbc, 0x4d, 0xc2, 0x90, 0x30, 0xb9, 0x44, 0x22, 0xed,
	0xfe, 0xdb, 0xdd, 0xef, 0xbb, 0x00, 0x31, 0xa3, 0xfe, 0xc0, 0x13, 0xb2, 0x98, 0x14, 0x95, 0x7a,
	0x96, 0xa1, 0xb4, 0x7c, 0xb4, 0x0e, 0xa0, 0x2b, 0x4f, 0x2b, 0xea, 0xd0, 0xf3, 0x4f, 0xab, 0xb5,
	0x94, 0xd7, 0xc9, 0xe0, 0xec, 0xbf, 0x15, 0x61, 0x6e, 0x8b, 0x88, 0xed, 0x93, 0x98, 0x30, 0x55,
	0x02, 0x47, 0x37, 0x98, 0x1e, 0x54, 0x85, 0x8b, 0x1c, 0x54, 0xc5, 0xd7, 0x39, 0xa8, 0x7e, 0x01,
	0x15, 0xa9, 0x80, 0x18, 0x9e, 0x70, 0x76, 0x4e, 0xaf, 0x60, 0x38, 0x9d, 0x14, 0x33, 0xce, 0x17,
	0xb3, 0x6f, 0xc4, 0x17, 0xa3, 0xc6, 0xbe, 0x74, 0x41, 0x63, 0xff, 0xa1, 0x08, 0x37, 0x5f, 0x61,
	0x6c, 0x53, 0x52, 0xef, 0xe7, 0x34, 0x88, 0xcf, 0x4e, 0x37, 0x88, 0x3f, 0xcf, 0x89, 0xf9, 0xf1,
	0x2b, 0x24, 0xa0, 0x61, 0xcb, 0xb8, 0x3e, 0x72, 0x99, 0x3e, 0x37, 0x8a, 0x86, 0x97, 0xe9, 0xec,
	0x2d, 0x7a, 0x0e, 0xc3, 0xb4, 0x81, 0xbc, 0xc9, 0xb6, 0x6f, 0xa4, 0x91, 0xfa, 0xed, 0x64, 0x4e,
	0xa0, 0x2e, 0x7d, 0x97, 0x02, 0xf5, 0x26, 0x58, 0xba, 0x31, 0x92, 0x69, 0x2d, 0x2b, 0xd8, 0x94,
	0x53, 0xd1, 0x84, 0x96, 0x8f, 0x1e, 0xc2, 0x14, 0xc3, 0x51, 0x97, 0x98, 0xdb, 0xb0, 0x9d, 0xe7,
	0x66, 0xea, 0x48, 0x4e, 0x47, 0x03, 0x46, 0x1b, 0xa5, 0xf2, 0x6b, 0x35, 0x4a, 0xb7, 0x61, 0xa6,
	0x43, 0x99, 0x47, 0x5c, 0x46, 0x3a, 0x8c, 0xf0, 0x9e, 0xea, 0xb3, 0x2a, 0x4e, 0x4d, 0x11, 0x1d,
	0x4d, 0xfb, 0x2e, 0xe4, 0xd7, 0xdf, 0x4b, 0x79, 0xf9, 0xb5, 0xf4, 0xd6, 0xf3, 0x6b, 0xe9, 0x2d,
	0xe5, 0x17, 0x3a, 0x1c, 0x76, 0xe0, 0x93, 0x4a, 0xbd, 0x9f, 0x5d, 0x4c, 0x3d, 0xdd, 0x9d, 0x0f,
	0x1b, 0xf3, 0x91, 0x50, 0x9c, 0x1a, 0x0d, 0xc5, 0x6f, 0x21, 0xa9, 0xe7, 0x3e, 0x85, 0xb2, 0x56,
	0x09, 0xcd, 0x42, 0x31, 0xd0, 0x72, 0xa7, 0x9c, 0x62, 0xe0, 0xcb, 0x6e, 0xda, 0x0f, 0x78, 0x1c,
	0xe2, 0x13, 0xe2, 0xeb, 0x56, 0x44, 0x1f, 0x80, 0x33, 0x29, 0x55, 0xf5, 0x23, 0x1e, 0x58, 0xe9,
	0x95, 0x05, 0xdd, 0x92, 0xbb, 0x21, 0xa1, 0x9a, 0x31, 0x0e, 0x1e, 0x12, 0xd0, 0x43, 0xb0, 0x30,
	0xf7, 0x48, 0xe4, 0x07, 0x51, 0xd7, 0x24, 0xfc, 0xdc, 0x99, 0xfc, 0x58, 0xa5, 0x34, 0x34, 0xe9,
	0x91, 0x32, 0xdb, 0xbf, 0x2e, 0x43, 0x35, 0x73, 0xaf, 0x39, 0x67, 0x9d, 0x3d, 0x98, 0x09, 0x7c,
	0xbe, 0xc7, 0x1e, 0x93, 0x93, 0x17, 0x94, 0xa9, 0x77, 0x82, 0x73, 0x1e, 0x84, 0x5a, 0x59, 0xf6,
	0xed, 0x09, 0x67, 0x14, 0x8f, 0x36, 0xc1, 0x52, 0x19, 0xee, 0xb7, 0xa2, 0xe4, 0x52, 0xff, 0xc3,
	0x1c, 0x61, 0x91, 0x20, 0x5d, 0xc2, 0x54, 0x69, 0xd8, 0x9e, 0x70, 0x86, 0x50, 0xb4, 0x0d, 0x55,
	0x3d, 0xd8, 0x0c, 0x29, 0x16, 0xe7, 0xdf, 0xc5, 0x14, 0x5b, 0x22, 0x27, 0x0b, 0x45, 0x1b, 0x00,
	0x7a, 0xb8, 0x8e, 0x05, 0x31, 0x97, 0xb2, 0x9c, 0x1b, 0x8a, 0xe4, 0x4a, 0xe4, 0x64, 0x80, 0xa8,
	0x05, 0xd5, 0x2e, 0xa1, 0x49, 0x85, 0x34, 0x2f, 0x5b, 0x77, 0x72, 0x2b, 0x5e, 0xc2, 0x2c, 0x35,
	0xca, 0x60, 0x65, 0x2d, 0x3f, 0xa2, 0x34, 0x24, 0x38, 0x32, 0xaf, 0x55, 0x39, 0xae, 0xdd, 0x9e,
	0x70, 0x12, 0x66, 0xb4, 0x03, 0x35, 0xf2, 0x12, 0x7b, 0xe2, 0x09, 0x16, 0x5e, 0x8f, 0x70, 0x75,
	0xe9, 0xcb, 0x35, 0xef, 0x46, 0x86, 0x7b, 0x7b, 0xc2, 0x19, 0x41, 0xa3, 0xcf, 0xa0, 0x42, 0x99,
	0x8e, 0x94, 0x06, 0x9c, 0x57, 0xbf, 0xf7, 0x0c, 0xe7, 0xf6, 0x84, 0x93, 0xa2, 0xd0, 0x1a, 0x58,
	0x11, 0x15, 0x46, 0x44, 0xed, 0x3c, 0xc3, 0xee, 0x26, 0xac, 0xd2, 0xd1, 0x29, 0x4e, 0x0a, 0xc1,
	0x91, 0x6f, 0x84, 0xcc, 0x9c, 0x27, 0x64, 0x25, 0x61, 0x95, 0x42, 0x52, 0xdc, 0x6a, 0x0d, 0x40,
	0x57, 0x82, 0x83, 0x93, 0x98, 0xd8, 0x8f, 0xa1, 0x92, 0xe8, 0x9b, 0x7d, 0x0e, 0x28, 0x5c, 0xe4,
	0x39, 0xc0, 0xde, 0x01, 0x2b, 0xd5, 0xfc, 0x8d, 0x48, 0x4b, 0xb7, 0xf0, 0xdf, 0x4b, 0x5b, 0x80,
	0x5a, 0xd6, 0xc5, 0xf2, 0xc8, 0xe8, 0x9b, 0xd8, 0x28, 0xa8, 0xf7, 0xbe, 0x64, 0x68, 0x7f, 0x53,
	0x00, 0x18, 0x3e, 0x57, 0xa0, 0x79, 0xa8, 0xaa, 0x07, 0x0b, 0xdd, 0x32, 0x98, 0xb2, 0x90, 0x25,
	0xa1, 0x27, 0x00, 0x6a, 0xe8, 0x8a, 0x93, 0x58, 0x97, 0xb3, 0xd9, 0xbc, 0x77, 0xe8, 0xa1, 0x6c,
	0xfd, 0x29, 0xfd, 0xe0, 0x58, 0xcf, 0x93, 0x4f, 0x7b, 0x1b, 0xac, 0x94, 0x8e, 0xaa, 0x30, 0xbd,
	0x4e, 0x3a, 0x78, 0x10, 0x8a, 0xfa, 0x04, 0x9a, 0x01, 0xeb, 0x20, 0x10, 0x21, 0xd9, 0x8b, 0xc2,
	0x93, 0x7a, 0x01, 0xd5, 0xa0, 0xb2, 0x4e, 0xb8, 0xa7, 0x46, 0x45, 0x74, 0x19, 0x66, 0xd4, 0x64,
	0x4a, 0x2a, 0xd9, 0xf7, 0xc0, 0x4a, 0x9f, 0x02, 0x65, 0x2f, 0x30, 0x7c, 0x93, 0x77, 0x4d, 0x4d,
	0xb6, 0x9c, 0xda, 0x90, 0xd8, 0xf2, 0xed, 0x6f, 0x8a, 0x80, 0xce, 0xfe, 0xff, 0x83, 0x3e, 0x80,
	0xd9, 0x40, 0x52, 0x5d, 0x0f, 0x7b, 0x3d, 0x92, 0x01, 0x2b, 0xea, 0x9a, 0x24, 0xb6, 0x7c, 0xf4,
	0xa5, 0xb1, 0x94, 0xab, 0xa8, 0xa6, 0x14, 0x7f, 0xf2, 0x3a, 0x7f, 0x34, 0x35, 0x37, 0x22, 0x8f,
	0xfa, 0xc4, 0x57, 0x33, 0x8e, 0xb6, 0xaa, 0xfa, 0x9e, 0xfb, 0x5d, 0x01, 0x6a, 0xd9, 0x49, 0xb9,
	0x1d, 0xa2, 0xc7, 0x66, 0x39, 0xa9, 0x51, 0xcd, 0xa9, 0x91, 0x2c, 0xd3, 0x2f, 0xa1, 0xdc, 0xa1,
	0xac, 0x8f, 0x85, 0xf1, 0xca, 0x67, 0x17, 0x56, 0xa6, 0xb9, 0xa9, 0xe4, 0x38, 0x46, 0x9e, 0xfd,
	0x3e, 0x94, 0x35, 0x45, 0x7a, 0xe8, 0xe9, 0xee, 0xe3, 0xdd, 0xbd, 0x67, 0xbb, 0xf5, 0x09, 0x54,
	0x81, 0xc9, 0x47, 0xfb, 0x1b, 0x5b, 0xf5, 0x82, 0x7d, 0x0f, 0x20, 0xf3, 0xb7, 0xc5, 0xf0, 0x14,
	0xb4, 0xd4, 0x29, 0x88, 0x60, 0x32, 0x73, 0xf6, 0xa9, 0x6f, 0xbb, 0x09, 0x97, 0xcf, 0xfc, 0xa5,
	0x85, 0x6e, 0x40, 0xa5, 0x87, 0xb9, 0xdb, 0xa7, 0x4c, 0xef, 0xb0, 0xe2, 0x4c, 0xf7, 0x30, 0x97,
	0xd7, 0x57, 0xfb, 0x2b, 0x80, 0x21, 0xff, 0x05, 0x5e, 0x6d, 0x46, 0x64, 0x97, 0x46, 0x64, 0x3f,
	0x9a, 0xac, 0x14, 0xeb, 0xa5, 0x8f, 0x3e, 0x84, 0xb2, 0x6e, 0xc8, 0xd0, 0x34, 0x94, 0x5a, 0x7b,
	0xed, 0xfa, 0x84, 0xdc, 0xed, 0xca, 0xee, 0xba, 0xb3, 0xd7, 0x5a, 0xaf, 0x17, 0x24, 0xf5, 0xd9,
	0xc6, 0x6a, 0xbd, 0xf8, 0xd1, 0x03, 0x98, 0x4e, 0x1e, 0xa8, 0xae, 0xc0, 0x25, 0x63, 0x0e, 0xf7,
	0x70, 0xc3, 0x69, 0xb7, 0xf6, 0xa4, 0x59, 0xae, 0x42, 0xbd, 0xdd, 0xda, 0xdd, 0xda, 0xd9, 0x70,
	0xdb, 0x3b, 0x7b, 0x07, 0xee, 0xde, 0xee, 0xce, 0x17, 0xf5, 0xc2, 0xea, 0xfe, 0x97, 0xbb, 0xdd,
	0x40, 0xf4, 0x06, 0x47, 0x4d, 0x8f, 0xf6, 0x17, 0x3d, 0xcc, 0xe8, 0x80, 0x93, 0x30, 0x5c, 0xe4,
	0x3d, 0xcc, 0x88, 0x7f, 0x57, 0x69, 0xbe, 0xd8, 0x25, 0xd1, 0x62, 0x97, 0x2e, 0x66, 0xff, 0xd2,
	0xfd, 0xe9, 0x38, 0x27, 0x1e, 0x95, 0xd5, 0xcf, 0xf2, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xde,
	0x32, 0x9b, 0x1a, 0xf0, 0x1e, 0x00, 0x00,
}
