// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content-feed/user.proto

package ContentFeedService_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserSortParam_SortType int32

const (
	UserSortParam_SORT_TYPE_UNSPECIFIED UserSortParam_SortType = 0
)

var UserSortParam_SortType_name = map[int32]string{
	0: "SORT_TYPE_UNSPECIFIED",
}

var UserSortParam_SortType_value = map[string]int32{
	"SORT_TYPE_UNSPECIFIED": 0,
}

func (x UserSortParam_SortType) String() string {
	return proto.EnumName(UserSortParam_SortType_name, int32(x))
}

func (UserSortParam_SortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{2, 0}
}

type SearchUsersRequestV1 struct {
	// Page size
	// Should be less or equal to 100. For numbers greater than 100, 100 will be used instead.
	Count                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	Session              *wrappers.StringValue `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Query                *UserQueryParam       `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	CountryId            *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	Sort                 *UserSortParam        `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	IncludeDebuggingInfo bool                  `protobuf:"varint,15,opt,name=include_debugging_info,json=includeDebuggingInfo,proto3" json:"include_debugging_info,omitempty"`
	AuthUserContainer    *AuthUserContainer    `protobuf:"bytes,16,opt,name=auth_user_container,json=authUserContainer,proto3" json:"auth_user_container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SearchUsersRequestV1) Reset()         { *m = SearchUsersRequestV1{} }
func (m *SearchUsersRequestV1) String() string { return proto.CompactTextString(m) }
func (*SearchUsersRequestV1) ProtoMessage()    {}
func (*SearchUsersRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{0}
}

func (m *SearchUsersRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUsersRequestV1.Unmarshal(m, b)
}
func (m *SearchUsersRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUsersRequestV1.Marshal(b, m, deterministic)
}
func (m *SearchUsersRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUsersRequestV1.Merge(m, src)
}
func (m *SearchUsersRequestV1) XXX_Size() int {
	return xxx_messageInfo_SearchUsersRequestV1.Size(m)
}
func (m *SearchUsersRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUsersRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUsersRequestV1 proto.InternalMessageInfo

func (m *SearchUsersRequestV1) GetCount() *wrappers.UInt32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *SearchUsersRequestV1) GetSession() *wrappers.StringValue {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SearchUsersRequestV1) GetQuery() *UserQueryParam {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchUsersRequestV1) GetCountryId() *wrappers.UInt32Value {
	if m != nil {
		return m.CountryId
	}
	return nil
}

func (m *SearchUsersRequestV1) GetSort() *UserSortParam {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *SearchUsersRequestV1) GetIncludeDebuggingInfo() bool {
	if m != nil {
		return m.IncludeDebuggingInfo
	}
	return false
}

func (m *SearchUsersRequestV1) GetAuthUserContainer() *AuthUserContainer {
	if m != nil {
		return m.AuthUserContainer
	}
	return nil
}

type UserQueryParam struct {
	// The query string to search
	QueryString          string   `protobuf:"bytes,1,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserQueryParam) Reset()         { *m = UserQueryParam{} }
func (m *UserQueryParam) String() string { return proto.CompactTextString(m) }
func (*UserQueryParam) ProtoMessage()    {}
func (*UserQueryParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{1}
}

func (m *UserQueryParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQueryParam.Unmarshal(m, b)
}
func (m *UserQueryParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQueryParam.Marshal(b, m, deterministic)
}
func (m *UserQueryParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQueryParam.Merge(m, src)
}
func (m *UserQueryParam) XXX_Size() int {
	return xxx_messageInfo_UserQueryParam.Size(m)
}
func (m *UserQueryParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQueryParam.DiscardUnknown(m)
}

var xxx_messageInfo_UserQueryParam proto.InternalMessageInfo

func (m *UserQueryParam) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

type UserSortParam struct {
	Type                 UserSortParam_SortType `protobuf:"varint,1,opt,name=type,proto3,enum=ContentFeedService_proto.UserSortParam_SortType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserSortParam) Reset()         { *m = UserSortParam{} }
func (m *UserSortParam) String() string { return proto.CompactTextString(m) }
func (*UserSortParam) ProtoMessage()    {}
func (*UserSortParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{2}
}

func (m *UserSortParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSortParam.Unmarshal(m, b)
}
func (m *UserSortParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSortParam.Marshal(b, m, deterministic)
}
func (m *UserSortParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSortParam.Merge(m, src)
}
func (m *UserSortParam) XXX_Size() int {
	return xxx_messageInfo_UserSortParam.Size(m)
}
func (m *UserSortParam) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSortParam.DiscardUnknown(m)
}

var xxx_messageInfo_UserSortParam proto.InternalMessageInfo

func (m *UserSortParam) GetType() UserSortParam_SortType {
	if m != nil {
		return m.Type
	}
	return UserSortParam_SORT_TYPE_UNSPECIFIED
}

type SearchUsersResponseV1 struct {
	Contents             []*SearchUsersResponseV1_Content     `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	Pagination           *SearchUsersResponseV1_Pagination    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DebuggingInfo        *SearchUsersResponseV1_DebuggingInfo `protobuf:"bytes,10,opt,name=debugging_info,json=debuggingInfo,proto3" json:"debugging_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *SearchUsersResponseV1) Reset()         { *m = SearchUsersResponseV1{} }
func (m *SearchUsersResponseV1) String() string { return proto.CompactTextString(m) }
func (*SearchUsersResponseV1) ProtoMessage()    {}
func (*SearchUsersResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{3}
}

func (m *SearchUsersResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUsersResponseV1.Unmarshal(m, b)
}
func (m *SearchUsersResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUsersResponseV1.Marshal(b, m, deterministic)
}
func (m *SearchUsersResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUsersResponseV1.Merge(m, src)
}
func (m *SearchUsersResponseV1) XXX_Size() int {
	return xxx_messageInfo_SearchUsersResponseV1.Size(m)
}
func (m *SearchUsersResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUsersResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUsersResponseV1 proto.InternalMessageInfo

func (m *SearchUsersResponseV1) GetContents() []*SearchUsersResponseV1_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *SearchUsersResponseV1) GetPagination() *SearchUsersResponseV1_Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *SearchUsersResponseV1) GetDebuggingInfo() *SearchUsersResponseV1_DebuggingInfo {
	if m != nil {
		return m.DebuggingInfo
	}
	return nil
}

type SearchUsersResponseV1_Content struct {
	// Types that are valid to be assigned to Response:
	//	*SearchUsersResponseV1_Content_User
	Response             isSearchUsersResponseV1_Content_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *SearchUsersResponseV1_Content) Reset()         { *m = SearchUsersResponseV1_Content{} }
func (m *SearchUsersResponseV1_Content) String() string { return proto.CompactTextString(m) }
func (*SearchUsersResponseV1_Content) ProtoMessage()    {}
func (*SearchUsersResponseV1_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{3, 0}
}

func (m *SearchUsersResponseV1_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUsersResponseV1_Content.Unmarshal(m, b)
}
func (m *SearchUsersResponseV1_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUsersResponseV1_Content.Marshal(b, m, deterministic)
}
func (m *SearchUsersResponseV1_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUsersResponseV1_Content.Merge(m, src)
}
func (m *SearchUsersResponseV1_Content) XXX_Size() int {
	return xxx_messageInfo_SearchUsersResponseV1_Content.Size(m)
}
func (m *SearchUsersResponseV1_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUsersResponseV1_Content.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUsersResponseV1_Content proto.InternalMessageInfo

type isSearchUsersResponseV1_Content_Response interface {
	isSearchUsersResponseV1_Content_Response()
}

type SearchUsersResponseV1_Content_User struct {
	User *User `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

func (*SearchUsersResponseV1_Content_User) isSearchUsersResponseV1_Content_Response() {}

func (m *SearchUsersResponseV1_Content) GetResponse() isSearchUsersResponseV1_Content_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SearchUsersResponseV1_Content) GetUser() *User {
	if x, ok := m.GetResponse().(*SearchUsersResponseV1_Content_User); ok {
		return x.User
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SearchUsersResponseV1_Content) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SearchUsersResponseV1_Content_User)(nil),
	}
}

type SearchUsersResponseV1_Pagination struct {
	Total                *wrappers.Int64Value `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	HasMore              bool                 `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Session              string               `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchUsersResponseV1_Pagination) Reset()         { *m = SearchUsersResponseV1_Pagination{} }
func (m *SearchUsersResponseV1_Pagination) String() string { return proto.CompactTextString(m) }
func (*SearchUsersResponseV1_Pagination) ProtoMessage()    {}
func (*SearchUsersResponseV1_Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{3, 1}
}

func (m *SearchUsersResponseV1_Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUsersResponseV1_Pagination.Unmarshal(m, b)
}
func (m *SearchUsersResponseV1_Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUsersResponseV1_Pagination.Marshal(b, m, deterministic)
}
func (m *SearchUsersResponseV1_Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUsersResponseV1_Pagination.Merge(m, src)
}
func (m *SearchUsersResponseV1_Pagination) XXX_Size() int {
	return xxx_messageInfo_SearchUsersResponseV1_Pagination.Size(m)
}
func (m *SearchUsersResponseV1_Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUsersResponseV1_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUsersResponseV1_Pagination proto.InternalMessageInfo

func (m *SearchUsersResponseV1_Pagination) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *SearchUsersResponseV1_Pagination) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *SearchUsersResponseV1_Pagination) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

// Debugging information for us to get info of each query.
// It returns only for staff accounts.
type SearchUsersResponseV1_DebuggingInfo struct {
	SearchQueries        []*SearchUsersResponseV1_DebuggingInfo_SearchQuery `protobuf:"bytes,3,rep,name=search_queries,json=searchQueries,proto3" json:"search_queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *SearchUsersResponseV1_DebuggingInfo) Reset()         { *m = SearchUsersResponseV1_DebuggingInfo{} }
func (m *SearchUsersResponseV1_DebuggingInfo) String() string { return proto.CompactTextString(m) }
func (*SearchUsersResponseV1_DebuggingInfo) ProtoMessage()    {}
func (*SearchUsersResponseV1_DebuggingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{3, 2}
}

func (m *SearchUsersResponseV1_DebuggingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo.Unmarshal(m, b)
}
func (m *SearchUsersResponseV1_DebuggingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo.Marshal(b, m, deterministic)
}
func (m *SearchUsersResponseV1_DebuggingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo.Merge(m, src)
}
func (m *SearchUsersResponseV1_DebuggingInfo) XXX_Size() int {
	return xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo.Size(m)
}
func (m *SearchUsersResponseV1_DebuggingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo proto.InternalMessageInfo

func (m *SearchUsersResponseV1_DebuggingInfo) GetSearchQueries() []*SearchUsersResponseV1_DebuggingInfo_SearchQuery {
	if m != nil {
		return m.SearchQueries
	}
	return nil
}

type SearchUsersResponseV1_DebuggingInfo_SearchQuery struct {
	EsQuery              string   `protobuf:"bytes,2,opt,name=es_query,json=esQuery,proto3" json:"es_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) Reset() {
	*m = SearchUsersResponseV1_DebuggingInfo_SearchQuery{}
}
func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) String() string {
	return proto.CompactTextString(m)
}
func (*SearchUsersResponseV1_DebuggingInfo_SearchQuery) ProtoMessage() {}
func (*SearchUsersResponseV1_DebuggingInfo_SearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{3, 2, 0}
}

func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo_SearchQuery.Unmarshal(m, b)
}
func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo_SearchQuery.Marshal(b, m, deterministic)
}
func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo_SearchQuery.Merge(m, src)
}
func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) XXX_Size() int {
	return xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo_SearchQuery.Size(m)
}
func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo_SearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUsersResponseV1_DebuggingInfo_SearchQuery proto.InternalMessageInfo

func (m *SearchUsersResponseV1_DebuggingInfo_SearchQuery) GetEsQuery() string {
	if m != nil {
		return m.EsQuery
	}
	return ""
}

type User struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Profile              *Profile             `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Username             string               `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string               `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateJoined           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=date_joined,json=dateJoined,proto3" json:"date_joined,omitempty"`
	IsActive             bool                 `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsBlocked            bool                 `protobuf:"varint,15,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetDateJoined() *timestamp.Timestamp {
	if m != nil {
		return m.DateJoined
	}
	return nil
}

func (m *User) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *User) GetIsBlocked() bool {
	if m != nil {
		return m.IsBlocked
	}
	return false
}

type Profile struct {
	Id                          int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl                    string   `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Image                       string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageProgressiveUrl         string   `protobuf:"bytes,4,opt,name=image_progressive_url,json=imageProgressiveUrl,proto3" json:"image_progressive_url,omitempty"`
	ImageProgressiveLowRange    int64    `protobuf:"varint,5,opt,name=image_progressive_low_range,json=imageProgressiveLowRange,proto3" json:"image_progressive_low_range,omitempty"`
	ImageProgressiveMediumRange int64    `protobuf:"varint,6,opt,name=image_progressive_medium_range,json=imageProgressiveMediumRange,proto3" json:"image_progressive_medium_range,omitempty"`
	Bio                         string   `protobuf:"bytes,20,opt,name=bio,proto3" json:"bio,omitempty"`
	IsDeactivated               bool     `protobuf:"varint,40,opt,name=is_deactivated,json=isDeactivated,proto3" json:"is_deactivated,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c106010c23917a14, []int{5}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Profile) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Profile) GetImageProgressiveUrl() string {
	if m != nil {
		return m.ImageProgressiveUrl
	}
	return ""
}

func (m *Profile) GetImageProgressiveLowRange() int64 {
	if m != nil {
		return m.ImageProgressiveLowRange
	}
	return 0
}

func (m *Profile) GetImageProgressiveMediumRange() int64 {
	if m != nil {
		return m.ImageProgressiveMediumRange
	}
	return 0
}

func (m *Profile) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Profile) GetIsDeactivated() bool {
	if m != nil {
		return m.IsDeactivated
	}
	return false
}

func init() {
	proto.RegisterEnum("ContentFeedService_proto.UserSortParam_SortType", UserSortParam_SortType_name, UserSortParam_SortType_value)
	proto.RegisterType((*SearchUsersRequestV1)(nil), "ContentFeedService_proto.SearchUsersRequestV1")
	proto.RegisterType((*UserQueryParam)(nil), "ContentFeedService_proto.UserQueryParam")
	proto.RegisterType((*UserSortParam)(nil), "ContentFeedService_proto.UserSortParam")
	proto.RegisterType((*SearchUsersResponseV1)(nil), "ContentFeedService_proto.SearchUsersResponseV1")
	proto.RegisterType((*SearchUsersResponseV1_Content)(nil), "ContentFeedService_proto.SearchUsersResponseV1.Content")
	proto.RegisterType((*SearchUsersResponseV1_Pagination)(nil), "ContentFeedService_proto.SearchUsersResponseV1.Pagination")
	proto.RegisterType((*SearchUsersResponseV1_DebuggingInfo)(nil), "ContentFeedService_proto.SearchUsersResponseV1.DebuggingInfo")
	proto.RegisterType((*SearchUsersResponseV1_DebuggingInfo_SearchQuery)(nil), "ContentFeedService_proto.SearchUsersResponseV1.DebuggingInfo.SearchQuery")
	proto.RegisterType((*User)(nil), "ContentFeedService_proto.User")
	proto.RegisterType((*Profile)(nil), "ContentFeedService_proto.Profile")
}

func init() { proto.RegisterFile("content-feed/user.proto", fileDescriptor_c106010c23917a14) }

var fileDescriptor_c106010c23917a14 = []byte{
	// 959 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x6d, 0x6f, 0x1b, 0x45,
	0x10, 0x6e, 0xfc, 0x92, 0x5c, 0x26, 0xc4, 0x84, 0x6d, 0x02, 0x17, 0x07, 0x42, 0x6a, 0xa9, 0xc2,
	0x12, 0xaa, 0x4d, 0x9c, 0xa8, 0x48, 0x44, 0x45, 0x6a, 0x5e, 0x2a, 0x5c, 0x68, 0x30, 0xe7, 0x24,
	0x12, 0xe5, 0xc3, 0x69, 0xed, 0x1b, 0x9f, 0x17, 0xee, 0x6e, 0xaf, 0xbb, 0x7b, 0x89, 0x22, 0xf1,
	0x5f, 0xf8, 0xc2, 0x37, 0x7e, 0x03, 0x3f, 0x83, 0xff, 0x83, 0x76, 0xee, 0x9c, 0xc4, 0x31, 0xae,
	0x5a, 0xf1, 0xc9, 0xb7, 0xf3, 0xcc, 0xf3, 0xec, 0xec, 0x33, 0xb3, 0x6b, 0xf8, 0x64, 0x28, 0x13,
	0x83, 0x89, 0x79, 0x32, 0x42, 0x0c, 0xda, 0x99, 0x46, 0xd5, 0x4a, 0x95, 0x34, 0x92, 0xb9, 0x47,
	0x39, 0xf0, 0x02, 0x31, 0xe8, 0xa3, 0xba, 0x14, 0x43, 0xf4, 0x09, 0xa9, 0x7f, 0x1e, 0x4a, 0x19,
	0x46, 0xd8, 0xa6, 0xd5, 0x20, 0x1b, 0xb5, 0x8d, 0x88, 0x51, 0x1b, 0x1e, 0xa7, 0x39, 0xb5, 0xbe,
	0x7d, 0x3f, 0xe1, 0x4a, 0xf1, 0x34, 0x45, 0xa5, 0x0b, 0x7c, 0x73, 0x6a, 0xcf, 0xa1, 0x8c, 0x63,
	0x99, 0xe4, 0x50, 0xe3, 0x9f, 0x32, 0xac, 0xf7, 0x91, 0xab, 0xe1, 0xf8, 0x5c, 0xa3, 0xd2, 0x1e,
	0xbe, 0xc9, 0x50, 0x9b, 0x8b, 0x5d, 0xd6, 0x81, 0xea, 0x50, 0x66, 0x89, 0x71, 0x17, 0x76, 0x16,
	0x9a, 0x2b, 0x9d, 0x4f, 0x5b, 0xf9, 0x1e, 0xad, 0xc9, 0x1e, 0xad, 0xf3, 0x6e, 0x62, 0xf6, 0x3a,
	0x17, 0x3c, 0xca, 0xd0, 0xcb, 0x53, 0xd9, 0x53, 0x58, 0xd2, 0xa8, 0xb5, 0x90, 0x89, 0x5b, 0x9a,
	0xc3, 0xea, 0x1b, 0x25, 0x92, 0x30, 0x67, 0x4d, 0x92, 0xd9, 0xb7, 0x50, 0x7d, 0x93, 0xa1, 0xba,
	0x76, 0xcb, 0xc4, 0x6a, 0xb6, 0xe6, 0x59, 0xd1, 0xb2, 0x45, 0xfe, 0x64, 0x53, 0x7b, 0x5c, 0xf1,
	0xd8, 0xcb, 0x69, 0xec, 0x00, 0x80, 0x0a, 0x50, 0xd7, 0xbe, 0x08, 0xdc, 0xca, 0x3b, 0x14, 0xbc,
	0x5c, 0xe4, 0x77, 0x03, 0x76, 0x00, 0x15, 0x2d, 0x95, 0x71, 0x17, 0x89, 0xf6, 0xc5, 0xdb, 0xf7,
	0xee, 0x4b, 0x65, 0xf2, 0xad, 0x89, 0xc4, 0xf6, 0xe1, 0x63, 0x91, 0x0c, 0xa3, 0x2c, 0x40, 0x3f,
	0xc0, 0x41, 0x16, 0x86, 0x22, 0x09, 0x7d, 0x91, 0x8c, 0xa4, 0xfb, 0xe1, 0xce, 0x42, 0xd3, 0xf1,
	0xd6, 0x0b, 0xf4, 0x78, 0x02, 0x76, 0x93, 0x91, 0x64, 0xbf, 0xc0, 0x43, 0x9e, 0x99, 0xb1, 0x6f,
	0xbb, 0xef, 0xdb, 0xde, 0x70, 0x91, 0xa0, 0x72, 0xd7, 0xa8, 0x82, 0x2f, 0xe7, 0x57, 0xf0, 0x3c,
	0x33, 0xd4, 0xa6, 0xa3, 0x09, 0xc5, 0xfb, 0x88, 0xdf, 0x0f, 0xbd, 0xac, 0x38, 0xd5, 0xb5, 0xc5,
	0xc6, 0x1e, 0xd4, 0xa6, 0xbd, 0x62, 0x8f, 0xe0, 0x03, 0x72, 0xcb, 0xd7, 0xd4, 0x02, 0xea, 0xeb,
	0xb2, 0xb7, 0x42, 0xb1, 0xbc, 0x2b, 0x8d, 0xdf, 0x61, 0x75, 0xea, 0x90, 0xec, 0x18, 0x2a, 0xe6,
	0x3a, 0x45, 0xca, 0xad, 0x75, 0xbe, 0x7a, 0x47, 0x6f, 0x5a, 0xf6, 0xeb, 0xec, 0x3a, 0x45, 0x8f,
	0xd8, 0x8d, 0xc7, 0xe0, 0x4c, 0x22, 0x6c, 0x13, 0x36, 0xfa, 0x3f, 0x7a, 0x67, 0xfe, 0xd9, 0xcf,
	0xbd, 0x13, 0xff, 0xfc, 0xb4, 0xdf, 0x3b, 0x39, 0xea, 0xbe, 0xe8, 0x9e, 0x1c, 0xaf, 0x3d, 0x68,
	0xfc, 0x51, 0x85, 0x8d, 0xa9, 0x51, 0xd4, 0xa9, 0x4c, 0x34, 0x5e, 0xec, 0xb2, 0x3e, 0x38, 0xc5,
	0x04, 0x6b, 0x77, 0x61, 0xa7, 0xdc, 0x5c, 0xe9, 0x7c, 0x3d, 0xbf, 0x94, 0xff, 0x94, 0x98, 0xa4,
	0x7b, 0x37, 0x42, 0xec, 0x35, 0x40, 0xca, 0x43, 0x91, 0x70, 0x73, 0x3b, 0xaf, 0xdf, 0xbc, 0xaf,
	0x6c, 0xef, 0x46, 0xc1, 0xbb, 0xa3, 0xc6, 0x02, 0xa8, 0xdd, 0x1b, 0x07, 0x20, 0xfd, 0x67, 0xef,
	0xab, 0x3f, 0x35, 0x37, 0xde, 0x6a, 0x70, 0x77, 0x59, 0xff, 0x1e, 0x96, 0x0a, 0x39, 0xb6, 0x0f,
	0x15, 0x3b, 0x4c, 0xc5, 0x65, 0xdd, 0x7e, 0x7b, 0xa3, 0xbe, 0x7b, 0xe0, 0x51, 0xf6, 0x21, 0x80,
	0xa3, 0x8a, 0xbd, 0xea, 0x06, 0xe0, 0xf6, 0x30, 0x6c, 0x17, 0xaa, 0x46, 0x1a, 0x1e, 0x15, 0x82,
	0x5b, 0x33, 0x97, 0xa9, 0x9b, 0x98, 0xa7, 0xfb, 0xc5, 0xe5, 0xa7, 0x4c, 0xb6, 0x09, 0xce, 0x98,
	0x6b, 0x3f, 0x96, 0x0a, 0xc9, 0x4d, 0xc7, 0x5b, 0x1a, 0x73, 0xfd, 0x4a, 0x2a, 0x64, 0xee, 0xed,
	0xbb, 0x50, 0xa6, 0xa9, 0x9b, 0x2c, 0xeb, 0x7f, 0x2d, 0xc0, 0xea, 0xf4, 0xdd, 0x48, 0xa1, 0xa6,
	0xc9, 0x0a, 0xdf, 0x4e, 0xa6, 0x40, 0xed, 0x96, 0xa9, 0xe3, 0xdd, 0xff, 0x65, 0x5d, 0x91, 0x43,
	0xd7, 0xc1, 0x5b, 0xd5, 0x37, 0x0b, 0x81, 0xba, 0xde, 0x84, 0x95, 0x3b, 0xa8, 0x3d, 0x07, 0x6a,
	0x3f, 0x7f, 0x8f, 0x4a, 0x79, 0xb5, 0xa8, 0x09, 0x6a, 0xfc, 0x59, 0x82, 0x8a, 0xdd, 0x86, 0xd5,
	0xa0, 0x24, 0x02, 0xf2, 0xa6, 0xec, 0x95, 0x84, 0x7d, 0x43, 0x96, 0x52, 0x25, 0x47, 0x22, 0xc2,
	0x62, 0x90, 0x1e, 0xcd, 0xaf, 0xb6, 0x97, 0x27, 0x7a, 0x13, 0x06, 0xab, 0x83, 0x63, 0xbb, 0x91,
	0xf0, 0x18, 0x0b, 0x7b, 0x6e, 0xd6, 0xec, 0x33, 0x80, 0x91, 0x50, 0xda, 0xf8, 0x84, 0x56, 0x08,
	0x5d, 0xa6, 0xc8, 0xa9, 0x85, 0xb7, 0x60, 0x39, 0xe2, 0x13, 0xb4, 0x9a, 0x73, 0x6d, 0x80, 0xc0,
	0x03, 0x58, 0x09, 0xb8, 0x41, 0xff, 0x57, 0x29, 0x12, 0x0c, 0x8a, 0x09, 0xac, 0xcf, 0x74, 0xf2,
	0x6c, 0xf2, 0x67, 0xe2, 0x81, 0x4d, 0x7f, 0x49, 0xd9, 0x56, 0x59, 0x68, 0x9f, 0x0f, 0x8d, 0xb8,
	0x44, 0xd7, 0xa1, 0x76, 0x3a, 0x42, 0x3f, 0xa7, 0xb5, 0xad, 0x4a, 0x68, 0x7f, 0x10, 0xc9, 0xe1,
	0x6f, 0x18, 0x14, 0x2f, 0xdd, 0xb2, 0xd0, 0x87, 0x79, 0xa0, 0xf1, 0x77, 0x09, 0x96, 0x8a, 0x53,
	0xce, 0x38, 0x65, 0x75, 0x63, 0x1e, 0xa2, 0x9f, 0xa9, 0xa8, 0xb0, 0xd7, 0xa1, 0xc0, 0xb9, 0x8a,
	0xd8, 0x3a, 0x54, 0xe9, 0xbb, 0xb0, 0x21, 0x5f, 0xb0, 0x0e, 0x6c, 0xe4, 0x94, 0x54, 0xc9, 0x50,
	0xd9, 0xc1, 0xb9, 0xcc, 0xe9, 0xb9, 0x1d, 0x0f, 0x09, 0xec, 0xdd, 0x62, 0x56, 0xe9, 0x19, 0x6c,
	0xcd, 0x72, 0x22, 0x79, 0xe5, 0x2b, 0x9e, 0x84, 0xb9, 0x55, 0x65, 0xcf, 0xbd, 0xcf, 0xfc, 0x41,
	0x5e, 0x79, 0x16, 0x67, 0x47, 0xb0, 0x3d, 0x4b, 0x8f, 0x31, 0x10, 0x59, 0x5c, 0x28, 0x2c, 0x92,
	0xc2, 0xd6, 0x7d, 0x85, 0x57, 0x94, 0x93, 0x8b, 0xac, 0x41, 0x79, 0x20, 0xa4, 0xbb, 0x4e, 0x55,
	0xda, 0x4f, 0xf6, 0x18, 0x6a, 0x42, 0xfb, 0x01, 0x92, 0xad, 0xdc, 0x60, 0xe0, 0x36, 0xc9, 0xbb,
	0x55, 0xa1, 0x8f, 0x6f, 0x83, 0x87, 0xbd, 0xd7, 0xa7, 0xa1, 0x30, 0xe3, 0x6c, 0xd0, 0x1a, 0xca,
	0xb8, 0x3d, 0xe4, 0x4a, 0x66, 0x1a, 0xa3, 0xa8, 0xad, 0xc7, 0x5c, 0x61, 0xf0, 0x84, 0x3a, 0xd7,
	0x0e, 0x31, 0x69, 0x87, 0xb2, 0x7d, 0xf7, 0x9f, 0xfd, 0x60, 0xde, 0xcc, 0x0d, 0x16, 0xe9, 0x67,
	0xef, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xe3, 0x57, 0xff, 0x7d, 0x08, 0x00, 0x00,
}
